<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 성과 및 위험 평가 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기</title>
  <meta name="description" content="Chapter 13 성과 및 위험 평가 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 성과 및 위험 평가 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 성과 및 위험 평가 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기" />
  
  
  

<meta name="author" content="이현열" />


<meta name="date" content="2019-06-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="section-78.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<script src="libs/proj4js-2.3.15/proj4.js"></script>
<link href="libs/highcharts-7.0.1/css/motion.css" rel="stylesheet" />
<link href="libs/highcharts-7.0.1/css/htmlwdgtgrid.css" rel="stylesheet" />
<script src="libs/highcharts-7.0.1/highcharts.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-3d.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-more.js"></script>
<script src="libs/highcharts-7.0.1/modules/stock.js"></script>
<script src="libs/highcharts-7.0.1/modules/map.js"></script>
<script src="libs/highcharts-7.0.1/modules/annotations.js"></script>
<script src="libs/highcharts-7.0.1/modules/boost.js"></script>
<script src="libs/highcharts-7.0.1/modules/data.js"></script>
<script src="libs/highcharts-7.0.1/modules/drag-panes.js"></script>
<script src="libs/highcharts-7.0.1/modules/drilldown.js"></script>
<script src="libs/highcharts-7.0.1/modules/item-series.js"></script>
<script src="libs/highcharts-7.0.1/modules/offline-exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/overlapping-datalabels.js"></script>
<script src="libs/highcharts-7.0.1/modules/exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/export-data.js"></script>
<script src="libs/highcharts-7.0.1/modules/funnel.js"></script>
<script src="libs/highcharts-7.0.1/modules/heatmap.js"></script>
<script src="libs/highcharts-7.0.1/modules/treemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/sankey.js"></script>
<script src="libs/highcharts-7.0.1/modules/solid-gauge.js"></script>
<script src="libs/highcharts-7.0.1/modules/streamgraph.js"></script>
<script src="libs/highcharts-7.0.1/modules/sunburst.js"></script>
<script src="libs/highcharts-7.0.1/modules/vector.js"></script>
<script src="libs/highcharts-7.0.1/modules/wordcloud.js"></script>
<script src="libs/highcharts-7.0.1/modules/xrange.js"></script>
<script src="libs/highcharts-7.0.1/modules/tilemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/venn.js"></script>
<script src="libs/highcharts-7.0.1/modules/gantt.js"></script>
<script src="libs/highcharts-7.0.1/modules/timeline.js"></script>
<script src="libs/highcharts-7.0.1/modules/parallel-coordinates.js"></script>
<script src="libs/highcharts-7.0.1/plugins/grouped-categories.js"></script>
<script src="libs/highcharts-7.0.1/plugins/motion.js"></script>
<script src="libs/highcharts-7.0.1/plugins/multicolor_series.js"></script>
<script src="libs/highcharts-7.0.1/custom/reset.js"></script>
<script src="libs/highcharts-7.0.1/custom/symbols-extra.js"></script>
<script src="libs/highcharts-7.0.1/custom/text-symbols.js"></script>
<script src="libs/highchart-binding-0.7.0/highchart.js"></script>
<script src="libs/plotly-binding-4.9.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.46.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.46.1/plotly-latest.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">퀀트 투자 쿡북</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>여는 글</a></li>
<li class="chapter" data-level="1" data-path="section-1.html"><a href="section-1.html"><i class="fa fa-check"></i><b>1</b> 퀀트 투자의 심장: 데이터와 프로그래밍</a><ul>
<li class="chapter" data-level="1.1" data-path="section-1.html"><a href="section-1.html#section-2"><i class="fa fa-check"></i><b>1.1</b> 데이터 구하기</a></li>
<li class="chapter" data-level="1.2" data-path="section-1.html"><a href="section-1.html#section-3"><i class="fa fa-check"></i><b>1.2</b> 퀀트 투자와 프로그래밍</a></li>
<li class="chapter" data-level="1.3" data-path="section-1.html"><a href="section-1.html#r-"><i class="fa fa-check"></i><b>1.3</b> R 프로그램</a></li>
<li class="chapter" data-level="1.4" data-path="section-1.html"><a href="section-1.html#r--1"><i class="fa fa-check"></i><b>1.4</b> 퀀트 투자에 유용한 R 패키지</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="section-4.html"><a href="section-4.html"><i class="fa fa-check"></i><b>2</b> 크롤링을 위한 기본 지식</a><ul>
<li class="chapter" data-level="2.1" data-path="section-4.html"><a href="section-4.html#r-utf-8-"><i class="fa fa-check"></i><b>2.1</b> 인코딩의 이해와 R에서 UTF-8 설정하기</a><ul>
<li class="chapter" data-level="2.1.1" data-path="section-4.html"><a href="section-4.html#ascii"><i class="fa fa-check"></i><b>2.1.1</b> 인간과 컴퓨터 간 번역의 시작, ASCII</a></li>
<li class="chapter" data-level="2.1.2" data-path="section-4.html"><a href="section-4.html#section-5"><i class="fa fa-check"></i><b>2.1.2</b> 한글 인코딩의 종류</a></li>
<li class="chapter" data-level="2.1.3" data-path="section-4.html"><a href="section-4.html#r-utf-8--1"><i class="fa fa-check"></i><b>2.1.3</b> R에서 UTF-8 설정하기</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="section-4.html"><a href="section-4.html#section-6"><i class="fa fa-check"></i><b>2.2</b> 웹의 동작 방식</a><ul>
<li class="chapter" data-level="2.2.1" data-path="section-4.html"><a href="section-4.html#http"><i class="fa fa-check"></i><b>2.2.1</b> HTTP</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="section-4.html"><a href="section-4.html#html-css-"><i class="fa fa-check"></i><b>2.3</b> HTML과 CSS 이해하기</a><ul>
<li class="chapter" data-level="2.3.1" data-path="section-4.html"><a href="section-4.html#html--"><i class="fa fa-check"></i><b>2.3.1</b> HTML 기본 구조</a></li>
<li class="chapter" data-level="2.3.2" data-path="section-4.html"><a href="section-4.html#section-7"><i class="fa fa-check"></i><b>2.3.2</b> 태그와 속성</a></li>
<li class="chapter" data-level="2.3.3" data-path="section-4.html"><a href="section-4.html#h--p-"><i class="fa fa-check"></i><b>2.3.3</b> h 태그와 p 태그</a></li>
<li class="chapter" data-level="2.3.4" data-path="section-4.html"><a href="section-4.html#ul-ol-"><i class="fa fa-check"></i><b>2.3.4</b> 리스트: ul과 ol 태그</a></li>
<li class="chapter" data-level="2.3.5" data-path="section-4.html"><a href="section-4.html#table-"><i class="fa fa-check"></i><b>2.3.5</b> table 태그</a></li>
<li class="chapter" data-level="2.3.6" data-path="section-4.html"><a href="section-4.html#a-src--"><i class="fa fa-check"></i><b>2.3.6</b> a, src 태그와 속성</a></li>
<li class="chapter" data-level="2.3.7" data-path="section-4.html"><a href="section-4.html#div-"><i class="fa fa-check"></i><b>2.3.7</b> div 태그</a></li>
<li class="chapter" data-level="2.3.8" data-path="section-4.html"><a href="section-4.html#css"><i class="fa fa-check"></i><b>2.3.8</b> CSS</a></li>
<li class="chapter" data-level="2.3.9" data-path="section-4.html"><a href="section-4.html#class-id"><i class="fa fa-check"></i><b>2.3.9</b> class와 id</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="section-4.html"><a href="section-4.html#section-8"><i class="fa fa-check"></i><b>2.4</b> 파이프 오퍼레이터 (<code>%&gt;%</code>)</a></li>
<li class="chapter" data-level="2.5" data-path="section-4.html"><a href="section-4.html#section-9"><i class="fa fa-check"></i><b>2.5</b> 오류에 대한 예외처리</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="api-.html"><a href="api-.html"><i class="fa fa-check"></i><b>3</b> API를 이용한 데이터 수집</a><ul>
<li class="chapter" data-level="3.1" data-path="api-.html"><a href="api-.html#api--quandl--"><i class="fa fa-check"></i><b>3.1</b> API를 이용한 Quandl 데이터 다운로드</a></li>
<li class="chapter" data-level="3.2" data-path="api-.html"><a href="api-.html#getsymbols---api-"><i class="fa fa-check"></i><b>3.2</b> <code>getSymbols()</code> 함수를 이용한 API 다운로드</a><ul>
<li class="chapter" data-level="3.2.1" data-path="api-.html"><a href="api-.html#section-10"><i class="fa fa-check"></i><b>3.2.1</b> 주가 다운로드</a></li>
<li class="chapter" data-level="3.2.2" data-path="api-.html"><a href="api-.html#section-11"><i class="fa fa-check"></i><b>3.2.2</b> 국내 종목 주가 다운로드</a></li>
<li class="chapter" data-level="3.2.3" data-path="api-.html"><a href="api-.html#fred--"><i class="fa fa-check"></i><b>3.2.3</b> FRED 데이터 다운로드</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="section-12.html"><a href="section-12.html"><i class="fa fa-check"></i><b>4</b> 크롤링 이해하기</a><ul>
<li class="chapter" data-level="4.1" data-path="section-12.html"><a href="section-12.html#get-post--"><i class="fa fa-check"></i><b>4.1</b> GET과 POST 방식 이해하기</a><ul>
<li class="chapter" data-level="4.1.1" data-path="section-12.html"><a href="section-12.html#get-"><i class="fa fa-check"></i><b>4.1.1</b> GET 방식</a></li>
<li class="chapter" data-level="4.1.2" data-path="section-12.html"><a href="section-12.html#post-"><i class="fa fa-check"></i><b>4.1.2</b> POST 방식</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="section-12.html"><a href="section-12.html#section-13"><i class="fa fa-check"></i><b>4.2</b> 크롤링 예제</a><ul>
<li class="chapter" data-level="4.2.1" data-path="section-12.html"><a href="section-12.html#section-14"><i class="fa fa-check"></i><b>4.2.1</b> 금융 속보 크롤링</a></li>
<li class="chapter" data-level="4.2.2" data-path="section-12.html"><a href="section-12.html#section-15"><i class="fa fa-check"></i><b>4.2.2</b> 기업공시채널에서 오늘의 공시 불러오기</a></li>
<li class="chapter" data-level="4.2.3" data-path="section-12.html"><a href="section-12.html#section-16"><i class="fa fa-check"></i><b>4.2.3</b> 네이버 금융에서 주식티커 크롤링</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="section-17.html"><a href="section-17.html"><i class="fa fa-check"></i><b>5</b> 금융 데이터 수집하기 (기본)</a><ul>
<li class="chapter" data-level="5.1" data-path="section-17.html"><a href="section-17.html#section-18"><i class="fa fa-check"></i><b>5.1</b> 한국거래소의 산업별 현황 및 개별지표 크롤링</a><ul>
<li class="chapter" data-level="5.1.1" data-path="section-17.html"><a href="section-17.html#section-19"><i class="fa fa-check"></i><b>5.1.1</b> 산업별 현황 크롤링</a></li>
<li class="chapter" data-level="5.1.2" data-path="section-17.html"><a href="section-17.html#section-20"><i class="fa fa-check"></i><b>5.1.2</b> 개별종목 지표 크롤링</a></li>
<li class="chapter" data-level="5.1.3" data-path="section-17.html"><a href="section-17.html#section-21"><i class="fa fa-check"></i><b>5.1.3</b> 데이터 정리하기</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="section-17.html"><a href="section-17.html#wics---"><i class="fa fa-check"></i><b>5.2</b> WICS 기준 섹터정보 크롤링</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="section-22.html"><a href="section-22.html"><i class="fa fa-check"></i><b>6</b> 금융 데이터 수집하기 (심화)</a><ul>
<li class="chapter" data-level="6.1" data-path="section-22.html"><a href="section-22.html#section-23"><i class="fa fa-check"></i><b>6.1</b> 수정주가 크롤링</a><ul>
<li class="chapter" data-level="6.1.1" data-path="section-22.html"><a href="section-22.html#section-24"><i class="fa fa-check"></i><b>6.1.1</b> 개별 종목 주가 크롤링</a></li>
<li class="chapter" data-level="6.1.2" data-path="section-22.html"><a href="section-22.html#section-25"><i class="fa fa-check"></i><b>6.1.2</b> 전 종목 주가 크롤링</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="section-22.html"><a href="section-22.html#section-26"><i class="fa fa-check"></i><b>6.2</b> 재무제표 및 가치지표 크롤링</a><ul>
<li class="chapter" data-level="6.2.1" data-path="section-22.html"><a href="section-22.html#section-27"><i class="fa fa-check"></i><b>6.2.1</b> 재무제표 다운로드</a></li>
<li class="chapter" data-level="6.2.2" data-path="section-22.html"><a href="section-22.html#section-28"><i class="fa fa-check"></i><b>6.2.2</b> 가치지표 계산하기</a></li>
<li class="chapter" data-level="6.2.3" data-path="section-22.html"><a href="section-22.html#section-29"><i class="fa fa-check"></i><b>6.2.3</b> 전 종목 재무제표 및 가치지표 다운로드</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="section-22.html"><a href="section-22.html#section-30"><i class="fa fa-check"></i><b>6.3</b> 야후 파이낸스 데이터 구하기</a><ul>
<li class="chapter" data-level="6.3.1" data-path="section-22.html"><a href="section-22.html#section-31"><i class="fa fa-check"></i><b>6.3.1</b> 재무제표 다운로드</a></li>
<li class="chapter" data-level="6.3.2" data-path="section-22.html"><a href="section-22.html#section-32"><i class="fa fa-check"></i><b>6.3.2</b> 가치지표 계산하기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="section-33.html"><a href="section-33.html"><i class="fa fa-check"></i><b>7</b> 데이터 정리하기</a><ul>
<li class="chapter" data-level="7.1" data-path="section-33.html"><a href="section-33.html#section-34"><i class="fa fa-check"></i><b>7.1</b> 주가 정리하기</a></li>
<li class="chapter" data-level="7.2" data-path="section-33.html"><a href="section-33.html#section-35"><i class="fa fa-check"></i><b>7.2</b> 재무제표 정리하기</a></li>
<li class="chapter" data-level="7.3" data-path="section-33.html"><a href="section-33.html#section-36"><i class="fa fa-check"></i><b>7.3</b> 가치지표 정리하기</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="section-37.html"><a href="section-37.html"><i class="fa fa-check"></i><b>8</b> 데이터 분석 및 시각화하기</a><ul>
<li class="chapter" data-level="8.1" data-path="section-37.html"><a href="section-37.html#section-38"><i class="fa fa-check"></i><b>8.1</b> 종목정보 데이터 분석</a><ul>
<li class="chapter" data-level="8.1.1" data-path="section-37.html"><a href="section-37.html#join--"><i class="fa fa-check"></i><b>8.1.1</b> <code>*_join</code>: 데이터 합치기</a></li>
<li class="chapter" data-level="8.1.2" data-path="section-37.html"><a href="section-37.html#glimpse---"><i class="fa fa-check"></i><b>8.1.2</b> <code>glimpse()</code>: 데이터 구조 확인하기</a></li>
<li class="chapter" data-level="8.1.3" data-path="section-37.html"><a href="section-37.html#rename---"><i class="fa fa-check"></i><b>8.1.3</b> <code>rename()</code>: 열 이름 바꾸기</a></li>
<li class="chapter" data-level="8.1.4" data-path="section-37.html"><a href="section-37.html#distinct---"><i class="fa fa-check"></i><b>8.1.4</b> distinct(): 고유한 값 확인</a></li>
<li class="chapter" data-level="8.1.5" data-path="section-37.html"><a href="section-37.html#select---"><i class="fa fa-check"></i><b>8.1.5</b> <code>select()</code>: 원하는 열만 선택</a></li>
<li class="chapter" data-level="8.1.6" data-path="section-37.html"><a href="section-37.html#mutate-----"><i class="fa fa-check"></i><b>8.1.6</b> <code>mutate()</code>: 열 생성 및 데이터 변경</a></li>
<li class="chapter" data-level="8.1.7" data-path="section-37.html"><a href="section-37.html#filter----"><i class="fa fa-check"></i><b>8.1.7</b> <code>filter()</code>: 조건을 충족하는 행 선택</a></li>
<li class="chapter" data-level="8.1.8" data-path="section-37.html"><a href="section-37.html#summarize---"><i class="fa fa-check"></i><b>8.1.8</b> <code>summarize()</code>: 요약 통계값 계산</a></li>
<li class="chapter" data-level="8.1.9" data-path="section-37.html"><a href="section-37.html#arrange--"><i class="fa fa-check"></i><b>8.1.9</b> <code>arrange()</code>: 데이터 정렬</a></li>
<li class="chapter" data-level="8.1.10" data-path="section-37.html"><a href="section-37.html#row_number--"><i class="fa fa-check"></i><b>8.1.10</b> <code>row_number()</code>: 순위 계산</a></li>
<li class="chapter" data-level="8.1.11" data-path="section-37.html"><a href="section-37.html#ntile--"><i class="fa fa-check"></i><b>8.1.11</b> <code>ntile()</code>: 분위수 계산</a></li>
<li class="chapter" data-level="8.1.12" data-path="section-37.html"><a href="section-37.html#group_by---"><i class="fa fa-check"></i><b>8.1.12</b> <code>group_by()</code>: 그룹별로 데이터를 묶음</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="section-37.html"><a href="section-37.html#section-39"><i class="fa fa-check"></i><b>8.2</b> 종목정보 시각화</a></li>
<li class="chapter" data-level="8.3" data-path="section-37.html"><a href="section-37.html#section-40"><i class="fa fa-check"></i><b>8.3</b> 주가 및 수익률 시각화</a><ul>
<li class="chapter" data-level="8.3.1" data-path="section-37.html"><a href="section-37.html#section-41"><i class="fa fa-check"></i><b>8.3.1</b> 주가 그래프 나타내기</a></li>
<li class="chapter" data-level="8.3.2" data-path="section-37.html"><a href="section-37.html#section-42"><i class="fa fa-check"></i><b>8.3.2</b> 인터랙티브 그래프 나타내기</a></li>
<li class="chapter" data-level="8.3.3" data-path="section-37.html"><a href="section-37.html#section-43"><i class="fa fa-check"></i><b>8.3.3</b> 연도별 수익률 나타내기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="section-44.html"><a href="section-44.html"><i class="fa fa-check"></i><b>9</b> 퀀트 전략을 이용한 종목선정 (기본)</a><ul>
<li class="chapter" data-level="9.1" data-path="section-44.html"><a href="section-44.html#section-45"><i class="fa fa-check"></i><b>9.1</b> 베타 이해하기</a><ul>
<li class="chapter" data-level="9.1.1" data-path="section-44.html"><a href="section-44.html#section-46"><i class="fa fa-check"></i><b>9.1.1</b> 베타 계산하기</a></li>
<li class="chapter" data-level="9.1.2" data-path="section-44.html"><a href="section-44.html#section-47"><i class="fa fa-check"></i><b>9.1.2</b> 베타 시각화</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="section-44.html"><a href="section-44.html#section-48"><i class="fa fa-check"></i><b>9.2</b> 저변동성 전략</a><ul>
<li class="chapter" data-level="9.2.1" data-path="section-44.html"><a href="section-44.html#section-49"><i class="fa fa-check"></i><b>9.2.1</b> 저변동성 포트폴리오 구하기: 일간 기준</a></li>
<li class="chapter" data-level="9.2.2" data-path="section-44.html"><a href="section-44.html#section-50"><i class="fa fa-check"></i><b>9.2.2</b> 저변동성 포트폴리오 구하기: 주간 기준</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="section-44.html"><a href="section-44.html#section-51"><i class="fa fa-check"></i><b>9.3</b> 모멘텀 전략</a><ul>
<li class="chapter" data-level="9.3.1" data-path="section-44.html"><a href="section-44.html#section-52"><i class="fa fa-check"></i><b>9.3.1</b> 모멘텀 포트폴리오 구하기: 12개월 모멘텀</a></li>
<li class="chapter" data-level="9.3.2" data-path="section-44.html"><a href="section-44.html#section-53"><i class="fa fa-check"></i><b>9.3.2</b> 모멘텀 포트폴리오 구하기: 위험조정 수익률</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="section-44.html"><a href="section-44.html#section-54"><i class="fa fa-check"></i><b>9.4</b> 밸류 전략</a><ul>
<li class="chapter" data-level="9.4.1" data-path="section-44.html"><a href="section-44.html#pbr"><i class="fa fa-check"></i><b>9.4.1</b> 밸류 포트폴리오 구하기: 저 PBR</a></li>
<li class="chapter" data-level="9.4.2" data-path="section-44.html"><a href="section-44.html#section-55"><i class="fa fa-check"></i><b>9.4.2</b> 각 지표를 결합하기</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="section-44.html"><a href="section-44.html#section-56"><i class="fa fa-check"></i><b>9.5</b> 퀄리티 전략</a><ul>
<li class="chapter" data-level="9.5.1" data-path="section-44.html"><a href="section-44.html#f-score"><i class="fa fa-check"></i><b>9.5.1</b> F-Score</a></li>
<li class="chapter" data-level="9.5.2" data-path="section-44.html"><a href="section-44.html#section-57"><i class="fa fa-check"></i><b>9.5.2</b> 각 지표를 결합하기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="section-58.html"><a href="section-58.html"><i class="fa fa-check"></i><b>10</b> 퀀트 전략을 이용한 종목선정 (심화)</a><ul>
<li class="chapter" data-level="10.1" data-path="section-58.html"><a href="section-58.html#section-59"><i class="fa fa-check"></i><b>10.1</b> 섹터 중립 포트폴리오</a></li>
<li class="chapter" data-level="10.2" data-path="section-58.html"><a href="section-58.html#section-60"><i class="fa fa-check"></i><b>10.2</b> 마법공식</a><ul>
<li class="chapter" data-level="10.2.1" data-path="section-58.html"><a href="section-58.html#section-61"><i class="fa fa-check"></i><b>10.2.1</b> 퀄리티와 밸류 간의 관계</a></li>
<li class="chapter" data-level="10.2.2" data-path="section-58.html"><a href="section-58.html#section-62"><i class="fa fa-check"></i><b>10.2.2</b> 마법공식 이해하기</a></li>
<li class="chapter" data-level="10.2.3" data-path="section-58.html"><a href="section-58.html#section-63"><i class="fa fa-check"></i><b>10.2.3</b> 마법공식 구성하기</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="section-58.html"><a href="section-58.html#section-64"><i class="fa fa-check"></i><b>10.3</b> 이상치 데이터 제거 및 팩터의 결합</a><ul>
<li class="chapter" data-level="10.3.1" data-path="section-58.html"><a href="section-58.html#trim---"><i class="fa fa-check"></i><b>10.3.1</b> 트림(Trim): 이상치 데이터 삭제</a></li>
<li class="chapter" data-level="10.3.2" data-path="section-58.html"><a href="section-58.html#winsorizing---"><i class="fa fa-check"></i><b>10.3.2</b> 윈저라이징(Winsorizing): 이상치 데이터 대체</a></li>
<li class="chapter" data-level="10.3.3" data-path="section-58.html"><a href="section-58.html#section-65"><i class="fa fa-check"></i><b>10.3.3</b> 팩터의 결합 방법</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="section-58.html"><a href="section-58.html#section-66"><i class="fa fa-check"></i><b>10.4</b> 멀티팩터 포트폴리오</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="section-67.html"><a href="section-67.html"><i class="fa fa-check"></i><b>11</b> 포트폴리오 구성</a><ul>
<li class="chapter" data-level="11.1" data-path="section-67.html"><a href="section-67.html#section-68"><i class="fa fa-check"></i><b>11.1</b> 최소분산 포트폴리오</a><ul>
<li class="chapter" data-level="11.1.1" data-path="section-67.html"><a href="section-67.html#slsqp---"><i class="fa fa-check"></i><b>11.1.1</b> <code>slsqp()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.2" data-path="section-67.html"><a href="section-67.html#solve.qp---"><i class="fa fa-check"></i><b>11.1.2</b> <code>solve.QP()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.3" data-path="section-67.html"><a href="section-67.html#optimalportfolio---"><i class="fa fa-check"></i><b>11.1.3</b> <code>optimalPortfolio()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.4" data-path="section-67.html"><a href="section-67.html#section-69"><i class="fa fa-check"></i><b>11.1.4</b> 결과값들의 비교</a></li>
<li class="chapter" data-level="11.1.5" data-path="section-67.html"><a href="section-67.html#section-70"><i class="fa fa-check"></i><b>11.1.5</b> 최소 및 최대 투자비중 제약조건</a></li>
<li class="chapter" data-level="11.1.6" data-path="section-67.html"><a href="section-67.html#section-71"><i class="fa fa-check"></i><b>11.1.6</b> 각 자산 별 제약조건의 추가</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="section-67.html"><a href="section-67.html#section-72"><i class="fa fa-check"></i><b>11.2</b> 최대분산효과 포트폴리오</a><ul>
<li class="chapter" data-level="11.2.1" data-path="section-67.html"><a href="section-67.html#solve.qp----1"><i class="fa fa-check"></i><b>11.2.1</b> <code>solve.QP()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.2.2" data-path="section-67.html"><a href="section-67.html#optimalportfolio----1"><i class="fa fa-check"></i><b>11.2.2</b> <code>optimalPortfolio()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.2.3" data-path="section-67.html"><a href="section-67.html#section-73"><i class="fa fa-check"></i><b>11.2.3</b> 최소 및 최대 투자비중 제약조건</a></li>
<li class="chapter" data-level="11.2.4" data-path="section-67.html"><a href="section-67.html#section-74"><i class="fa fa-check"></i><b>11.2.4</b> 각 자산 별 제약조건의 추가</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="section-67.html"><a href="section-67.html#section-75"><i class="fa fa-check"></i><b>11.3</b> 위험균형 포트폴리오</a><ul>
<li class="chapter" data-level="11.3.1" data-path="section-67.html"><a href="section-67.html#section-76"><i class="fa fa-check"></i><b>11.3.1</b> 전통적 자산배분, 주식 60%와 채권 40%</a></li>
<li class="chapter" data-level="11.3.2" data-path="section-67.html"><a href="section-67.html#rp---"><i class="fa fa-check"></i><b>11.3.2</b> <code>rp()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.3.3" data-path="section-67.html"><a href="section-67.html#section-77"><i class="fa fa-check"></i><b>11.3.3</b> 위험예산 포트폴리오</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="section-78.html"><a href="section-78.html"><i class="fa fa-check"></i><b>12</b> 포트폴리오 백테스트</a><ul>
<li class="chapter" data-level="12.1" data-path="section-78.html"><a href="section-78.html#return.portfolio-"><i class="fa fa-check"></i><b>12.1</b> <code>Return.Portfolio()</code> 함수</a><ul>
<li class="chapter" data-level="12.1.1" data-path="section-78.html"><a href="section-78.html#section-79"><i class="fa fa-check"></i><b>12.1.1</b> 인자목록 살펴보기</a></li>
<li class="chapter" data-level="12.1.2" data-path="section-78.html"><a href="section-78.html#section-80"><i class="fa fa-check"></i><b>12.1.2</b> 출력값 살펴보기</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="section-78.html"><a href="section-78.html#section-81"><i class="fa fa-check"></i><b>12.2</b> 전통적인 60대 40 포트폴리오 백테스트</a></li>
<li class="chapter" data-level="12.3" data-path="section-78.html"><a href="section-78.html#section-82"><i class="fa fa-check"></i><b>12.3</b> 시점 선택 전략 백테스트</a></li>
<li class="chapter" data-level="12.4" data-path="section-78.html"><a href="section-78.html#section-83"><i class="fa fa-check"></i><b>12.4</b> 동적 자산배분 백테스트</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="section-84.html"><a href="section-84.html"><i class="fa fa-check"></i><b>13</b> 성과 및 위험 평가</a><ul>
<li class="chapter" data-level="13.1" data-path="section-84.html"><a href="section-84.html#section-85"><i class="fa fa-check"></i><b>13.1</b> 결과 측정 지표</a><ul>
<li class="chapter" data-level="13.1.1" data-path="section-84.html"><a href="section-84.html#section-86"><i class="fa fa-check"></i><b>13.1.1</b> 수익률 및 변동성</a></li>
<li class="chapter" data-level="13.1.2" data-path="section-84.html"><a href="section-84.html#section-87"><i class="fa fa-check"></i><b>13.1.2</b> 낙폭과 최대낙폭</a></li>
<li class="chapter" data-level="13.1.3" data-path="section-84.html"><a href="section-84.html#section-88"><i class="fa fa-check"></i><b>13.1.3</b> 연도별 수익률</a></li>
<li class="chapter" data-level="13.1.4" data-path="section-84.html"><a href="section-84.html#section-89"><i class="fa fa-check"></i><b>13.1.4</b> 승률 및 롤링 윈도우 값</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="section-84.html"><a href="section-84.html#section-90"><i class="fa fa-check"></i><b>13.2</b> 팩터 회귀분석 및 테이블로 나타내기</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://henryquant.blogspot.com/" target="blank">Henry's Quantopia</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="section-84" class="section level1">
<h1><span class="header-section-number">Chapter 13</span> 성과 및 위험 평가</h1>
<p>원하는 전략의 백테스트를 통해 포트폴리오 수익률을 구했다면, 이를 바탕으로 각종 성과 및 위험을 평가해야합니다. 아무리 성과가 좋은 전략이라도 위험이 너무 크다면 투자를 하기 부담스럽습니다. 또한 전략의 수익률이 지속적으로 감소하는 추세라면 경쟁이 치열해져 더이상 작동하지 않는 전략일 가능성도 있습니다.</p>
<p>본 장에서는 포트폴리오의 예시로 퀄리티 팩터를 종합적으로 고려한 QMJ(Quality Minus Junk) 팩터<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a>의 데이터를 이용하겠습니다. QMJ 팩터란 우량성이 높은 종목들을 매수, 우량성이 낮은 종목들을 공매도한 전략을 지수의 형태로 나타낸 것입니다. 해당 팩터의 수익률을 통해 성과 및 위험을 평가해보고, 회귀분석을 통해 다른 팩터와의 관계도 살펴보도록 하겠습니다.</p>
<p>QMJ 팩터의 수익률은 논문 저자들의 회사인 AQR Capital Management의 Datasets<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a>에서 엑셀 파일을 다운로드 받은 후 가공할 수도 있습니다. 그러나 해당 작업을 매번 하는 것은 지나치게 번거로우므로, R 내에서 엑셀 파일을 다운로드 받은 후 가공하도록 하겠습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(readxl)
<span class="kw">library</span>(xts)
<span class="kw">library</span>(timetk)

url =<span class="st"> </span><span class="kw">paste0</span>(<span class="st">&#39;https://images.aqr.com/-/media/AQR/Documents/Insights/&#39;</span>,
             <span class="st">&#39;Data-Sets/Quality-Minus-Junk-Factors-Monthly.xlsx&#39;</span>)

tf =<span class="st"> </span><span class="kw">tempfile</span>(<span class="dt">fileext =</span> <span class="st">&#39;.xlsx&#39;</span>)
<span class="kw">download.file</span>(url, tf, <span class="dt">mode =</span> <span class="st">&#39;wb&#39;</span>)

<span class="kw">excel_sheets</span>(tf)</code></pre>
<pre><code>##  [1] &quot;QMJ Factors&quot;                   &quot;Definition&quot;                   
##  [3] &quot;Data Sources&quot;                  &quot;--&gt; Additional Global Factors&quot;
##  [5] &quot;MKT&quot;                           &quot;SMB&quot;                          
##  [7] &quot;HML FF&quot;                        &quot;HML Devil&quot;                    
##  [9] &quot;UMD&quot;                           &quot;ME(t-1)&quot;                      
## [11] &quot;RF&quot;                            &quot;Sources and Definitions&quot;      
## [13] &quot;Disclosures&quot;</code></pre>
<ol style="list-style-type: decimal">
<li>해당 데이터의 엑셀 url을 저장합니다.</li>
<li><code>tempfile()</code> 함수 내 .xlsx 인자를 입력함으로써, 임시로 엑셀 파일을 만들도록 합니다.</li>
<li><code>download.file()</code> 함수를 통해 url 파일을 tf 파일명에 저장하도록 하며, 엑셀의 경우 바이너리 파일이므로 wb 인자를 입력합니다.</li>
<li><code>readxl</code> 패키지의 <code>excel_sheets()</code> 함수를 통해 해당 엑셀의 시트명들을 확인합니다.</li>
</ol>
<p>우리가 필요한 데이터는 수익률을 계산할 QMJ Factors, 회귀분석에 필요한 MKT, SMB, HML Devil, UMD, 무위험 이자율인 RF 시트의 데이터 입니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">df_QMJ =<span class="st"> </span><span class="kw">read_xlsx</span>(tf, <span class="dt">sheet =</span> <span class="st">&#39;QMJ Factors&#39;</span>, <span class="dt">skip =</span> <span class="dv">18</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(DATE, Global)
df_MKT =<span class="st"> </span><span class="kw">read_xlsx</span>(tf, <span class="dt">sheet =</span> <span class="st">&#39;MKT&#39;</span>, <span class="dt">skip =</span> <span class="dv">18</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(DATE, Global)
df_SMB =<span class="st"> </span><span class="kw">read_xlsx</span>(tf, <span class="dt">sheet =</span> <span class="st">&#39;SMB&#39;</span>, <span class="dt">skip =</span> <span class="dv">18</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(DATE, Global)
df_HML_Devil =<span class="st"> </span><span class="kw">read_xlsx</span>(tf, <span class="dt">sheet =</span> <span class="st">&#39;HML Devil&#39;</span>, <span class="dt">skip =</span> <span class="dv">18</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(DATE, Global)
df_UMD =<span class="st"> </span><span class="kw">read_xlsx</span>(tf, <span class="dt">sheet =</span> <span class="st">&#39;UMD&#39;</span>, <span class="dt">skip =</span> <span class="dv">18</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(DATE, Global)
df_RF =<span class="st"> </span><span class="kw">read_xlsx</span>(tf, <span class="dt">sheet =</span> <span class="st">&#39;RF&#39;</span>, <span class="dt">skip =</span> <span class="dv">18</span>) </code></pre>
<p><code>readxl</code> 패키지의 <code>read_xlsx()</code> 함수를 통해 엑셀 데이터를 읽어올 수 있으며, 시트명을 정해줄 수도 있습니다. 또한 각 시트 내 18행 까지는 데이터를 설명하는 텍스트이므로, skip 인자를 통해 해당 부분은 읽어오지 않도록 합니다. 그 후 <code>select()</code> 함수를 통해 날짜에 해당하는 DATE와 Global 열만을 선택해 줍니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">df =<span class="st"> </span><span class="kw">Reduce</span>(<span class="cf">function</span>(x, y) <span class="kw">inner_join</span>(x, y, <span class="dt">by =</span> <span class="st">&#39;DATE&#39;</span>),
       <span class="kw">list</span>(df_QMJ, df_MKT, df_SMB, df_HML_Devil, df_UMD, df_RF)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">c</span>(<span class="st">&#39;DATE&#39;</span>,<span class="st">&#39;QMJ&#39;</span>, <span class="st">&#39;MKT&#39;</span>, <span class="st">&#39;SMB&#39;</span>, <span class="st">&#39;HML&#39;</span>, <span class="st">&#39;UMD&#39;</span>, <span class="st">&#39;RF&#39;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">DATE =</span> <span class="kw">as.Date</span>(DATE, <span class="st">&quot;%m/%d/%Y&quot;</span>),
         <span class="dt">R_excess =</span> QMJ <span class="op">-</span><span class="st"> </span>RF,
         <span class="dt">Mkt_excess =</span> MKT <span class="op">-</span><span class="st"> </span>RF) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">tk_xts</span>(<span class="dt">date_var =</span> DATE)</code></pre>
<ol style="list-style-type: decimal">
<li><code>inner_join()</code> 함수를 통해 DATE를 기준으로 데이터를 묶어주어야 합니다. 해당 함수는 한 번에 두개 테이블만을 선택할 수 있으므로, <code>Reduce()</code> 함수를 통해 모든 데이터에 <code>inner_join()</code> 함수를 적용합니다.</li>
<li><code>setNames()</code> 함수를 통해 열이름을 입력해줍니다.</li>
<li>각 팩터별 시작시점이 다르므로 <code>na.omit()</code> 함수를 통해 NA 데이터를 삭제해줍니다.</li>
<li><code>mutate()</code> 함수를 통해 데이터를 변형해줍니다. DATE 열의 경우
mm/dd/yy의 문자열 형식이므로 이를 날짜 형식으로 변경해줍니다. QMJ 팩터 수익률에서 무위험 수익률을 차감하여 초과수익률을 구해주며, 시장 수익률에서 무위험 수익률을 차감하여 시장위험 프리미엄을 계산해줍니다.</li>
<li><code>timetk</code> 패키지의 <code>tk_xts()</code> 함수를 이용해 티블 형태를 시계열 형태로 변경해주며, 인덱스는 DATE 열을 설정해줍니다. 형태 변경 후 해당 열은 자동으로 삭제됩니다.</li>
</ol>
<p>위 과정을 통해 구한 데이터를 바탕으로 성과 및 위험을 평가하도록 하겠습니다.</p>
<div id="section-85" class="section level2">
<h2><span class="header-section-number">13.1</span> 결과 측정 지표</h2>
<p>포트폴리오의 평가에서 가장 중요한 지표는 수익률과 위험입니다. 수익률은 누적수익률과 연율화 수익률, 연도별 수익률이 주요 지표이며, 위험의 경우 변동성과 낙폭이 주요 지표입니다.</p>
<p>이 외에도 승률, 롤링 윈도우 값 등 다양한 지표를 살펴보기도 합니다. 이러한 지표를 수식에 맞게 직접 계산할 수도 있지만, <code>PerformanceAnalytics</code> 패키지에서 제공하는 다양한 함수들을 이용해 편하게 계산할 수도 있습니다.</p>
<div id="section-86" class="section level3">
<h3><span class="header-section-number">13.1.1</span> 수익률 및 변동성</h3>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(PerformanceAnalytics)
<span class="kw">chart.CumReturns</span>(df<span class="op">$</span>QMJ)</code></pre>
<p><img src="13-evaluation_files/figure-html/unnamed-chunk-4-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>먼저 <code>chart.CumReturns()</code> 함수를 이용해 QMJ 팩터의 누적수익률을 그래프로 나타내봅니다. 1989-07-31 부터 2019-04-30까지 장기간동안 우상향 하는 모습을 보이고 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prod</span>((<span class="dv">1</span><span class="op">+</span>df<span class="op">$</span>QMJ)) <span class="op">-</span><span class="st"> </span><span class="dv">1</span> <span class="co"># 누적수익률</span></code></pre>
<pre><code>## [1] 4.049764</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(df<span class="op">$</span>QMJ) <span class="op">*</span><span class="st"> </span><span class="dv">12</span> <span class="co"># 연율화 수익률(산술)</span></code></pre>
<pre><code>## [1] 0.05703643</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">(<span class="kw">prod</span>((<span class="dv">1</span><span class="op">+</span>df<span class="op">$</span>QMJ))) <span class="op">^</span><span class="st"> </span>(<span class="dv">12</span> <span class="op">/</span><span class="st"> </span><span class="kw">nrow</span>(df<span class="op">$</span>QMJ)) <span class="op">-</span><span class="st"> </span><span class="dv">1</span> <span class="co"># 연율화 수익률(기하)</span></code></pre>
<pre><code>## [1] 0.05577976</code></pre>
<p>수익률 중 가장 많이보는 지표는 누적 수익률, 연율화 수익률(산술), 연율화 수익률(기하) 입니다. 각 수익률을 구하는 법은 다음과 같습니다.</p>
<ol style="list-style-type: decimal">
<li>누적 수익률: <span class="math inline">\((1+r_1) \times (1+r_2) \times \dots \ \times (1+r_n) = \{\prod_{i=1}^n(1+r_i)\}-1\)</span>,</li>
<li>연율화 수익률(산술): $ scale $</li>
<li>연율화 수익률(기하): <span class="math inline">\(\{\prod_{i=1}^n(1+r_i)\}^{scale / Days} - 1\)</span></li>
</ol>
<p>먼저 누적 수익률은 각 수익률에 1을 더한 값을 모두 곱한 후 1을 빼면 됩니다. 연율화 수익률(산술)의 경우 단순히 수익률의 평균을 구한 후, 연율화를 위한 조정값(scale)을 곱해주면 됩니다. 데이터가 일간일 경우 조정값은 252, 주간일 경우 52, 월간일 경우 12 입니다. 현재 데이터는 월간 기준이므로 조정값은 12가 됩니다.</p>
<p>마지막으로 연율화 수익률(기하)의 경우 각 수익률에 1을 더한 값의 곱을 구한 후, 연율화를 위해 승수를 곱한 후 1을 빼주면 되며, <span class="math inline">\(Days\)</span>는 시계열의 관측 기간입니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Return.cumulative</span>(df<span class="op">$</span>QMJ) <span class="co"># 누적수익률</span></code></pre>
<pre><code>##                        QMJ
## Cumulative Return 4.049764</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Return.annualized</span>(df<span class="op">$</span>QMJ, <span class="dt">geometric =</span> <span class="ot">FALSE</span>) <span class="co"># 연율화 수익률(산술)</span></code></pre>
<pre><code>##                          QMJ
## Annualized Return 0.05703643</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Return.annualized</span>(df<span class="op">$</span>QMJ) <span class="co"># 연율화 수익률(기하)</span></code></pre>
<pre><code>##                          QMJ
## Annualized Return 0.05577976</code></pre>
<p>수식에 맞게 값을 입력하여 계산할 수도 있지만, 함수를 이용할 경우 더욱 손쉽게 계산이 가능하며 실수를 할 가능성도 줄어들게 됩니다. 누적 수익률은 <code>Return.cumulative()</code> 함수를 통해, 연율화 수익률(산술)은 <code>Return.annualized()</code> 함수 내 geometric 인자를 FALSE로 선택해줌으로써, 연율화 수익률(기하)는 <code>Return.annualized()</code> 함수를 통해 계산이 가능합니다. 수식으로 계산한 값과 함수를 통해 계산한 값을 비교하면 동일함이 확인됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(df<span class="op">$</span>QMJ) <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">12</span>) <span class="co"># 연율화 변동성</span></code></pre>
<pre><code>## [1] 0.07285063</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">StdDev.annualized</span>(df<span class="op">$</span>QMJ) <span class="co"># 연율화 변동성</span></code></pre>
<pre><code>##                                      QMJ
## Annualized Standard Deviation 0.07285063</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">SharpeRatio.annualized</span>(df<span class="op">$</span>QMJ, <span class="dt">Rf =</span> df<span class="op">$</span>RF, <span class="dt">geometric =</span> <span class="ot">TRUE</span>)</code></pre>
<pre><code>##                                         QMJ
## Annualized Sharpe Ratio (Rf=2.8%) 0.3644028</code></pre>
<p>위험으로 가장 많이 사용되는 지표는 변동성입니다. 연율화 변동성의 경우 <code>sd()</code> 함수를 통해 변동성을 계산한 후 조정값을 곱해주어 계산이 됩니다. 그러나 <code>StdDev.annualized()</code> 함수를 사용하여 더욱 쉽게 계산할 수도 있습니다.</p>
<p>수익을 위험으로 나누어 위험 조정 수익률을 보는 지표가 샤프지수 입니다. 해당 지수는 <span class="math inline">\(\frac {R_i - R_f}{\sigma_i}\)</span>로 계산되며, 분자에는 포트폴리오 수익률에서 무위험 수익률을 차감한 값이, 분모에는 포트폴리오의 변동성이 오게 됩니다.</p>
<p><code>SharpeRatio.annualized()</code> 함수를 이용할 경우 포트폴리오 수익률에서 무위험 수익률을 차감한 값을 연율화로 변경한 후, 연율화 변동성으로 나누어 샤프지수를 계산합니다. geometric를 TRUE로 설정할 경우 기하평균 기준 연율화 수익률을, FALSE로 설정할 경우 산술평균 기준 연율화 수익률을 계산합니다.</p>
</div>
<div id="section-87" class="section level3">
<h3><span class="header-section-number">13.1.2</span> 낙폭과 최대낙폭</h3>
<p>먼저 낙폭(Drawdown)은 수익률이 하락한 후 반등하기 전까지 얼마나 하락하였는지를 나타냅니다. 최대낙폭(Maximum Drawdown)은 이러한 낙폭 중 가장 값이 큰 값으로써, 최고점에 최저점까지 얼마나 손실을 보는지를 나타냅니다. 투자를 함에 있어 수익률이 하락하는 것은 어쩔 수 없지만, 최대낙폭이 지나치게 큰 전략에 투자하는 것은 매우 위험한 선택이 될 수 있습니다.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-8"></span>
<img src="images/drawdown.png" alt="낙폭과 최대낙폭" width="50%" />
<p class="caption">
Figure 5.1: 낙폭과 최대낙폭
</p>
</div>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table.Drawdowns</span>(df<span class="op">$</span>QMJ)</code></pre>
<pre><code>##         From     Trough         To   Depth Length To Trough Recovery
## 1 2002-10-31 2004-01-31 2008-08-31 -0.2118     71        16       55
## 2 2009-03-31 2009-09-30 2012-05-31 -0.2012     39         7       32
## 3 1992-11-30 1993-08-31 1997-01-31 -0.1404     51        10       41
## 4 1998-10-31 1999-04-30 2000-05-31 -0.0868     20         7       13
## 5 2012-08-31 2013-01-31 2014-10-31 -0.0665     27         6       21</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">maxDrawdown</span>(df<span class="op">$</span>QMJ)</code></pre>
<pre><code>## [1] 0.2118214</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chart.Drawdown</span>(df<span class="op">$</span>QMJ)</code></pre>
<p><img src="13-evaluation_files/figure-html/unnamed-chunk-9-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>이러한 낙폭에 대한 지표들은 손으로 계산하기 번거롭지만, 패키지 내 함수를 사용한다면 매우 손쉽게 계산할 수 있습니다.</p>
<p>먼저 <code>table.Drawdowns()</code> 함수를 이용하면 역대 낙폭이 가장 심했던 순서대로 낙폭 정도, 하락 기간과 상승 기간, 원금 회복 기간 등을 테이블로 나타내줍니다. <code>maxDrawdown()</code> 함수는 포트폴리오의 최대 낙폭을 계산해주며, <code>chart.Drawdown()</code> 함수는 낙폭 만을 그래프로 그려줍니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">CalmarRatio</span>(df<span class="op">$</span>QMJ)</code></pre>
<pre><code>##                    QMJ
## Calmar Ratio 0.2633339</code></pre>
<p>위험 조정 수익률 중 사용되는 지표 중 칼마 지수도 있습니다. 해당 지표는 연율화 수익률을 최대낙폭으로 나눈 값으로써, 특히나 안정적인 절대 수익률을 추구하는 헤지펀드에서 많이 참조하는 지표입니다.</p>
</div>
<div id="section-88" class="section level3">
<h3><span class="header-section-number">13.1.3</span> 연도별 수익률</h3>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">apply.yearly</span>(df<span class="op">$</span>QMJ, Return.cumulative) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre>
<pre><code>##                    QMJ
## 1989-12-31  0.07555061
## 1990-12-31  0.22043182
## 1991-12-31  0.01087825
## 1992-12-31  0.02998013
## 1993-12-31 -0.09243790
## 1994-12-31  0.03969672</code></pre>
<p><code>apply.yearly()</code> 함수 내 계산함수를 <code>Return.cumulative</code>로 설정할 경우, 연도 별 수익률을 계산할 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lubridate)
<span class="kw">library</span>(tidyr)
<span class="kw">library</span>(ggplot2)

R.yr =<span class="st"> </span><span class="kw">apply.yearly</span>(df<span class="op">$</span>QMJ, Return.cumulative) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">fortify.zoo</span>() <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">Index =</span> <span class="kw">year</span>(Index)) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">gather</span>(key, value, <span class="op">-</span>Index) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">key =</span> <span class="kw">factor</span>(key, <span class="dt">levels =</span> <span class="kw">unique</span>(key)))

<span class="kw">ggplot</span>(R.yr, <span class="kw">aes</span>(<span class="dt">x =</span> Index, <span class="dt">y =</span> value, <span class="dt">fill =</span> key)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Yearly Return&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="ot">NULL</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand =</span> <span class="kw">c</span>(<span class="fl">0.03</span>, <span class="fl">0.03</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> R.yr<span class="op">$</span>Index,
                     <span class="dt">expand =</span> <span class="kw">c</span>(<span class="fl">0.01</span>, <span class="fl">0.01</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>,
                                  <span class="dt">size =</span> <span class="dv">12</span>),
        <span class="dt">legend.position =</span> <span class="st">&#39;bottom&#39;</span>,
        <span class="dt">legend.title =</span> <span class="kw">element_blank</span>(),
        <span class="dt">legend.text =</span> <span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">7</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>, <span class="dt">hjust =</span> <span class="dv">1</span>, <span class="dt">size =</span> <span class="dv">8</span>),
        <span class="dt">panel.grid.minor.x =</span> <span class="kw">element_blank</span>() ) <span class="op">+</span>
<span class="st">  </span><span class="kw">guides</span>(<span class="dt">fill =</span> <span class="kw">guide_legend</span>(<span class="dt">byrow =</span> <span class="ot">TRUE</span>)) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste</span>(<span class="kw">round</span>(value <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">&quot;%&quot;</span>),
                    <span class="dt">vjust =</span> <span class="kw">ifelse</span>(value <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span>, <span class="fl">-0.5</span>, <span class="fl">1.5</span>)),
                <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="dt">width =</span> <span class="dv">1</span>), <span class="dt">size =</span> <span class="dv">3</span>)</code></pre>
<p><img src="13-evaluation_files/figure-html/unnamed-chunk-12-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p><code>apply.yearly()</code> 함수를 통해 계산한 연도별 수익률에 <code>ggplot()</code> 함수를 응용할 경우 막대그래프로 나타낼 수도 있으며, 시각화를 통해 포트폴리오의 수익률 추이가 더욱 쉽게 확인됩니다.</p>
</div>
<div id="section-89" class="section level3">
<h3><span class="header-section-number">13.1.4</span> 승률 및 롤링 윈도우 값</h3>
<p>승률이란 포트폴리오가 벤치마크를 대비 높은 성과를 기록한 비율을 의미하며, <span class="math inline">\(\frac {(포트폴리오\,수익률 &gt; 벤치마크)\,일수}{전체\,기간}\)</span>을 통해 계산됩니다. 벤치마크가 S&amp;P 500 지수, KOSPI 200 지수처럼 구체적으로 존재하는 경우도 있지만, 절대수익을 추구하는 경우에는 이러한 벤치마크가 0 혹은 무위험 수익률이 됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">UpsideFrequency</span>(df<span class="op">$</span>QMJ, <span class="dt">MAR =</span> <span class="dv">0</span>)</code></pre>
<pre><code>## [1] 0.5949721</code></pre>
<p><code>UpsideFrequency()</code> 함수는 벤치마크 대비 승률을 계산해줍니다. MAR 인자는 0이 기본값으로 설정되어 있으며, 원하는 벤치마크가 있을시 이를 입력해주면 됩니다. QMJ 팩터는 월간 기준 수익률이 플러스를 기록했던 비율이 59.5% 입니다.</p>
<p>위에서 구한 각종 지표들은 투자자가 시작부터 현재까지 투자를 하였다는 전제하에 계산됩니다. 그러나 투자를 시작하는 시점은 사람마다 다르기에, 무작위 시점에 투자했을 시 향후 n개월 후 승률 혹은 연율화 수익률 등을 계산할 필요도 있습니다. 이러한 기법을 롤링 윈도우라 합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">roll_<span class="dv">12</span> =<span class="st"> </span>df<span class="op">$</span>QMJ <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">apply.monthly</span>(., Return.cumulative) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rollapply</span>(., <span class="dv">12</span>, Return.annualized) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">UpsideFrequency</span>()

roll_<span class="dv">24</span> =<span class="st"> </span>df<span class="op">$</span>QMJ <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">apply.monthly</span>(., Return.cumulative) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rollapply</span>(., <span class="dv">24</span>, Return.annualized) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">UpsideFrequency</span>()

roll_<span class="dv">36</span> =<span class="st"> </span>df<span class="op">$</span>QMJ <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">apply.monthly</span>(., Return.cumulative) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rollapply</span>(., <span class="dv">36</span>, Return.annualized) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">UpsideFrequency</span>()

roll_win =<span class="st"> </span><span class="kw">cbind</span>(roll_<span class="dv">12</span>, roll_<span class="dv">24</span>, roll_<span class="dv">36</span>)
<span class="kw">print</span>(roll_win)</code></pre>
<pre><code>##        roll_12   roll_24   roll_36
## [1,] 0.7636888 0.7910448 0.8668731</code></pre>
<p>롤링 윈도우 승률은 무작위 시점에 투자했을 시 미래 n기간 동안의 연율화 수익률을 구하고, 해당 값이 벤치마크 대비 수익이 높았던 비율을 계산합니다. 만일 12개월 롤링 윈도우 승률이 100% 라면, 어떠한 시점에 투자하여도 12개월 후에는 언제나 벤치마크를 이겼음을 의미합니다. 반면 아무리 연율화 수익률이 높은 전략도 이러한 롤링 윈도우 승률이 지나치게 낮다면, 단순히 한번의 운으로 인해 수익률이 높아보이는 것처럼 보일 수 있습니다.</p>
<p>함수를 이용해 해당 값을 구하는 과정은 다음과 같습니다.</p>
<ol style="list-style-type: decimal">
<li><code>apply.*()</code> 함수를 이용해 원하는 기간 수익률로 변경하며, 위 예제에서는 월간 수익률로 변경했습니다.</li>
<li><code>rollapply()</code> 함수를 통해 원하는 기간의 롤링 윈도우 통계값을 구해줍니다. 각각 12개월, 24개월, 36개월 기간에 대해 <code>Return.annualized()</code> 함수를 통해 연율화 수익률을 계산해줍니다.</li>
<li>계산에 필요한 n기간 동안은 수익률이 없으므로 <code>na.omit()</code>을 통해 삭제해줍니다.</li>
<li><code>UpsideFrequency()</code> 함수를 통해 승률을 계산해 줍니다.</li>
</ol>
<p>해당 과정을 통해 계산된 12개월, 24개월, 36개월 롤링 승률은 각각 76.37%, 79.1%, 86.69%이며, 투자 기간이 길어질수록 승률이 높아짐이 확인됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">df<span class="op">$</span>QMJ <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">apply.monthly</span>(., Return.cumulative) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rollapply</span>(., <span class="dv">12</span>, Return.annualized) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">fortify.zoo</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Index, <span class="dt">y =</span> QMJ)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</code></pre>
<p><img src="13-evaluation_files/figure-html/unnamed-chunk-15-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>롤링 윈도우 연율화 수익률 역시 매우 중요한 지표입니다. 해당 값이 지속적으로 하락할 경우, 전략이 더이상 동작하지 않는 것인지 혹은 가장 험난한 시기를 지났기에 인내심을 갖고 기다려야 할지 판단해야 합니다.</p>
</div>
</div>
<div id="section-90" class="section level2">
<h2><span class="header-section-number">13.2</span> 팩터 회귀분석 및 테이블로 나타내기</h2>
<p>포트폴리오 수익률에 대한 성과 평가만큼 중요한 것이, 수익률이 어디에서 발생했는가에 대한 요인을 분석하는 것입니다. 베타를 통한 개별 주식과 주식시장과의 관계를 시작으로, 수익률을 설명하기 위한 여러 모형들이 개발되고 발표되었습니다. 그 중 일반적으로 많이 사용되는 모형은 기존의 CAPM에 사이즈 팩터(SMB), 밸류 팩터(HML)를 추가한 파마-프렌치의 쓰리팩터 모형, 그리고 모멘텀 팩터(UMD)를 더 추가한 카하트의 포팩터 모형입니다.</p>
<p>QMJ 팩터를 위 4개 팩터에 회귀분석한 결과를 토대로, 퀄리티 팩터의 수익률에 대한 요인 분석을 해보도록 하겠습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">reg =<span class="st"> </span><span class="kw">lm</span>(R_excess <span class="op">~</span><span class="st"> </span>Mkt_excess <span class="op">+</span><span class="st"> </span>SMB <span class="op">+</span><span class="st"> </span>HML <span class="op">+</span><span class="st"> </span>UMD, <span class="dt">data =</span> df)
<span class="kw">summary</span>(reg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = R_excess ~ Mkt_excess + SMB + HML + UMD, data = df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.037572 -0.007304 -0.000242  0.007702  0.060886 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.0029406  0.0007164   4.104 5.04e-05 ***
## Mkt_excess  -0.2774942  0.0166597 -16.657  &lt; 2e-16 ***
## SMB         -0.3641118  0.0363016 -10.030  &lt; 2e-16 ***
## HML         -0.1296454  0.0341438  -3.797 0.000172 ***
## UMD          0.0659894  0.0267169   2.470 0.013985 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01261 on 353 degrees of freedom
## Multiple R-squared:  0.6428, Adjusted R-squared:  0.6388 
## F-statistic: 158.8 on 4 and 353 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>먼저 우리가 구한 데이터를 통해 다음과 같은 회귀분석을 실시합니다. 즉 QMJ 팩터의 초과수익률을 시장위험 프리미엄, 사이즈 팩터, 밸류 팩터, 모멘텀 팩터에 회귀분석 합니다.</p>
<p><span class="math display">\[QMJ - R_f= \beta_m \times \ [R_m - R_f] + \beta_{SMB} \times R_{SMB} + \beta_{HML} \times R_{HML} + \beta_{UMD} \times R_{UMD}\]</span>
<code>lm()</code> 함수 내에서 R_excess는 <span class="math inline">\(QMJ - R_f\)</span>와 동일하며, Mkt_excess는 <span class="math inline">\(R_m - R_f\)</span>와 동일합니다. 베타의 절대값이 크다는 의미는 QMJ 팩터의 수익률이 해당 팩터와의 관계가 높다는 의미이며, 양수일 경우에는 양의 관계가, 음수일 경우에는 음의 관계가 높다는 의미입니다. 또한 t value 혹은 P value를 통해 관계가 얼마나 유의한지도 확인할 수 있습니다.</p>
<ol style="list-style-type: decimal">
<li>시장 베타에 해당하는 <span class="math inline">\(\beta_m\)</span>은 -0.277로 음수값을 보이며, 우량주의 경우 베타가 낮다고 볼 수 있습니다. 또한 t-value가 -16.657로 충분히 유의합니다.</li>
<li>사이즈 베타에 해당하는 <span class="math inline">\(\beta_{SMB}\)</span>는 -0.364로써 역시나 음수값을 보입니다. 즉 우량주는 주로 대형주, 비우량주는 주로 소형주일 가능성이 있습니다. t-value 역시 -10.03로 충분히 유의합니다.</li>
<li>밸류 베타에 해당하는 <span class="math inline">\(\beta_{HML}\)</span>은 -0.13로써 이 역시 음수값을 보입니다. 즉 퀄리티와 밸류 간의 관계에서 살펴본것 처럼, 우량주는 주로 밸류가 높은 경향이 있습니다. t-value 역시 -3.797로 유의합니다.</li>
<li>모멘텀 베타에 해당하는 <span class="math inline">\(\beta_{UMD}\)</span>는 0.066로 양의 관계가 있습니다. 즉 우량주는 주로 과거 수익률이 높았던 주식, 비우량주는 과거 수익률이 낮았던 주식인 경향이 있습니다. t-value는 2.47로 유의하다고 볼 수 있습니다.</li>
<li>이러한 설명변수를 제외하고도 월간 초과수익률에 해당하는 계수값이 0.003이며, t-value는 4.104로 유의합니다. 즉, 퀄리티 팩터는 기존의 여러 팩터들로 설명되지 않는 새로운 팩터라고도 볼 수 있습니다.</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(broom)
<span class="kw">tidy</span>(reg)</code></pre>
<pre><code>## # A tibble: 5 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)  0.00294  0.000716      4.10 5.04e- 5
## 2 Mkt_excess  -0.277    0.0167      -16.7  2.23e-46
## 3 SMB         -0.364    0.0363      -10.0  5.36e-21
## 4 HML         -0.130    0.0341       -3.80 1.72e- 4
## 5 UMD          0.0660   0.0267        2.47 1.40e- 2</code></pre>
<p><code>broom()</code> 패키지의 <code>tidy()</code> 함수를 사용하면 분석 결과 중 계수에 해당하는 값만을 요약해서 볼 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(stargazer)
<span class="kw">stargazer</span>(reg, <span class="dt">type =</span> <span class="st">&#39;text&#39;</span>, <span class="dt">out =</span> <span class="st">&#39;data/reg_table.html&#39;</span>)</code></pre>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                              R_excess          
## -----------------------------------------------
## Mkt_excess                   -0.277***         
##                               (0.017)          
##                                                
## SMB                          -0.364***         
##                               (0.036)          
##                                                
## HML                          -0.130***         
##                               (0.034)          
##                                                
## UMD                           0.066**          
##                               (0.027)          
##                                                
## Constant                     0.003***          
##                               (0.001)          
##                                                
## -----------------------------------------------
## Observations                    358            
## R2                             0.643           
## Adjusted R2                    0.639           
## Residual Std. Error      0.013 (df = 353)      
## F Statistic          158.811*** (df = 4; 353)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p><code>stargazer</code> 패키지를 사용하면, 회귀분석 결과를 논문에서 많이 사용되는 테이블 형식으로 손쉽게 출력과 저장을 할 수 있습니다.테이블이 출력과 함께 data 폴더 내에 <strong>reg_table.html</strong> 이름으로 html 파일 역시 저장이 됩니다.</p>

</div>
</div>































<div class="footnotes">
<hr />
<ol start="25">
<li id="fn25"><p>Asness, C. S., Frazzini, A., &amp; Pedersen, L. H. (2019). Quality minus junk. Review of Accounting Studies, 24(1), 34-112.<a href="section-84.html#fnref25" class="footnote-back">↩</a></p></li>
<li id="fn26"><p><a href="https://www.aqr.com/Insights/Datasets/Quality-Minus-Junk-Factors-Monthly" class="uri">https://www.aqr.com/Insights/Datasets/Quality-Minus-Junk-Factors-Monthly</a><a href="section-84.html#fnref26" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="section-78.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
