<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 포트폴리오 구성 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기</title>
  <meta name="description" content="Chapter 11 포트폴리오 구성 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 포트폴리오 구성 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 포트폴리오 구성 | 퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기" />
  
  
  

<meta name="author" content="이현열" />


<meta name="date" content="2019-06-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="section-58.html">
<link rel="next" href="section-78.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<script src="libs/proj4js-2.3.15/proj4.js"></script>
<link href="libs/highcharts-7.0.1/css/motion.css" rel="stylesheet" />
<link href="libs/highcharts-7.0.1/css/htmlwdgtgrid.css" rel="stylesheet" />
<script src="libs/highcharts-7.0.1/highcharts.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-3d.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-more.js"></script>
<script src="libs/highcharts-7.0.1/modules/stock.js"></script>
<script src="libs/highcharts-7.0.1/modules/map.js"></script>
<script src="libs/highcharts-7.0.1/modules/annotations.js"></script>
<script src="libs/highcharts-7.0.1/modules/boost.js"></script>
<script src="libs/highcharts-7.0.1/modules/data.js"></script>
<script src="libs/highcharts-7.0.1/modules/drag-panes.js"></script>
<script src="libs/highcharts-7.0.1/modules/drilldown.js"></script>
<script src="libs/highcharts-7.0.1/modules/item-series.js"></script>
<script src="libs/highcharts-7.0.1/modules/offline-exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/overlapping-datalabels.js"></script>
<script src="libs/highcharts-7.0.1/modules/exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/export-data.js"></script>
<script src="libs/highcharts-7.0.1/modules/funnel.js"></script>
<script src="libs/highcharts-7.0.1/modules/heatmap.js"></script>
<script src="libs/highcharts-7.0.1/modules/treemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/sankey.js"></script>
<script src="libs/highcharts-7.0.1/modules/solid-gauge.js"></script>
<script src="libs/highcharts-7.0.1/modules/streamgraph.js"></script>
<script src="libs/highcharts-7.0.1/modules/sunburst.js"></script>
<script src="libs/highcharts-7.0.1/modules/vector.js"></script>
<script src="libs/highcharts-7.0.1/modules/wordcloud.js"></script>
<script src="libs/highcharts-7.0.1/modules/xrange.js"></script>
<script src="libs/highcharts-7.0.1/modules/tilemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/venn.js"></script>
<script src="libs/highcharts-7.0.1/modules/gantt.js"></script>
<script src="libs/highcharts-7.0.1/modules/timeline.js"></script>
<script src="libs/highcharts-7.0.1/modules/parallel-coordinates.js"></script>
<script src="libs/highcharts-7.0.1/plugins/grouped-categories.js"></script>
<script src="libs/highcharts-7.0.1/plugins/motion.js"></script>
<script src="libs/highcharts-7.0.1/plugins/multicolor_series.js"></script>
<script src="libs/highcharts-7.0.1/custom/reset.js"></script>
<script src="libs/highcharts-7.0.1/custom/symbols-extra.js"></script>
<script src="libs/highcharts-7.0.1/custom/text-symbols.js"></script>
<script src="libs/highchart-binding-0.7.0/highchart.js"></script>
<script src="libs/plotly-binding-4.9.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.46.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.46.1/plotly-latest.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">퀀트 투자 쿡북</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>여는 글</a></li>
<li class="chapter" data-level="1" data-path="section-1.html"><a href="section-1.html"><i class="fa fa-check"></i><b>1</b> 퀀트 투자의 심장: 데이터와 프로그래밍</a><ul>
<li class="chapter" data-level="1.1" data-path="section-1.html"><a href="section-1.html#section-2"><i class="fa fa-check"></i><b>1.1</b> 데이터 구하기</a></li>
<li class="chapter" data-level="1.2" data-path="section-1.html"><a href="section-1.html#section-3"><i class="fa fa-check"></i><b>1.2</b> 퀀트 투자와 프로그래밍</a></li>
<li class="chapter" data-level="1.3" data-path="section-1.html"><a href="section-1.html#r-"><i class="fa fa-check"></i><b>1.3</b> R 프로그램</a></li>
<li class="chapter" data-level="1.4" data-path="section-1.html"><a href="section-1.html#r--1"><i class="fa fa-check"></i><b>1.4</b> 퀀트 투자에 유용한 R 패키지</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="section-4.html"><a href="section-4.html"><i class="fa fa-check"></i><b>2</b> 크롤링을 위한 기본 지식</a><ul>
<li class="chapter" data-level="2.1" data-path="section-4.html"><a href="section-4.html#r-utf-8-"><i class="fa fa-check"></i><b>2.1</b> 인코딩의 이해와 R에서 UTF-8 설정하기</a><ul>
<li class="chapter" data-level="2.1.1" data-path="section-4.html"><a href="section-4.html#ascii"><i class="fa fa-check"></i><b>2.1.1</b> 인간과 컴퓨터 간 번역의 시작, ASCII</a></li>
<li class="chapter" data-level="2.1.2" data-path="section-4.html"><a href="section-4.html#section-5"><i class="fa fa-check"></i><b>2.1.2</b> 한글 인코딩의 종류</a></li>
<li class="chapter" data-level="2.1.3" data-path="section-4.html"><a href="section-4.html#r-utf-8--1"><i class="fa fa-check"></i><b>2.1.3</b> R에서 UTF-8 설정하기</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="section-4.html"><a href="section-4.html#section-6"><i class="fa fa-check"></i><b>2.2</b> 웹의 동작 방식</a><ul>
<li class="chapter" data-level="2.2.1" data-path="section-4.html"><a href="section-4.html#http"><i class="fa fa-check"></i><b>2.2.1</b> HTTP</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="section-4.html"><a href="section-4.html#html-css-"><i class="fa fa-check"></i><b>2.3</b> HTML과 CSS 이해하기</a><ul>
<li class="chapter" data-level="2.3.1" data-path="section-4.html"><a href="section-4.html#html--"><i class="fa fa-check"></i><b>2.3.1</b> HTML 기본 구조</a></li>
<li class="chapter" data-level="2.3.2" data-path="section-4.html"><a href="section-4.html#section-7"><i class="fa fa-check"></i><b>2.3.2</b> 태그와 속성</a></li>
<li class="chapter" data-level="2.3.3" data-path="section-4.html"><a href="section-4.html#h--p-"><i class="fa fa-check"></i><b>2.3.3</b> h 태그와 p 태그</a></li>
<li class="chapter" data-level="2.3.4" data-path="section-4.html"><a href="section-4.html#ul-ol-"><i class="fa fa-check"></i><b>2.3.4</b> 리스트: ul과 ol 태그</a></li>
<li class="chapter" data-level="2.3.5" data-path="section-4.html"><a href="section-4.html#table-"><i class="fa fa-check"></i><b>2.3.5</b> table 태그</a></li>
<li class="chapter" data-level="2.3.6" data-path="section-4.html"><a href="section-4.html#a-src--"><i class="fa fa-check"></i><b>2.3.6</b> a, src 태그와 속성</a></li>
<li class="chapter" data-level="2.3.7" data-path="section-4.html"><a href="section-4.html#div-"><i class="fa fa-check"></i><b>2.3.7</b> div 태그</a></li>
<li class="chapter" data-level="2.3.8" data-path="section-4.html"><a href="section-4.html#css"><i class="fa fa-check"></i><b>2.3.8</b> CSS</a></li>
<li class="chapter" data-level="2.3.9" data-path="section-4.html"><a href="section-4.html#class-id"><i class="fa fa-check"></i><b>2.3.9</b> class와 id</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="section-4.html"><a href="section-4.html#section-8"><i class="fa fa-check"></i><b>2.4</b> 파이프 오퍼레이터 (<code>%&gt;%</code>)</a></li>
<li class="chapter" data-level="2.5" data-path="section-4.html"><a href="section-4.html#section-9"><i class="fa fa-check"></i><b>2.5</b> 오류에 대한 예외처리</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="api-.html"><a href="api-.html"><i class="fa fa-check"></i><b>3</b> API를 이용한 데이터 수집</a><ul>
<li class="chapter" data-level="3.1" data-path="api-.html"><a href="api-.html#api--quandl--"><i class="fa fa-check"></i><b>3.1</b> API를 이용한 Quandl 데이터 다운로드</a></li>
<li class="chapter" data-level="3.2" data-path="api-.html"><a href="api-.html#getsymbols---api-"><i class="fa fa-check"></i><b>3.2</b> <code>getSymbols()</code> 함수를 이용한 API 다운로드</a><ul>
<li class="chapter" data-level="3.2.1" data-path="api-.html"><a href="api-.html#section-10"><i class="fa fa-check"></i><b>3.2.1</b> 주가 다운로드</a></li>
<li class="chapter" data-level="3.2.2" data-path="api-.html"><a href="api-.html#section-11"><i class="fa fa-check"></i><b>3.2.2</b> 국내 종목 주가 다운로드</a></li>
<li class="chapter" data-level="3.2.3" data-path="api-.html"><a href="api-.html#fred--"><i class="fa fa-check"></i><b>3.2.3</b> FRED 데이터 다운로드</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="section-12.html"><a href="section-12.html"><i class="fa fa-check"></i><b>4</b> 크롤링 이해하기</a><ul>
<li class="chapter" data-level="4.1" data-path="section-12.html"><a href="section-12.html#get-post--"><i class="fa fa-check"></i><b>4.1</b> GET과 POST 방식 이해하기</a><ul>
<li class="chapter" data-level="4.1.1" data-path="section-12.html"><a href="section-12.html#get-"><i class="fa fa-check"></i><b>4.1.1</b> GET 방식</a></li>
<li class="chapter" data-level="4.1.2" data-path="section-12.html"><a href="section-12.html#post-"><i class="fa fa-check"></i><b>4.1.2</b> POST 방식</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="section-12.html"><a href="section-12.html#section-13"><i class="fa fa-check"></i><b>4.2</b> 크롤링 예제</a><ul>
<li class="chapter" data-level="4.2.1" data-path="section-12.html"><a href="section-12.html#section-14"><i class="fa fa-check"></i><b>4.2.1</b> 금융 속보 크롤링</a></li>
<li class="chapter" data-level="4.2.2" data-path="section-12.html"><a href="section-12.html#section-15"><i class="fa fa-check"></i><b>4.2.2</b> 기업공시채널에서 오늘의 공시 불러오기</a></li>
<li class="chapter" data-level="4.2.3" data-path="section-12.html"><a href="section-12.html#section-16"><i class="fa fa-check"></i><b>4.2.3</b> 네이버 금융에서 주식티커 크롤링</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="section-17.html"><a href="section-17.html"><i class="fa fa-check"></i><b>5</b> 금융 데이터 수집하기 (기본)</a><ul>
<li class="chapter" data-level="5.1" data-path="section-17.html"><a href="section-17.html#section-18"><i class="fa fa-check"></i><b>5.1</b> 한국거래소의 산업별 현황 및 개별지표 크롤링</a><ul>
<li class="chapter" data-level="5.1.1" data-path="section-17.html"><a href="section-17.html#section-19"><i class="fa fa-check"></i><b>5.1.1</b> 산업별 현황 크롤링</a></li>
<li class="chapter" data-level="5.1.2" data-path="section-17.html"><a href="section-17.html#section-20"><i class="fa fa-check"></i><b>5.1.2</b> 개별종목 지표 크롤링</a></li>
<li class="chapter" data-level="5.1.3" data-path="section-17.html"><a href="section-17.html#section-21"><i class="fa fa-check"></i><b>5.1.3</b> 데이터 정리하기</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="section-17.html"><a href="section-17.html#wics---"><i class="fa fa-check"></i><b>5.2</b> WICS 기준 섹터정보 크롤링</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="section-22.html"><a href="section-22.html"><i class="fa fa-check"></i><b>6</b> 금융 데이터 수집하기 (심화)</a><ul>
<li class="chapter" data-level="6.1" data-path="section-22.html"><a href="section-22.html#section-23"><i class="fa fa-check"></i><b>6.1</b> 수정주가 크롤링</a><ul>
<li class="chapter" data-level="6.1.1" data-path="section-22.html"><a href="section-22.html#section-24"><i class="fa fa-check"></i><b>6.1.1</b> 개별 종목 주가 크롤링</a></li>
<li class="chapter" data-level="6.1.2" data-path="section-22.html"><a href="section-22.html#section-25"><i class="fa fa-check"></i><b>6.1.2</b> 전 종목 주가 크롤링</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="section-22.html"><a href="section-22.html#section-26"><i class="fa fa-check"></i><b>6.2</b> 재무제표 및 가치지표 크롤링</a><ul>
<li class="chapter" data-level="6.2.1" data-path="section-22.html"><a href="section-22.html#section-27"><i class="fa fa-check"></i><b>6.2.1</b> 재무제표 다운로드</a></li>
<li class="chapter" data-level="6.2.2" data-path="section-22.html"><a href="section-22.html#section-28"><i class="fa fa-check"></i><b>6.2.2</b> 가치지표 계산하기</a></li>
<li class="chapter" data-level="6.2.3" data-path="section-22.html"><a href="section-22.html#section-29"><i class="fa fa-check"></i><b>6.2.3</b> 전 종목 재무제표 및 가치지표 다운로드</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="section-22.html"><a href="section-22.html#section-30"><i class="fa fa-check"></i><b>6.3</b> 야후 파이낸스 데이터 구하기</a><ul>
<li class="chapter" data-level="6.3.1" data-path="section-22.html"><a href="section-22.html#section-31"><i class="fa fa-check"></i><b>6.3.1</b> 재무제표 다운로드</a></li>
<li class="chapter" data-level="6.3.2" data-path="section-22.html"><a href="section-22.html#section-32"><i class="fa fa-check"></i><b>6.3.2</b> 가치지표 계산하기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="section-33.html"><a href="section-33.html"><i class="fa fa-check"></i><b>7</b> 데이터 정리하기</a><ul>
<li class="chapter" data-level="7.1" data-path="section-33.html"><a href="section-33.html#section-34"><i class="fa fa-check"></i><b>7.1</b> 주가 정리하기</a></li>
<li class="chapter" data-level="7.2" data-path="section-33.html"><a href="section-33.html#section-35"><i class="fa fa-check"></i><b>7.2</b> 재무제표 정리하기</a></li>
<li class="chapter" data-level="7.3" data-path="section-33.html"><a href="section-33.html#section-36"><i class="fa fa-check"></i><b>7.3</b> 가치지표 정리하기</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="section-37.html"><a href="section-37.html"><i class="fa fa-check"></i><b>8</b> 데이터 분석 및 시각화하기</a><ul>
<li class="chapter" data-level="8.1" data-path="section-37.html"><a href="section-37.html#section-38"><i class="fa fa-check"></i><b>8.1</b> 종목정보 데이터 분석</a><ul>
<li class="chapter" data-level="8.1.1" data-path="section-37.html"><a href="section-37.html#join--"><i class="fa fa-check"></i><b>8.1.1</b> <code>*_join</code>: 데이터 합치기</a></li>
<li class="chapter" data-level="8.1.2" data-path="section-37.html"><a href="section-37.html#glimpse---"><i class="fa fa-check"></i><b>8.1.2</b> <code>glimpse()</code>: 데이터 구조 확인하기</a></li>
<li class="chapter" data-level="8.1.3" data-path="section-37.html"><a href="section-37.html#rename---"><i class="fa fa-check"></i><b>8.1.3</b> <code>rename()</code>: 열 이름 바꾸기</a></li>
<li class="chapter" data-level="8.1.4" data-path="section-37.html"><a href="section-37.html#distinct---"><i class="fa fa-check"></i><b>8.1.4</b> distinct(): 고유한 값 확인</a></li>
<li class="chapter" data-level="8.1.5" data-path="section-37.html"><a href="section-37.html#select---"><i class="fa fa-check"></i><b>8.1.5</b> <code>select()</code>: 원하는 열만 선택</a></li>
<li class="chapter" data-level="8.1.6" data-path="section-37.html"><a href="section-37.html#mutate-----"><i class="fa fa-check"></i><b>8.1.6</b> <code>mutate()</code>: 열 생성 및 데이터 변경</a></li>
<li class="chapter" data-level="8.1.7" data-path="section-37.html"><a href="section-37.html#filter----"><i class="fa fa-check"></i><b>8.1.7</b> <code>filter()</code>: 조건을 충족하는 행 선택</a></li>
<li class="chapter" data-level="8.1.8" data-path="section-37.html"><a href="section-37.html#summarize---"><i class="fa fa-check"></i><b>8.1.8</b> <code>summarize()</code>: 요약 통계값 계산</a></li>
<li class="chapter" data-level="8.1.9" data-path="section-37.html"><a href="section-37.html#arrange--"><i class="fa fa-check"></i><b>8.1.9</b> <code>arrange()</code>: 데이터 정렬</a></li>
<li class="chapter" data-level="8.1.10" data-path="section-37.html"><a href="section-37.html#row_number--"><i class="fa fa-check"></i><b>8.1.10</b> <code>row_number()</code>: 순위 계산</a></li>
<li class="chapter" data-level="8.1.11" data-path="section-37.html"><a href="section-37.html#ntile--"><i class="fa fa-check"></i><b>8.1.11</b> <code>ntile()</code>: 분위수 계산</a></li>
<li class="chapter" data-level="8.1.12" data-path="section-37.html"><a href="section-37.html#group_by---"><i class="fa fa-check"></i><b>8.1.12</b> <code>group_by()</code>: 그룹별로 데이터를 묶음</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="section-37.html"><a href="section-37.html#section-39"><i class="fa fa-check"></i><b>8.2</b> 종목정보 시각화</a></li>
<li class="chapter" data-level="8.3" data-path="section-37.html"><a href="section-37.html#section-40"><i class="fa fa-check"></i><b>8.3</b> 주가 및 수익률 시각화</a><ul>
<li class="chapter" data-level="8.3.1" data-path="section-37.html"><a href="section-37.html#section-41"><i class="fa fa-check"></i><b>8.3.1</b> 주가 그래프 나타내기</a></li>
<li class="chapter" data-level="8.3.2" data-path="section-37.html"><a href="section-37.html#section-42"><i class="fa fa-check"></i><b>8.3.2</b> 인터랙티브 그래프 나타내기</a></li>
<li class="chapter" data-level="8.3.3" data-path="section-37.html"><a href="section-37.html#section-43"><i class="fa fa-check"></i><b>8.3.3</b> 연도별 수익률 나타내기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="section-44.html"><a href="section-44.html"><i class="fa fa-check"></i><b>9</b> 퀀트 전략을 이용한 종목선정 (기본)</a><ul>
<li class="chapter" data-level="9.1" data-path="section-44.html"><a href="section-44.html#section-45"><i class="fa fa-check"></i><b>9.1</b> 베타 이해하기</a><ul>
<li class="chapter" data-level="9.1.1" data-path="section-44.html"><a href="section-44.html#section-46"><i class="fa fa-check"></i><b>9.1.1</b> 베타 계산하기</a></li>
<li class="chapter" data-level="9.1.2" data-path="section-44.html"><a href="section-44.html#section-47"><i class="fa fa-check"></i><b>9.1.2</b> 베타 시각화</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="section-44.html"><a href="section-44.html#section-48"><i class="fa fa-check"></i><b>9.2</b> 저변동성 전략</a><ul>
<li class="chapter" data-level="9.2.1" data-path="section-44.html"><a href="section-44.html#section-49"><i class="fa fa-check"></i><b>9.2.1</b> 저변동성 포트폴리오 구하기: 일간 기준</a></li>
<li class="chapter" data-level="9.2.2" data-path="section-44.html"><a href="section-44.html#section-50"><i class="fa fa-check"></i><b>9.2.2</b> 저변동성 포트폴리오 구하기: 주간 기준</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="section-44.html"><a href="section-44.html#section-51"><i class="fa fa-check"></i><b>9.3</b> 모멘텀 전략</a><ul>
<li class="chapter" data-level="9.3.1" data-path="section-44.html"><a href="section-44.html#section-52"><i class="fa fa-check"></i><b>9.3.1</b> 모멘텀 포트폴리오 구하기: 12개월 모멘텀</a></li>
<li class="chapter" data-level="9.3.2" data-path="section-44.html"><a href="section-44.html#section-53"><i class="fa fa-check"></i><b>9.3.2</b> 모멘텀 포트폴리오 구하기: 위험조정 수익률</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="section-44.html"><a href="section-44.html#section-54"><i class="fa fa-check"></i><b>9.4</b> 밸류 전략</a><ul>
<li class="chapter" data-level="9.4.1" data-path="section-44.html"><a href="section-44.html#pbr"><i class="fa fa-check"></i><b>9.4.1</b> 밸류 포트폴리오 구하기: 저 PBR</a></li>
<li class="chapter" data-level="9.4.2" data-path="section-44.html"><a href="section-44.html#section-55"><i class="fa fa-check"></i><b>9.4.2</b> 각 지표를 결합하기</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="section-44.html"><a href="section-44.html#section-56"><i class="fa fa-check"></i><b>9.5</b> 퀄리티 전략</a><ul>
<li class="chapter" data-level="9.5.1" data-path="section-44.html"><a href="section-44.html#f-score"><i class="fa fa-check"></i><b>9.5.1</b> F-Score</a></li>
<li class="chapter" data-level="9.5.2" data-path="section-44.html"><a href="section-44.html#section-57"><i class="fa fa-check"></i><b>9.5.2</b> 각 지표를 결합하기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="section-58.html"><a href="section-58.html"><i class="fa fa-check"></i><b>10</b> 퀀트 전략을 이용한 종목선정 (심화)</a><ul>
<li class="chapter" data-level="10.1" data-path="section-58.html"><a href="section-58.html#section-59"><i class="fa fa-check"></i><b>10.1</b> 섹터 중립 포트폴리오</a></li>
<li class="chapter" data-level="10.2" data-path="section-58.html"><a href="section-58.html#section-60"><i class="fa fa-check"></i><b>10.2</b> 마법공식</a><ul>
<li class="chapter" data-level="10.2.1" data-path="section-58.html"><a href="section-58.html#section-61"><i class="fa fa-check"></i><b>10.2.1</b> 퀄리티와 밸류 간의 관계</a></li>
<li class="chapter" data-level="10.2.2" data-path="section-58.html"><a href="section-58.html#section-62"><i class="fa fa-check"></i><b>10.2.2</b> 마법공식 이해하기</a></li>
<li class="chapter" data-level="10.2.3" data-path="section-58.html"><a href="section-58.html#section-63"><i class="fa fa-check"></i><b>10.2.3</b> 마법공식 구성하기</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="section-58.html"><a href="section-58.html#section-64"><i class="fa fa-check"></i><b>10.3</b> 이상치 데이터 제거 및 팩터의 결합</a><ul>
<li class="chapter" data-level="10.3.1" data-path="section-58.html"><a href="section-58.html#trim---"><i class="fa fa-check"></i><b>10.3.1</b> 트림(Trim): 이상치 데이터 삭제</a></li>
<li class="chapter" data-level="10.3.2" data-path="section-58.html"><a href="section-58.html#winsorizing---"><i class="fa fa-check"></i><b>10.3.2</b> 윈저라이징(Winsorizing): 이상치 데이터 대체</a></li>
<li class="chapter" data-level="10.3.3" data-path="section-58.html"><a href="section-58.html#section-65"><i class="fa fa-check"></i><b>10.3.3</b> 팩터의 결합 방법</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="section-58.html"><a href="section-58.html#section-66"><i class="fa fa-check"></i><b>10.4</b> 멀티팩터 포트폴리오</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="section-67.html"><a href="section-67.html"><i class="fa fa-check"></i><b>11</b> 포트폴리오 구성</a><ul>
<li class="chapter" data-level="11.1" data-path="section-67.html"><a href="section-67.html#section-68"><i class="fa fa-check"></i><b>11.1</b> 최소분산 포트폴리오</a><ul>
<li class="chapter" data-level="11.1.1" data-path="section-67.html"><a href="section-67.html#slsqp---"><i class="fa fa-check"></i><b>11.1.1</b> <code>slsqp()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.2" data-path="section-67.html"><a href="section-67.html#solve.qp---"><i class="fa fa-check"></i><b>11.1.2</b> <code>solve.QP()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.3" data-path="section-67.html"><a href="section-67.html#optimalportfolio---"><i class="fa fa-check"></i><b>11.1.3</b> <code>optimalPortfolio()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.4" data-path="section-67.html"><a href="section-67.html#section-69"><i class="fa fa-check"></i><b>11.1.4</b> 결과값들의 비교</a></li>
<li class="chapter" data-level="11.1.5" data-path="section-67.html"><a href="section-67.html#section-70"><i class="fa fa-check"></i><b>11.1.5</b> 최소 및 최대 투자비중 제약조건</a></li>
<li class="chapter" data-level="11.1.6" data-path="section-67.html"><a href="section-67.html#section-71"><i class="fa fa-check"></i><b>11.1.6</b> 각 자산 별 제약조건의 추가</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="section-67.html"><a href="section-67.html#section-72"><i class="fa fa-check"></i><b>11.2</b> 최대분산효과 포트폴리오</a><ul>
<li class="chapter" data-level="11.2.1" data-path="section-67.html"><a href="section-67.html#solve.qp----1"><i class="fa fa-check"></i><b>11.2.1</b> <code>solve.QP()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.2.2" data-path="section-67.html"><a href="section-67.html#optimalportfolio----1"><i class="fa fa-check"></i><b>11.2.2</b> <code>optimalPortfolio()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.2.3" data-path="section-67.html"><a href="section-67.html#section-73"><i class="fa fa-check"></i><b>11.2.3</b> 최소 및 최대 투자비중 제약조건</a></li>
<li class="chapter" data-level="11.2.4" data-path="section-67.html"><a href="section-67.html#section-74"><i class="fa fa-check"></i><b>11.2.4</b> 각 자산 별 제약조건의 추가</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="section-67.html"><a href="section-67.html#section-75"><i class="fa fa-check"></i><b>11.3</b> 위험균형 포트폴리오</a><ul>
<li class="chapter" data-level="11.3.1" data-path="section-67.html"><a href="section-67.html#section-76"><i class="fa fa-check"></i><b>11.3.1</b> 전통적 자산배분, 주식 60%와 채권 40%</a></li>
<li class="chapter" data-level="11.3.2" data-path="section-67.html"><a href="section-67.html#rp---"><i class="fa fa-check"></i><b>11.3.2</b> <code>rp()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.3.3" data-path="section-67.html"><a href="section-67.html#section-77"><i class="fa fa-check"></i><b>11.3.3</b> 위험예산 포트폴리오</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="section-78.html"><a href="section-78.html"><i class="fa fa-check"></i><b>12</b> 포트폴리오 백테스트</a><ul>
<li class="chapter" data-level="12.1" data-path="section-78.html"><a href="section-78.html#return.portfolio-"><i class="fa fa-check"></i><b>12.1</b> <code>Return.Portfolio()</code> 함수</a><ul>
<li class="chapter" data-level="12.1.1" data-path="section-78.html"><a href="section-78.html#section-79"><i class="fa fa-check"></i><b>12.1.1</b> 인자목록 살펴보기</a></li>
<li class="chapter" data-level="12.1.2" data-path="section-78.html"><a href="section-78.html#section-80"><i class="fa fa-check"></i><b>12.1.2</b> 출력값 살펴보기</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="section-78.html"><a href="section-78.html#section-81"><i class="fa fa-check"></i><b>12.2</b> 전통적인 60대 40 포트폴리오 백테스트</a></li>
<li class="chapter" data-level="12.3" data-path="section-78.html"><a href="section-78.html#section-82"><i class="fa fa-check"></i><b>12.3</b> 시점 선택 전략 백테스트</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://henryquant.blogspot.com/" target="blank">Henry's Quantopia</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">퀀트 투자 쿡북: R을 이용한 투자 포트폴리오 만들기</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="section-67" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> 포트폴리오 구성</h1>
<p>종목의 선택 못지 않게 중요한 것이 포트폴리오를 구성하는 방법입니다. 종목별로 비중을 어떻게 배분하느냐에 따라 성과가 달라질 수 있기 때문입니다. 최적 포트폴리오의 구성은 수식을 기반으로 최적화된 해를 찾습니다. 물론 엑셀의 해찾기와 같은 기능을 사용하여 간단한 형태의 최적화 구현이 가능하지만, 데이터가 방대해질 경우에는 속도가 지나치게 느려져 효율적이지 않습니다.</p>
<p>동일한 최적화 방법을 지속적으로 사용할 경우 프로그래밍을 통해 함수를 만들고, 입력 변수만 변경하는 것이 훨씬 효율적인 방법입니다. 또한 포트폴리오 최적화에 관한 좋은 패키지들이 이미 많이 나와 있으므로, 대략적인 내용만 이해하고 실제 구현은 패키지를 이용하는 것도 유용한 방법입니다.</p>
<p>본 장에서는 일반적으로 많이 쓰이는 최소분산 포트폴리오, 최대분산효과 포트폴리오, 위험균형 포트폴리오를 구현해보도록 합니다. 먼저 포트폴리오 구성을 위해 글로벌 자산을 대표하는 ETF 데이터를 다운로드 받도록 하겠습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(quantmod)
<span class="kw">library</span>(PerformanceAnalytics)
<span class="kw">library</span>(magrittr)

symbols =<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;SPY&#39;</span>, <span class="co"># 미국 주식: SPDR S&amp;P 500 ETF</span>
            <span class="st">&#39;IEV&#39;</span>, <span class="co"># 유럽 주식: iShares Europe ETF </span>
            <span class="st">&#39;EWJ&#39;</span>, <span class="co"># 일본 주식: iShares Europe ETF </span>
            <span class="st">&#39;EEM&#39;</span>, <span class="co"># 이머징 주식: iShares MSCI Emerging Markets ETF</span>
            <span class="st">&#39;TLT&#39;</span>, <span class="co"># 미국 장기채: iShares 20+ Year Treasury Bond ETF</span>
            <span class="st">&#39;IEF&#39;</span>, <span class="co"># 미국 중기채: iShares 7-10 Year Treasury Bond ETF</span>
            <span class="st">&#39;IYR&#39;</span>, <span class="co"># 미국 리츠: iShares U.S. Real Estate ETF</span>
            <span class="st">&#39;RWX&#39;</span>, <span class="co"># 글로벌 리츠: SPDR Dow Jones International Real Estate ETF</span>
            <span class="st">&#39;GLD&#39;</span>, <span class="co"># 금: SPDR Gold Shares</span>
            <span class="st">&#39;DBC&#39;</span>  <span class="co"># 상품: Invesco DB Commodity Index Tracking Fund</span>
            )
<span class="kw">getSymbols</span>(symbols, <span class="dt">src =</span> <span class="st">&#39;yahoo&#39;</span>)

prices =<span class="st"> </span><span class="kw">do.call</span>(cbind, <span class="kw">lapply</span>(symbols, <span class="cf">function</span>(x) <span class="kw">Ad</span>(<span class="kw">get</span>(x)))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(symbols)

rets =<span class="st"> </span><span class="kw">Return.calculate</span>(prices) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>()</code></pre>
<p><code>getSymbols()</code> 함수를 통해 일반적으로 자산배분에서 많이 사용되는 주식과 채권, 대체자산에 해당하는 ETF 가격 데이터를 받은 후, <code>lapply()</code>와 <code>Ad()</code>, <code>get()</code> 함수의 조합을 통해 수정주가 만을 선택하여 열의 형태로 묶어주도록 합니다. 그 후 <code>Return.calculate()</code> 함수를 통해 수익률을 계산 해줍니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyr)
<span class="kw">library</span>(dplyr)
<span class="kw">library</span>(corrplot)

<span class="kw">cor</span>(rets) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">corrplot</span>(<span class="dt">method =</span> <span class="st">&#39;color&#39;</span>, <span class="dt">type =</span> <span class="st">&#39;upper&#39;</span>,
           <span class="dt">addCoef.col =</span> <span class="st">&#39;black&#39;</span>, <span class="dt">number.cex =</span> <span class="fl">0.7</span>,
           <span class="dt">tl.cex =</span> <span class="fl">0.6</span>, <span class="dt">tl.srt=</span><span class="dv">45</span>, <span class="dt">tl.col =</span> <span class="st">&#39;black&#39;</span>,
           <span class="dt">col =</span> <span class="kw">colorRampPalette</span>(<span class="kw">c</span>(<span class="st">&#39;blue&#39;</span>, <span class="st">&#39;white&#39;</span>, <span class="st">&#39;red&#39;</span>))(<span class="dv">200</span>),
           <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="dv">0</span>))</code></pre>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-4-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>각 ETF의 수익률 간 상관관계를 살펴보면 같은 자산군 내에서는 강한 상관관계가가 보이며, 주식과 채권 간에는 매우 낮은 상관관계를 보입니다. 또한 주식과 리츠 간에도 꽤 높은 상관관계를 보입니다.</p>
<p>포트폴리오 최적화에는 <strong>분산-공분산</strong> 행렬이 대부분 사용되며, 이는 <code>cov()</code> 함수를 통해 손쉽게 계산할 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">covmat =<span class="st"> </span><span class="kw">cov</span>(rets)</code></pre>
<div id="section-68" class="section level2">
<h2><span class="header-section-number">11.1</span> 최소분산 포트폴리오</h2>
<p>최소분산 포트폴리오(Minimum Variance Portfolio)는 변동성이 최소인 포트폴리오 입니다. 포트폴리오의 변동성은 일반적으로 <span class="math inline">\(\sum_{i=1}^{n}\sum_{j=1}^{n}w_iw_j\sigma_{ij}\)</span>의 형태로 표현되지만, 최적화 작업을 위해서는 행렬의 형태인 <span class="math inline">\(w&#39;\Omega w\)</span>로 표현하는 것이 더욱 편리합니다. 이 중 <span class="math inline">\(w\)</span>는 각 자산들의 비중을 행렬의 형태로 나타낸 것이며, <span class="math inline">\(\Omega\)</span>는 각 자산 별 분산-공분산 행렬을 나타낸 것입니다. 분산-공분산 행렬은 사전에 고정되어 있는 값이므로, 각 자산들의 비중인 <span class="math inline">\(w\)</span>를 변화시킴으로써 포트폴리오의 변동성이 최소인 지점을 찾을 수 있습니다.</p>
<p>최소분산 포트폴리오의 목적함수는 아래의 수식으로 표현할 수 있습니다. 이 중 <span class="math inline">\(^1/_2\)</span>은 단지 미분했을 때 계산을 용이하게 하기 위한 장치일 뿐 결과에는 영향을 미치지 않습니다.</p>
<p><span class="math display">\[ 최소분산\,포트폴리오의\,목적함수: min\,^1/_2\,w&#39;\Omega w \]</span></p>
<p>다만 단순히 위의 목적함수를 찾는 해를 구할 경우 결과 값이 음수가 나오기도 하며, 이는 공매도를 의미합니다. 일반적으로 공매도가 불가능하다는 점과, 투자 비중의 합이 100%가 되어야 한다는 점을 고려하면 아래와 같은 제약조건을 추가해야 합니다.</p>
<p><span class="math display">\[ 최소분산\,포트폴리오의\,제약조건: \sum_{i=1}^{n}w_i = 1, w_i \ge 0 \]</span>
물론 이 외에도 각 섹터의 투자비중 합에 대한 제약, 회전율에 대한 제약 등도 추가할 수 있습니다. 그러나 이는 코드가 지나치게 복잡해지며, 정확한 계산을 위해서는 좀 더 전문화된 프로그램을 사용할 필요가 있으므로 해당 책에서는 다루지 않도록 하겠습니다.</p>
<div id="slsqp---" class="section level3">
<h3><span class="header-section-number">11.1.1</span> <code>slsqp()</code> 함수를 이용한 최적화</h3>
<p>R에서 가장 손쉽게 최적화 작업을 수행하는 방법은 <code>nloptr</code> 패키지의 <code>slsqp()</code> 함수를 이용하는 법입니다. 해당 함수는 순차적 이차 계획(Sequential quadratic programming)을 이용하여 해를 찾으며, 목적함수와 제약조건은 아래와 같습니다.</p>
<table>
<caption><span id="tab:unnamed-chunk-6">Table 2.1: </span><code>slsqp()</code> 함수 목적함수와 제약조건</caption>
<thead>
<tr class="header">
<th align="left">목적함수</th>
<th align="left">제약조건</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(min\,f(x)\)</span></td>
<td align="left"><span class="math inline">\(b(x)\ge0\)</span><br><span class="math inline">\(c(x)=0\)</span></td>
</tr>
</tbody>
</table>
<p>목적함수에서 <span class="math inline">\(f(x)\)</span> 는 최소화 하고자 하는 값, 즉 포트폴리오의 변동성입니다. 제약조건은 크게 개별 자산의 투자 비중이 0 이상인 것과, 투자 비중의 합이 1이 되도록 하는 것입니다. 첫번째 제약조건은 자연스럽게 개별 자산의 투자 비중이 0 이상인 것을 의미합니다. 두 번째 제약조건은 약간의 변형을 통해 투자 비중의 합이 1이 되는 제약조건을 만들 수 있습니다. c(x)를 ‘투자 비중의 합 – 1’ 로 변형할 경우, -1을 우변으로 넘기면 결국 ‘투자 비중의 합 = 1’ 의 형태로 나타낼 수 있습니다. <code>slsqp()</code> 함수의 구성은 다음과 같습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">slsqp</span>(x0, fn, <span class="dt">gr =</span> <span class="ot">NULL</span>, <span class="dt">lower =</span> <span class="ot">NULL</span>, <span class="dt">upper =</span> <span class="ot">NULL</span>,
      <span class="dt">hin =</span> <span class="ot">NULL</span>, <span class="dt">hinjac =</span> <span class="ot">NULL</span>, <span class="dt">heq =</span> <span class="ot">NULL</span>, <span class="dt">heqjac =</span> <span class="ot">NULL</span>,
      <span class="dt">nl.info =</span> <span class="ot">FALSE</span>, <span class="dt">control =</span> <span class="kw">list</span>(), ...)</code></pre>
<p>이 중 우리가 구체적으로 입력해야 할 값은 x0, fn, hin, heq 항목 입니다.</p>
<ol style="list-style-type: decimal">
<li>x0는 초기 시작값으로써, 일반적으로 모든 x에 대해 동일한 값을 입력합니다.</li>
<li>fn은 최소화 하고자 하는 목적함수로써, 포트폴리오의 변동성에 해당합니다.</li>
<li>hin은 부등위 제약조건(inequality constraints)을 의미하며, 프로그래밍 내에서는 hin &gt;= 0 로 인식하며, 각 자산의 비중이 0보다 크다는 제약조건과 연결됩니다.</li>
<li>heq는 등위 제약조건(equality constraints)을 의미하며 프로그래밍 내에서는 heq == 0을 의미합니다. ’투자 비중의 합 - 1’의 형태를 입력 할 경우, 투자 비중의 합이 1이 라는 제약조건과 연결됩니다.</li>
</ol>
<p>표 <a href="section-67.html#tab:slsqp">11.1</a>는 최소분산 포트폴리오를 구할 때 필요한 주요 변수에 대한 내용입니다.</p>
<table>
<caption><span id="tab:slsqp">Table 11.1: </span><code>slsqp()</code> 함수의 인자와 포트폴리오 내 변수</caption>
<thead>
<tr class="header">
<th align="left">변수명</th>
<th align="left">내용</th>
<th align="left">포트폴리오 내 변수</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">x0</td>
<td align="left">초기값</td>
<td align="left">-</td>
</tr>
<tr class="even">
<td align="left">fn</td>
<td align="left">목적함수</td>
<td align="left">포트폴리오 변동성</td>
</tr>
<tr class="odd">
<td align="left">hin</td>
<td align="left">부등위 제약조건</td>
<td align="left">각 자산의 비중이 0 보다 큰 제약조건</td>
</tr>
<tr class="even">
<td align="left">heq</td>
<td align="left">등위 제약조건</td>
<td align="left">투자 비중의 합이 1인 제약조건</td>
</tr>
</tbody>
</table>
<p><code>slsqp()</code> 함수를 이용하여 최소분산 포트폴리오를 만족하는 자산의 투자 비중을 구하는 과정은 다음과 같습니다. 먼저 fn, hin, heq에 해당하는 함수들을 각각 만들어 준 후, 이를 slsqp() 함수와 결합하여 최적화된 결과값을 얻을 수 있습니다. 구체적인 과정은 아래와 같습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">objective =<span class="st"> </span><span class="cf">function</span>(w) {
  obj =<span class="st"> </span><span class="kw">t</span>(w) <span class="op">%*%</span><span class="st"> </span>covmat <span class="op">%*%</span><span class="st"> </span>w
  <span class="kw">return</span>(obj)
}</code></pre>
<p>먼저 목적함수에 해당하는 부분입니다. covmat은 사전에 계산된 분산-공분산 행렬이며, <span class="math inline">\(w\)</span>는 각 자산의 투자 비중입니다. obj는 포트폴리오의 변동성인 <span class="math inline">\(w&#39;\Omega w\)</span>를 계산한 것입니다. 즉, 해당 함수는 계산된 <span class="math inline">\(w\)</span>를 바탕으로 포트폴리오의 변동성을 반환하고, 우리의 목적은 해당 값이 최소가 되도록 하는 것입니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">hin.objective =<span class="st"> </span><span class="cf">function</span>(w) {
  <span class="kw">return</span>(w)
}</code></pre>
<p><span class="math inline">\(w_i \ge 0\)</span> 제약조건에 해당하는 부등위 제약조건입니다. 패키지 내에서는 hin &gt;= 0 의 형태로 인식을 하므로, 계산된 비중인 <span class="math inline">\(w\)</span>를 단순히 입력하기만 하면 됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">heq.objective =<span class="st"> </span><span class="cf">function</span>(w) {
  sum_w =<span class="st"> </span><span class="kw">sum</span>(w)
  <span class="kw">return</span>( sum_w <span class="op">-</span><span class="st"> </span><span class="dv">1</span> )
}</code></pre>
<p><span class="math inline">\(\sum_{i=1}^{n}w_i = 1\)</span> 제약조건에 해당하는 등위 제약조건입니다. 먼저 계산된 비중인 <span class="math inline">\(w\)</span>들의 합계를 구한 후, 해당 값에서 1을 빼주는 값을 반환하도록 합니다. 프로그래밍 내에서는 heq == 0 의 형태로 인식을 하므로, 결국 (sum_w – 1) == 0, 즉 sum_w == 1 의 제약조건과 동일하게 됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(nloptr)

result =<span class="st"> </span><span class="kw">slsqp</span>( <span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),
                <span class="dt">fn =</span> objective,
                <span class="dt">hin =</span> hin.objective,
                <span class="dt">heq =</span> heq.objective)

<span class="kw">print</span>(result)</code></pre>
<pre><code>## $par
##  [1]  1.529389e-01 -3.785834e-18 -1.754307e-17 -3.639632e-19 -2.276099e-18
##  [6]  7.844576e-01  4.289285e-18  1.248200e-17 -3.338117e-19  6.260344e-02
## 
## $value
## [1] 9.697801e-06
## 
## $iter
## [1] 139
## 
## $convergence
## [1] 4
## 
## $message
## [1] &quot;NLOPT_XTOL_REACHED: Optimization stopped because xtol_rel or xtol_abs (above) was reached.&quot;</code></pre>
<p>위에서 만들어진 함수들을 바탕으로 최적화 작업을 실행합니다. 초기값인 x0에는 먼저 동일한 비중들을 입력합니다. 예제에서는 종목이 10개 이므로, x0값에는 rep(0.1, 10) 인 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 가 입력됩니다. 최소화 하고자 하는 목적함수 fn에는 위에서 구성한 objective 함수를 입력합니다. 부등위 제약조건과 등위 제약조건에도 각각 위에서 구성한 hin.objective 함수와 heq.objective를 입력합니다.</p>
<p>즉, 해당 함수는 초기값을 시작점으로 하여 주어진 제약조건을 만족하는 해를 찾기 위해 <span class="math inline">\(w\)</span>값들을 조정하는 작업을 반복한 후, 목적함수가 최소가 되는 지점의 <span class="math inline">\(w\)</span>를 반환합니다.</p>
<p>result 값 중 $par는 최적화된 지점의 해를 의미하며, 여기서는 최소분산 포트폴리오를 구성하는 자산들의 투자 비중을 의미합니다. $value는 $par에서 산출된 값을 목적함수 fn에 입력하였을 때 나오는 결과값으로써, 여기서는 포트폴리오의 분산을 의미합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">w_<span class="dv">1</span> =<span class="st"> </span>result<span class="op">$</span>par <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w_<span class="dv">1</span>)</code></pre>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX    GLD    DBC 
## 0.1529 0.0000 0.0000 0.0000 0.0000 0.7845 0.0000 0.0000 0.0000 0.0626</code></pre>
<p>자산들의 투자비중은 result$par 를 통해 추출한 후, <code>round()</code> 함수를 이용하여 반올림을 하여 줍니다. 마지막으로 이름에 종목명을 입력해주도록 합니다. 계산된 비중으로 포트폴리오를 구성할 경우, 포트폴리오의 비중이 최소화 됩니다.</p>
</div>
<div id="solve.qp---" class="section level3">
<h3><span class="header-section-number">11.1.2</span> <code>solve.QP()</code> 함수를 이용한 최적화</h3>
<p>다음으로는 <code>quadprog</code> 패키지 내의 <code>solve.QP()</code> 함수를 이용하여 포트폴리오 최적화를 하는 방법이 있습니다. 해당 함수는 쌍대기법(Dual Method)를 이용하여 제약조건 내에서 목적함수가 최소화 되는 해를 구합니다. 해당 함수의 목적함수와 제약조건은 표 <a href="section-67.html#tab:solveqp">11.2</a>와 같습니다.</p>
<table>
<caption><span id="tab:solveqp">Table 11.2: </span><code>solve.QP</code> 함수 목적함수와 제약조건</caption>
<thead>
<tr class="header">
<th align="left">목적함수</th>
<th align="left">제약조건</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(min(-d^Tb+^1/_2b^TDb)\)</span></td>
<td align="left"><span class="math inline">\(A^Tb \ge b_0\)</span></td>
</tr>
</tbody>
</table>
<p>최소분산 포트폴리오의 목적함수가 <span class="math inline">\(min\,^1/_2\,w&#39;\Omega w\)</span> 로 표시된다는 점을 생각하면, 해당 함수는 매우 이해하기 쉽게 구성되어 있습니다. b를 각 개별 자산의 투자 비중인 <span class="math inline">\(w\)</span>, D를 분산-공분산 행렬인 <span class="math inline">\(\Omega\)</span>라 생각하면, 목적함수 중 <span class="math inline">\(min\,^1/_2\,wDw\)</span>는 최소분산 포트폴리오의 목적함수와 정확히 동일합니다. d를 0으로 생각할 경우 <span class="math inline">\(-d^Tb\)</span> 또한 0이 되어 목적함수에 아무런 영향도 미치지 않습니다.</p>
<p>제약조건 역시 <span class="math inline">\(A^T\)</span> 항목을 적절하게 수정하여 준다면, 개별 자산의 투자 비중이 0 이상인 것과, 투자 비중의 합이 1이 되도록 만들 수 있습니다. 이에 대해서는 뒤에서 구체적으로 다루도록 합니다. <code>solve.QP()</code> 함수의 사용법은 아래와 같습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, <span class="dt">meq =</span> <span class="dv">0</span>, <span class="dt">factorized =</span> <span class="ot">FALSE</span>)</code></pre>
<ol style="list-style-type: decimal">
<li>Dmat은 목적함수 중 D에 해당하는 행렬부분으로써 분산-공분산 행렬과 일치합니다.</li>
<li>dvec은 목적함수 중 d에 해당하는 벡터부분이며, 포트폴리오 최적화에서는 역할이 없습니다.</li>
<li>Amat은 제약조건 중 <span class="math inline">\(A^T\)</span>에 해당하는 부분으로써, 제약조건 중 좌변에 위치하는 항목입니다. 주의할 점은 제약조건에서 보듯이 제약조건 행렬을 구한 후 이의 전치(Transpose)행렬을 입력해야 합니다.</li>
<li>bvec은 제약조건 중 b_0에 해당하는 부분으로써, 제약조건 중 우변에 위치하는 항목입니다.</li>
<li>meq는 bvec의 몇번째 까지를 등위 제약조건으로 설정할지에 대한 부분입니다.</li>
</ol>
<p>표 <a href="section-67.html#tab:solveqp2">11.3</a>는 위의 내용을 요약한 것이며, 각 변수를 입력한 후 함수를 실행할 경우 위의 목적함수와 제약조건을 만족하는 b값을 찾습니다.</p>
<table>
<caption><span id="tab:solveqp2">Table 11.3: </span><code>solve.QP</code> 함수의 인자와 포트폴리오 내 변수</caption>
<thead>
<tr class="header">
<th align="left">변수명</th>
<th align="left">내용</th>
<th align="left">포트폴리오 내 변수</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Dmat</td>
<td align="left">목적함수 중 D</td>
<td align="left">분산-공분산 행렬</td>
</tr>
<tr class="even">
<td align="left">dvec</td>
<td align="left">목적함수 중 d</td>
<td align="left">해당사항 없음</td>
</tr>
<tr class="odd">
<td align="left">Amat</td>
<td align="left">제약조건 (좌변)</td>
<td align="left"><span class="math inline">\(\sum_{i=1}^{n}w_i, w_i\)</span></td>
</tr>
<tr class="even">
<td align="left">bvec</td>
<td align="left">제약조건 (우변)</td>
<td align="left">각 비중이 0보다 큼, 비중의 합이 1</td>
</tr>
<tr class="odd">
<td align="left">meq</td>
<td align="left">등위 제약조건 개수</td>
<td align="left">1개 (비중의 합이 1)</td>
</tr>
</tbody>
</table>
<p><code>solve.QP()</code> 함수를 이용하여 최소분산 포트폴리오 비중을 구할 때는 Amat 항목을 제대로 입력하는 것이 가장 중요하며, 나머지 항목은 매우 손쉽게 입력이 가능합니다. 설명된 내용에 해당하는 행렬을 손으로 직접 써가며 계산해 보신다면 훨씬 이해하기가 쉬울 것입니다. 구체적인 과정은 아래와 같습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">Dmat =<span class="st"> </span>covmat
dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)
Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="kw">diag</span>(<span class="dv">10</span>), <span class="op">-</span><span class="kw">diag</span>(<span class="dv">10</span>)))
bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="op">-</span><span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>))
meq =<span class="st"> </span><span class="dv">1</span></code></pre>
<p>Dmat에는 분산-공분산 행렬을 입력하며, dvec은 최소분산 포트폴리오를 구하는데는 필요한 값이 아니므로 0벡터를 입력 합니다. 등위 제약조건과 부등위 제약조건(<span class="math inline">\(A^Tb \ge b_0\)</span>)을 행렬의 형태로 표현하면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix}
1 &amp; 1 &amp; \dots &amp; 1 \\ 1 &amp; 0 &amp; \dots &amp; 0 \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \dots &amp; 1 \\ -1 &amp; 0 &amp; \dots &amp; 0 \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \dots &amp; -1 \\ \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} = 
\begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ \vdots \\ w_{10} \\ -w_1 \\ 
\vdots \\ -w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ -1 \\ \vdots \\ -1 \end{bmatrix}
\]</span></p>
<p>이 중, 맨 좌측 행렬의 전치행렬이 제약조건의 좌변인 Amat에 해당합니다.</p>
<p><span class="math display">\[ Amat = \begin{bmatrix}
1 &amp; 1 &amp; \dots &amp; 1 \\ 1 &amp; 0 &amp; \dots &amp; 0 \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \dots &amp; 1 \\ -1 &amp; 0 &amp; \dots &amp; 0 \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \dots &amp; -1 \end{bmatrix} ^T \]</span></p>
<p>맨 우측 행렬이 제약조건의 우변인 bvec에 해당합니다.
<span class="math display">\[ bvec = \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ -1 \\ \vdots \\ -1 \end{bmatrix} \]</span></p>
<p>위의 제약조건은 크게 투자 비중의 합이 1인 제약조건, 최소 투자 비중이 0 이상인 제약조건, 최대 투자 비중이 1 이하인 제약조건, 총 3개 부분으로 나눌 수 있습니다.</p>
<p><span class="math display">\[ (1)\; \sum_{i = 1}^nw_i = 1 \Rightarrow \begin{bmatrix} w_1 + w_2 + \dots \ w_{10}  \end{bmatrix} = 
\begin{bmatrix} 1 \end{bmatrix} \\
(2)\; w_i \ge 0 \Rightarrow \begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10}  \end{bmatrix} \ge
\begin{bmatrix} 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix} \\
(3)\;-w_i \ge -1 \Rightarrow  \begin{bmatrix} -w_1 \\ -w_2 \\ \vdots \\ -w_{10}  \end{bmatrix} \ge
\begin{bmatrix} -1 \\ -1 \\ \vdots \\ -1 \end{bmatrix}
\]</span></p>
<p><code>solve.QP()</code> 함수의 제약조건은 항상 좌변이 큰 형태이므로, 최대 투자 비중에 대한 제약 조건의 경우 다음 행렬의 양변에 마이너스(-)를 곱하여 부등호를 맞춰주었습니다.</p>
<p><span class="math display">\[\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10}  \end{bmatrix} \le
\begin{bmatrix} 1 \\ 1 \\ \vdots \\ 1 \end{bmatrix}\]</span></p>
<p>첫번째 제약조건은 부등호가 아닌 등호, 즉 투자 비중의 합이 1인 조건을 의미하므로 meq = 1을 통해 첫번째 제약조건은 등식 제약조건임을 선언할 수 있습니다.</p>
<p>제약조건의 좌변에 해당하는 Amat을 만드는 과정은 다음과 같습니다. 먼저 <code>rep(1, 10)</code>를 통해 최상단에 위치한 1로 이루어진 행렬을 만들어줍니다.</p>
<p><span class="math display">\[\begin{bmatrix} 1 &amp; 1 &amp; \dots &amp; 1 \end{bmatrix}\]</span></p>
<p>하단의 1과 -1로 이루어진 대각행렬은 <code>diag()</code> 함수를 통해 쉽게 만들 수 있습니다.</p>
<p><span class="math display">\[
diag(10) = \begin{bmatrix} 1 &amp; \dots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\ 0 &amp; \dots &amp;\ 1\end{bmatrix} \\
-diag(10) = \begin{bmatrix} -1 &amp; \dots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\ 0 &amp; \dots &amp;\ -1\end{bmatrix}
\]</span>
세 개의 행렬을 <code>rbind()</code> 함수를 통해 행으로 묶어주면 제약조건의 맨 좌측 행렬과 동일한 형태가 됩니다. 이를 <code>t()</code> 함수를 통해 전치행렬을 만들어 준 뒤 Amat에 입력합니다.</p>
<p>제약조건에 해당하는 bvec은 1, 0으로 이루어진 벡터, -1로 이루어진 벡터를 통해 손쉽게 만들 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(quadprog)
result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)

<span class="kw">print</span>(result)</code></pre>
<pre><code>## $solution
##  [1]  1.529389e-01 -5.585486e-18  3.501337e-19  3.704057e-18 -6.027648e-17
##  [6]  7.844576e-01 -3.979972e-19 -5.225962e-18  0.000000e+00  6.260344e-02
## 
## $value
## [1] 4.8489e-06
## 
## $unconstrained.solution
##  [1] 0 0 0 0 0 0 0 0 0 0
## 
## $iterations
## [1] 9 0
## 
## $Lagrangian
##  [1] 9.697801e-06 0.000000e+00 1.462567e-06 1.024397e-06 5.206227e-06
##  [6] 8.078963e-06 0.000000e+00 6.651101e-06 1.275822e-06 5.006650e-07
## [11] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
## [16] 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
## [21] 0.000000e+00
## 
## $iact
## [1]  1  6  5  8  3  9  4 10</code></pre>
<p>위에 입력된 내역들을 <code>solve.QP()</code> 함수에 넣어 최적화 값을 찾아줍니다. 위의 코드를 실행한 후 result를 입력하면 다음과 같은 결과값을 확인할 수 있습니다. 결과 중 $solution은 최적화된 지점의 해, 즉 최소분산 포트폴리오를 구성하는 자산들의 투자 비중을 의미합니다. $value는 $solution에서 산출된 값을 목적함수에 입력하였을 때 나오는 결과값으로써, 포트폴리오의 분산을 의미합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">w_<span class="dv">2</span> =<span class="st"> </span>result<span class="op">$</span>solution <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w_<span class="dv">2</span>)</code></pre>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX    GLD    DBC 
## 0.1529 0.0000 0.0000 0.0000 0.0000 0.7845 0.0000 0.0000 0.0000 0.0626</code></pre>
<p>자산들의 투자비중은 result$solution 을 통해 추출한 후, <code>round()</code> 함수를 이용하여 반올림을 하여 줍니다. 마지막으로 이름에 종목명을 입력해주도록 합니다. 계산된 비중으로 포트폴리오를 구성할 경우, 포트폴리오의 비중이 최소화 됩니다.</p>
</div>
<div id="optimalportfolio---" class="section level3">
<h3><span class="header-section-number">11.1.3</span> <code>optimalPortfolio()</code> 함수를 이용한 최적화</h3>
<p><code>RiskPortfolios</code> 패키지의 <code>optimalPortfolio()</code> 함수를 이용하여 매우 간단하게 최적화 포트폴리오를 구현할 수도 있습니다. 해당 함수의 사용법은 아래와 같습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">optimalPortfolio</span>(Sigma, <span class="dt">mu =</span> <span class="ot">NULL</span>, <span class="dt">semiDev =</span> <span class="ot">NULL</span>, <span class="dt">control =</span> <span class="kw">list</span>())</code></pre>
<p>Sigma는 분산-공분산 행렬입니다. mu와 semiDev는 각각 기대수익률과 세미 편차(semi deviation)로써, 입력하지 않아도 됩니다. control은 포트폴리오 종류 및 제약조건에 해당하는 부분이며, 자세한 내용은 표 <a href="section-67.html#tab:optimal">11.4</a>와 같습니다.</p>
<table>
<caption><span id="tab:optimal">Table 11.4: </span><code>optimalPortfolio()</code> 포트폴리오 내 control 인자</caption>
<thead>
<tr class="header">
<th align="left">종류</th>
<th align="left">입력값</th>
<th align="left">내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">type</td>
<td align="left">minvol</td>
<td align="left">최소분산 포트폴리오</td>
</tr>
<tr class="even">
<td align="left">type</td>
<td align="left">invvol</td>
<td align="left">역변동성 포트폴리오</td>
</tr>
<tr class="odd">
<td align="left">type</td>
<td align="left">erc</td>
<td align="left">위험 균형 포트폴리오</td>
</tr>
<tr class="even">
<td align="left">type</td>
<td align="left">maxdiv</td>
<td align="left">최대 분산효과 포트폴리오</td>
</tr>
<tr class="odd">
<td align="left">type</td>
<td align="left">riskeff</td>
<td align="left">위험-효율적 포트폴리오</td>
</tr>
<tr class="even">
<td align="left">constraint</td>
<td align="left">lo</td>
<td align="left">최소 투자 비중이 0 보다 클것</td>
</tr>
<tr class="odd">
<td align="left">constraint</td>
<td align="left">user</td>
<td align="left">최소(LB) 및 최대 투자 비중(UB) 설정</td>
</tr>
</tbody>
</table>
<p>control 항목에서 원하는 포트폴리오 타입과 제약조건을 입력해주면, 매우 손쉽게 최적화 포트폴리오를 구현할 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(RiskPortfolios)

w_<span class="dv">3</span> =<span class="st"> </span><span class="kw">optimalPortfolio</span>(covmat, <span class="dt">control =</span> <span class="kw">list</span>(<span class="dt">type =</span> <span class="st">&#39;minvol&#39;</span>, <span class="dt">constraint =</span> <span class="st">&#39;lo&#39;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w_<span class="dv">3</span>)  </code></pre>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX    GLD    DBC 
## 0.1529 0.0000 0.0000 0.0000 0.0000 0.7845 0.0000 0.0000 0.0000 0.0626</code></pre>
<p><code>optimalPortfolio()</code> 함수 내부에 분산-공분산 행렬을 입력합니다. type 부분에 최소분산 포트폴리오에 해당하는 ’minvol’을 입력하며, constraint에는 각 자산의 비중이 0보다 큰 제약조건인 ’lo(Long Only)’를 입력합니다. 비중의 합이 1인 제약조건은 자동적으로 적용이 됩니다.</p>
<p>이처럼 패키지를 이용할 경우 매우 훨씬 간단하게 원하는 값을 얻을 수 있습니다. github를 통해 해당 함수의 코드를 살펴보면 <code>solve.QP()</code>를 이용하여 작성한 방법과 거의 동일합니다. 따라서 위의 과정들을 대략적으로 이해한 후, 패키지를 사용하여 포트폴리오 최적화를 구현하는 것이 현명한 방법이 될 수도 있습니다.</p>
</div>
<div id="section-69" class="section level3">
<h3><span class="header-section-number">11.1.4</span> 결과값들의 비교</h3>
<p>아래 표는 <code>slsqp()</code>, <code>solve.QP()</code>, <code>optimalPortfolio()</code>를 이용하여 구한 값들의 비교입니다.</p>
<table>
<caption><span id="tab:unnamed-chunk-19">Table 11.5: </span>최적화 결과 비교</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">SPY</th>
<th align="right">IEV</th>
<th align="right">EWJ</th>
<th align="right">EEM</th>
<th align="right">TLT</th>
<th align="right">IEF</th>
<th align="right">IYR</th>
<th align="right">RWX</th>
<th align="right">GLD</th>
<th align="right">DBC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>slsqp</td>
<td align="right">0.1529</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.7845</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0626</td>
</tr>
<tr class="even">
<td>solve.QP</td>
<td align="right">0.1529</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.7845</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0626</td>
</tr>
<tr class="odd">
<td>optimalPortfolio</td>
<td align="right">0.1529</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.7845</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0626</td>
</tr>
</tbody>
</table>
<p>3가지 방법 모두 결과가 동일합니다. 그러나 여기서 나온 결과를 이용하여 그대로 투자하기에는 문제가 있습니다. 일부 자산은 투자비중이 0%, 즉 전혀 투자를 하지 않는 반면, 특정 자산에 대부분의 비중인 78.45%를 투자를 하는 편중된 결과가 나옵니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

<span class="kw">data.frame</span>(w_<span class="dv">1</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),
                        <span class="dt">y =</span> w_<span class="dv">1</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</code></pre>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-20-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>이처럼 변동성이 가장 낮은 종목에 대부분의 비중이 투자되는 구석해(Corner Solution) 문제를 해결하기 위해 각 자산의 최소 및 최대 투자 비중 제약조건을 추가해 줄 필요가 있습니다.</p>
</div>
<div id="section-70" class="section level3">
<h3><span class="header-section-number">11.1.5</span> 최소 및 최대 투자비중 제약조건</h3>
<p>구석해 문제를 방지하고, 모든 자산에 골고루 투자하기 위해 개별 투자비중을 최소 5%, 최대 20%로 하는 제약조건을 추가해 주도록 하겠습니다. 먼저 <code>slsqp()</code> 함수에서 제약조건을 추가하는 방법은 다음과 같습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">result =<span class="st"> </span><span class="kw">slsqp</span>( <span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),
                <span class="dt">fn =</span> objective,
                <span class="dt">hin =</span> hin.objective,
                <span class="dt">heq =</span> heq.objective,
                <span class="dt">lower =</span> <span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>),
                <span class="dt">upper =</span> <span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>))

w_<span class="dv">4</span> =<span class="st"> </span>result<span class="op">$</span>par <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w_<span class="dv">4</span>)</code></pre>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.05 0.05 0.05 0.05 0.20 0.20 0.05 0.05 0.20 0.10</code></pre>
<p>함수의 마지막에 lower와 upper 인자를 추가로 입력할 경우, 해당 값 사이에서 최적화를 만족하는 해를 찾게 되며, 해당 예에서는 5%와 20% 사이에서 해를 찾게 됩니다. 추가로 입력한 제약조건에 맞게, 최소 투자비중은 5%이며, 최대 투자비중은 20%임을 확인할 수 있습니다.</p>
<p>다음은 <code>solve.QP()</code> 함수 내에서 제약조건을 추가하는 방법입니다. 해당 함수 역시 다른 입력값은 모두 동일하며, 제약조건의 우변에 해당하는 bvec 항목만 수정하면 됩니다. 최소, 최대 투자비중 제약 조건을 기존 [0, 1]에서 [0.05, 0.20] 로 변경하면, bvec에 해당하는 행렬은 다음과 같이 변경됩니다.</p>
<p><span class="math display">\[ 기존: \begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ \vdots \\ w_{10} \\ -w_1 \\ 
\vdots \\ -w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ -1 \\ \vdots \\ -1 \end{bmatrix} \\
변경: \begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ \vdots \\ w_{10} \\ -w_1 \\ 
\vdots \\ -w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0.05 \\ \vdots \\ 0.05 \\ -0.20 \\ \vdots \\ -0.20 \end{bmatrix} \]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">Dmat =<span class="st"> </span>covmat
dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)
Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="kw">diag</span>(<span class="dv">10</span>), <span class="op">-</span><span class="kw">diag</span>(<span class="dv">10</span>)))
bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>), <span class="op">-</span><span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>))
meq =<span class="st"> </span><span class="dv">1</span>

result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)

w_<span class="dv">5</span> =<span class="st"> </span>result<span class="op">$</span>solution <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w_<span class="dv">5</span>)</code></pre>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.05 0.05 0.05 0.05 0.20 0.20 0.05 0.05 0.20 0.10</code></pre>
<p>bvec 항목을 제외한 모든 코드는 기존과 동일하며, 조건함수의 우변인 bvec만 각각 최소 투자비중과 최대 투자비중이 [0, 1]에서 [0.05, 0.20]으로 변경되었습니다. 해당 방법 역시 추가적인 투자비중 제약이 잘 적용되었음이 확인됩니다.</p>
<p>마지막으로 <code>optimalPortfolio()</code> 함수 내에서 최소 및 최대 투자비중을 추가하는 방법입니다. 입력변수의 control 항목 중 constraint 부분을 간단하게 수정하여 원하는 조건을 입력할 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">w_<span class="dv">6</span> =<span class="st"> </span><span class="kw">optimalPortfolio</span>(covmat, <span class="dt">control =</span> <span class="kw">list</span>(<span class="dt">type =</span> <span class="st">&#39;minvol&#39;</span>, <span class="dt">constraint =</span> <span class="st">&#39;user&#39;</span>,
                                            <span class="dt">LB =</span> <span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>), <span class="dt">UB =</span> <span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w_<span class="dv">6</span>)</code></pre>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.05 0.05 0.05 0.05 0.20 0.20 0.05 0.05 0.20 0.10</code></pre>
<p>constraint 부분에 롱온리 제약조건에 해당하는 ‘lo’ 대신 직접 제약값들을 입력할 수 있는 ’user’를 입력하며, LB에는 최소 투자비중 벡터를, UB에는 최대 투자비중 벡터를 입력합니다. 결과적으로 원하는 제약조건 내에서 결과값이 계산됩니다.</p>
<table>
<caption><span id="tab:unnamed-chunk-24">Table 11.6: </span>최소 및 최대 비중제약 조건 후 결과 비교</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">SPY</th>
<th align="right">IEV</th>
<th align="right">EWJ</th>
<th align="right">EEM</th>
<th align="right">TLT</th>
<th align="right">IEF</th>
<th align="right">IYR</th>
<th align="right">RWX</th>
<th align="right">GLD</th>
<th align="right">DBC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>slsqp</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.2</td>
<td align="right">0.2</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.2</td>
<td align="right">0.1</td>
</tr>
<tr class="even">
<td>solve.QP</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.2</td>
<td align="right">0.2</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.2</td>
<td align="right">0.1</td>
</tr>
<tr class="odd">
<td>optimalPortfolio</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.2</td>
<td align="right">0.2</td>
<td align="right">0.05</td>
<td align="right">0.05</td>
<td align="right">0.2</td>
<td align="right">0.1</td>
</tr>
</tbody>
</table>
<p>최소 및 최대 제약 조건을 추가한 경우도, 3가지 방법 모두 동일한 결과가 나오게되며, 최소 및 최대 투자비중도 각각 5%와 20%로 제한되어 구석해 문제 또한 해결되었음이 확인됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data.frame</span>(w_<span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),
                        <span class="dt">y =</span> w_<span class="dv">4</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.05</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.20</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</code></pre>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
<div id="section-71" class="section level3">
<h3><span class="header-section-number">11.1.6</span> 각 자산 별 제약조건의 추가</h3>
<p>투자 규모가 크지 않을 경우에는 위에서 추가한 제약조건 만으로도 충분히 훌륭한 포트폴리오가 구성됩니다. 그러나 투자 규모가 커질 경우 추가적인 제약조건들을 고려해야 할 경우가 생깁니다. 벤치마크 비중과의 괴리로 인한 추적오차(Tracking Error)을 고려해야 할 수도 있고, 투자 대상 별 거래량을 고려한 제약조건을 추가해야 할 경우도 있습니다.</p>
<p>기존 제약조건에는 자산 별로 동일한 최소 및 최대 투자비중 제약조건을 다루었지만, 자산 별로 상이한 제약조건이 필요할 경우도 있습니다. <code>slsqp()</code>와 <code>optimalPortfolio()</code> 함수에서는 복잡한 제약조건을 다루기가 힘들지만, <code>solve.QP()</code> 함수의 경우 bvec 부분을 간단하게 수정하여 어렵지 않게 구현이 가능합니다.</p>
<p>먼저 표 <a href="section-67.html#tab:assetconst">11.7</a>는 새롭게 설정하고자 하는 각 자산 별 최소 및 최대 제약조건 입니다.</p>
<table>
<caption><span id="tab:assetconst">Table 11.7: </span>각 자산 별 최소 및 최대 제약조건</caption>
<thead>
<tr class="header">
<th align="left">제약</th>
<th align="left">1</th>
<th align="left">2</th>
<th align="left">3</th>
<th align="left">4</th>
<th align="left">5</th>
<th align="left">6</th>
<th align="left">7</th>
<th align="left">8</th>
<th align="left">9</th>
<th align="left">10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">최소</td>
<td align="left">0.10</td>
<td align="left">0.10</td>
<td align="left">0.05</td>
<td align="left">0.05</td>
<td align="left">0.10</td>
<td align="left">0.10</td>
<td align="left">0.05</td>
<td align="left">0.05</td>
<td align="left">0.03</td>
<td align="left">0.03</td>
</tr>
<tr class="even">
<td align="left">최대</td>
<td align="left">0.25</td>
<td align="left">0.25</td>
<td align="left">0.20</td>
<td align="left">0.20</td>
<td align="left">0.20</td>
<td align="left">0.20</td>
<td align="left">0.10</td>
<td align="left">0.10</td>
<td align="left">0.08</td>
<td align="left">0.08</td>
</tr>
</tbody>
</table>
<p>이를 행렬의 형태로 나타내면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix} 1 &amp; 1 &amp; \dots &amp; 1 \\ 1 &amp; 0 &amp; \dots &amp; 0 \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \dots &amp; 1 \\ -1 &amp; 0 &amp; \dots &amp; 0 \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \dots &amp; -1 \\ \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} 
= \begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ w_2 \\ w_3 \\ w_4 \\ w_5 \\ w_6 \\
w_7\\ w_8\\ w_9\\ w_{10} \\ -w_1 \\ -w_2 \\ -w_3 \\ -w_4 \\ -w_5 \\ -w_6 \\ -w_7 \\ -w_8 \\ -w_9 \\ -w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0.10 \\ 0.10 \\ 0.05 \\ 0.05 \\ 0.10 \\ 0.10 \\ 0.05 \\ 0.05 \\ 0.03 \\ 0.03 \\ -0.25 \\ -0.25 \\ -0.20 \\ -0.20 \\ -0.20 \\ -0.20 \\ -0.10 \\ -0.10 \\ -0.08 \\ -0.08
\end{bmatrix} \]</span></p>
<p>위의 행렬 중 우측 부분을 bvec에 그대로 입력해 주도록 합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">Dmat =<span class="st"> </span>covmat
dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)
Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="kw">diag</span>(<span class="dv">10</span>), <span class="op">-</span><span class="kw">diag</span>(<span class="dv">10</span>))) 
bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">c</span>(<span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.03</span>, <span class="fl">0.03</span>),
         <span class="op">-</span><span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.08</span>, <span class="fl">0.08</span>))
meq =<span class="st"> </span><span class="dv">1</span>

result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)

result<span class="op">$</span>solution <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</code></pre>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.14 0.10 0.05 0.05 0.20 0.20 0.05 0.05 0.08 0.08</code></pre>
<p>결과값을 확인해보면, 각 자산 별 제약조건 내에 위치함을 확인할 수 있습니다.</p>
</div>
</div>
<div id="section-72" class="section level2">
<h2><span class="header-section-number">11.2</span> 최대분산효과 포트폴리오</h2>
<p>앞서 설명했듯이 포트폴리오의 변동성은 <span class="math inline">\(\sum_{i=1}^{n}\sum_{j=1}^{n}w_iw_j\sigma_{ij}\)</span> 형태로 나타나며, 이는 다음과 같이 표현할 수도 있습니다.</p>
<p><span class="math display">\[\sigma_p^2 = \sum_{i=1}^{n}\sum_{j=1}^{n}w_iw_j\sigma_{ij} = \sum_{i=1}^nw_i^2\sigma_i^2 +
\sum_{i=1}^{n}\sum_{i \ne j}^{n}w_iw_j\rho_{ij}\sigma_i\sigma_j \]</span></p>
<p>이 중 <span class="math inline">\(\sum_{i=1}^{n}\sum_{i \ne j}^{n}w_iw_j\rho_{ij}\sigma_i\sigma_j\)</span> 부분에는 자산 간 상관관계가 포함되어 있습니다. 상관관계는 -1과 1 사이에 위치하며, 자산 간 상관관계가 낮을수록 포트폴리오의 변동성 역시 낮아지게 됩니다. 상관관계가 1, 즉 두 자산이 완벽하게 동일한 경우에는 포트폴리오의 변동성은 개별 자산 변동성의 가중합과 같습니다. 그러나 상관관계가 낮아질수록 포트폴리오의 변동성 또한 점차 낮아집니다. 이러한 효과를 투자에서는 <strong>분산효과</strong>라 합니다.</p>
<p>이러한 분산효과의 정도를 측정하는 지표가 분산 비율(DR: Diversification Ratio) 입니다. 분산 비율의 분자는 개별 변동성의 가중합이며, 분모는 포트폴리오의 변동성입니다. 이를 수식으로 나타내면 다음과 같습니다.</p>
<p><span class="math display">\[ 분산\,비율 =  \frac{\sum w_i \sigma_i}{\sigma_p} = \frac{w&#39;\sigma}{\sqrt{w&#39;\Omega w}}\]</span></p>
<p>모든 자산 간의 상관관계가 1일 경우, 위의 예시에서 살펴본 것과 같이 포트폴리오의 변동성은 개별 자산 변동성의 가중합과 같아지게 됩니다. 즉, <span class="math inline">\(\sum w_i \sigma_i = \sigma_p\)</span>가 되어, 분산 비율은 1이 됩니다. 그러나 대부분의 경우에서 자산 간의 상관관계는 1보다 낮으며, 이로 인해 포트폴리오의 분산은 단순 가중합 보다 작아지게 되고(<span class="math inline">\(\sigma_p &lt; \sum w_i\sigma_i\)</span>), 이로 인해 분산 비율은 1보다 커지게 됩니다.</p>
<p>자산 간 상관관계가 낮은 종목을 위주로 포트폴리오를 구성할 수록 분산효과로 인해 포트폴리오의 변동성은 낮아지게 되고, 분산 비율은 점점 커지게 됩니다. 최대분산 포트폴리오(Most Diversified Portfolio)는 이를 이용하여 분산효과가 최대가 되는, 즉 분산 비율이 최대가 되는 포트폴리오를 구성하는 방법입니다. 이에 대한 목적함수와 제약조건은 다음과 같습니다.</p>
<p><span class="math display">\[목적함수: max\,DR = max \frac{\sum w_i \sigma_i}{\sigma_p} \\
제약조건: \sum_{i=1}^n w_i = 1, w_i \ge 0\]</span></p>
<p>최대분산효과 포트폴리오의 목적함수는 분산비율을 최대화하는데 있는 반면, 대부분의 최적화 프로그래밍은 목적함수를 최소화 하는 형태로 이루어집니다. 따라서 목적함수인 maxaDR을 최소화 형태로 바꿀 필요가 있으며 이는 세가지 방법이 있습니다.</p>
<ol style="list-style-type: decimal">
<li>Choueifaty Synthetic Asset Back-Transformation을 이용하는 방법<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a></li>
<li>Duality를 이용하는 방법<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a></li>
<li>Min (-)DR 방법</li>
</ol>
<p>먼저 Choueifaty Synthetic Asset Back-Transformation 방법은 목적함수 <span class="math inline">\(min\,w_s&#39;cw_s\)</span>와 제약조건 <span class="math inline">\(\sum_{i=1}^n w_i = 1, w_i \ge 0\)</span>을 만족하는 자산 별 비중을 구합니다. 그 후, 구해진 비중을 각각의 표준편차로 나누어 주며, 비중의 합이 1이 되도록 표준화를 해줍니다. 이 중 주의할 점은 목적함수의 c가 우리가 지금까지 사용하던 분산-공분산 행렬이 아닌, <strong>상관관계</strong> 행렬이라는 점입니다.</p>
<p>Duality 방법을 이용할 경우 목적함수는 최소분산 포트폴리오와 동일한 <span class="math inline">\(min^1/_2w&#39;\sigma w\)</span>이며, 제약조건만 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1, w_i \ge 0\)</span>, 즉 개별 자산의 비중이 0보다 크고 개별 표준편차의 가중합이 1인 조건으로 바뀝니다. 그 후, 비중의 합이 1이 되도록 표준화를 해줍니다.</p>
<p>기존 두 방법이 수학적 증명에 의해 <span class="math inline">\(maxDR\)</span>을 최소화의 형태로 풀어준 반면, 간단하게 목적함수를 <span class="math inline">\(min(-DR)\)</span>의 형태로 바꾸어 풀 수도 있습니다. 표 <a href="section-67.html#tab:solveqp">11.2</a>는 3가지 방법을 요약한 내용입니다.</p>
<table>
<caption><span id="tab:mdp">Table 11.8: </span>MDP 방법 비교</caption>
<thead>
<tr class="header">
<th align="left">방법</th>
<th align="left">목적함수</th>
<th align="left">제약조건</th>
<th align="left">표준화</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Transformation</td>
<td align="left"><span class="math inline">\(min\,w_s&#39;cw_s\)</span></td>
<td align="left"><span class="math inline">\(\sum_{i=1}^n w_i = 1\)</span> <br> <span class="math inline">\(w_i \ge 0\)</span></td>
<td align="left">비중을 각각의 표준편차로 나눈 후 <br>비중의 합으로 표준화</td>
</tr>
<tr class="even">
<td align="left">Duality</td>
<td align="left"><span class="math inline">\(min\,^1/_2w&#39;\sigma w\)</span></td>
<td align="left"><span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1\)</span><br> <span class="math inline">\(w_i \ge 0\)</span></td>
<td align="left">비중의 합으로 표준화</td>
</tr>
<tr class="odd">
<td align="left">-DR</td>
<td align="left">min(-DR)</td>
<td align="left"><span class="math inline">\(\sum_{i=1}^n w_i = 1\)</span> <br> <span class="math inline">\(w_i \ge0\)</span></td>
<td align="left">불필요</td>
</tr>
</tbody>
</table>
<div id="solve.qp----1" class="section level3">
<h3><span class="header-section-number">11.2.1</span> <code>solve.QP()</code> 함수를 이용한 최적화</h3>
<p>먼저 <code>solve.QP()</code> 함수를 이용하여 Duality 방법을 통해 최대분산효과 포트폴리오를 만족하는 해를 찾도록 하겠습니다.</p>
<p>Duality 방법에서 목적함수는 <span class="math inline">\(min\,^1/_2w&#39;\sigma w\)</span> 로 최소분산 포트폴리오와 동일하며, 제약조건은 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1, w_i \ge 0\)</span> 입니다. 제약조건 부분인 Amat과 bvec 부분을 입력할 때 이 부분을 고려하여 입력해야 합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">Dmat =<span class="st"> </span>covmat
dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)
Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(covmat)), <span class="kw">diag</span>(<span class="dv">10</span>)))
bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>))
meq =<span class="st"> </span><span class="dv">1</span></code></pre>
<p>제약조건에 해당하는 Amat 부분과 bvec 부분은 최소분산 포트폴리오와 다소 다릅니다. 표 <a href="section-67.html#tab:mvmdp">11.9</a>에는 둘 간에 코드가 어떻게 다른지 나타나 있습니다.</p>
<table>
<caption><span id="tab:mvmdp">Table 11.9: </span>Amat과 bvec 차이 비교</caption>
<thead>
<tr class="header">
<th align="left">인자</th>
<th align="left">최소분산 포트폴리오</th>
<th align="left">최대분산효과 포트폴리오</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Amat</td>
<td align="left">t(rbind(rep(1, 10), diag(10), -diag(10)))</td>
<td align="left">t(rbind(sqrt(diag(covmat)), diag(10)))</td>
</tr>
<tr class="even">
<td align="left">bvec</td>
<td align="left">c(1, rep(0, 10), -rep(1, 10))</td>
<td align="left">c(1, rep(0, 10))</td>
</tr>
</tbody>
</table>
<p>이해를 위해 Duality 방법의 제약조건을 행렬의 형태로 표현하면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix}
\sigma_1 &amp; \sigma_2 &amp; \dots &amp; \sigma_{10} \\ 1 &amp; 0 &amp; \dots &amp; 0 \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \dots &amp; 1 \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} = 
\begin{bmatrix} \sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10} \\ w_1 \\ \vdots \\ w_{10} \\
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \end{bmatrix} \]</span></p>
<p>1행의 <span class="math inline">\(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}\)</span> 부분은 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1\)</span>과 같으며, 해당 식은 등위제약조건으로써 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = \sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10} = 1\)</span>을 의미합니다. 2행부터 마지막 행까지는 모두 <span class="math inline">\(w_i \ge 0\)</span> 조건으로써, 개별 자산의 투자 비중이 0보다 큰 조건을 의미합니다.</p>
<p>행렬의 맨좌측에 해당하는 Amat 부분은 각 자산의 표준편차로 이루어진 벡터 행렬과, 1로 이루어진 대각행렬로 구성되어 있습니다. 먼저 <code>diag(covmat)</code>을 통해 분산-공분산 부분에서 대각부분 즉 분산 부분만을 추출할 수 있습니다. 개별 자산의 분산인 <span class="math inline">\(\sigma_{i,i}\)</span>의 경우 <span class="math inline">\(\sigma_i\sigma_i\rho_{1,1}\)</span> 형태로 쓸 수 있으며, <span class="math inline">\(\rho_{1,1} = 1\)</span>을 적용하면 <span class="math inline">\(\sigma_i^2\)</span>와 같습니다. 따라서 대각부분 값에 제곱근을 계산하는 <code>sqrt()</code> 함수를 적용하면 각각의 표준편차만 남게 됩니다. 이를 <code>diag(10)</code>을 통해 만든 대각행렬과 행으로 묶어준 후, 전치행렬을 입력해 줍니다.</p>
<p>bvec의 경우 행렬의 맨우측과 같이 등위제약조건에 해당하는 1과 부등위제약조건에 해당하는 0들로 구성되어 있습니다. 차후에 표준화 과정을 거쳐야 하므로 개별 자산의 투자 비중이 1보다 작은 조건은 Duality 방법에서는 입력하지 않아도 됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)

w =<span class="st"> </span>result<span class="op">$</span>solution <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))
  
<span class="kw">print</span>(w)</code></pre>
<pre><code>##     SPY     IEV     EWJ     EEM     TLT     IEF     IYR     RWX     GLD 
## 17.3779  2.3429  3.7611  0.0000 27.8116 36.2592  3.0243  0.0000  8.4122 
##     DBC 
## 11.6106</code></pre>
<p>입력된 목적함수와 제약조건들을 바탕으로 <code>solve.QP()</code>를 통해 최적화를 수행한 후, 최대분산효과를 만족하는 해를 구해보면, 비중의 합이 1을 초과하게 됩니다. <span class="math inline">\(w_i = \frac{w_i}{\sum_{i=1}^nw_i}\)</span> 를 통해 비중의 합이 1이 되도록 표준화를 해주도록 합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>)

<span class="kw">print</span>(w)</code></pre>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX    GLD    DBC 
## 0.1571 0.0212 0.0340 0.0000 0.2515 0.3278 0.0273 0.0000 0.0761 0.1050</code></pre>
<p>표준화 과정을 통해 비중의 합이 1이 되었음이 확인됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data.frame</span>(w) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),
                        <span class="dt">y =</span> w)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</code></pre>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-30-1.png" width="50%" style="display: block; margin: auto;" /></p>
</div>
<div id="optimalportfolio----1" class="section level3">
<h3><span class="header-section-number">11.2.2</span> <code>optimalPortfolio()</code> 함수를 이용한 최적화</h3>
<p>최소분산 포트폴리오와 동일하게 <code>optimalPortfolio()</code> 함수를 이용하여 매우 간단하게 최대분산효과 포트폴리오를 구현할 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">w =<span class="st"> </span><span class="kw">optimalPortfolio</span>(covmat, <span class="dt">control =</span> <span class="kw">list</span>(<span class="dt">type =</span> <span class="st">&#39;maxdiv&#39;</span>, <span class="dt">constraint =</span> <span class="st">&#39;lo&#39;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>)

<span class="kw">print</span>(w)</code></pre>
<pre><code>##  [1] 0.1571 0.0212 0.0340 0.0000 0.2515 0.3278 0.0273 0.0000 0.0761 0.1050</code></pre>
<p>control 항목의 type에 maximum diversification을 의미하는 ‘maxdiv’를 입력해주며, 제약조건에는 투자 비중이 0보다 큰 ‘lo’(long only) 조건을 입력해 줍니다. 패키지를 활용하여 매우 간단하게 최대분산효과 포트폴리오를 구현할 수 있으며, 그 결과값 또한 앞에서 계산한 것과 동일합니다. 해당 함수의 코드를 확인해보면, 최대분산효과 포트폴리오 계산시 -DR 방법 방법을 사용합니다.</p>
</div>
<div id="section-73" class="section level3">
<h3><span class="header-section-number">11.2.3</span> 최소 및 최대 투자비중 제약조건</h3>
<p>최대분산효과 포트폴리오 역시 구석해 문제가 발생하며, 모든 자산에 골고루 투자하기 위해 개별 투자비중을 최소 5%, 최대 20%로 하는 제약조건을 추가해 주도록 하겠습니다.</p>
<p>Duality 방법에서는 목적함수인 <span class="math inline">\(min\,^1/_2w&#39;\sigma w\)</span>과 제약조건인 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1, w_i \ge 0\)</span>에 맞게 해를 구한 후, 비중의 합이 1이 되도록 표준화하는 과정을 거쳤습니다. 따라서 비중의 최소 및 최대 제약조건은 단순히 <span class="math inline">\(lb \le w_i \le ub\)</span>가 아닌 표준화 과정인 <span class="math inline">\(w_i = \frac{w_i}{\sum_{i=1}^nw_i}\)</span>까지 고려하여 적용해 주어야 합니다. 표 <a href="section-67.html#tab:mdpconst">11.10</a>는 이를 수식으로 나타낸 것입니다.</p>
<table>
<caption><span id="tab:mdpconst">Table 11.10: </span>최소 및 최대비중 제약조건</caption>
<thead>
<tr class="header">
<th align="left">최소비중 제약조건</th>
<th align="left">최대비중 제약조건</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(\frac{w_i}{\sum_{i=1}^nw_i} \ge lb\)</span></td>
<td align="left"><span class="math inline">\(\frac{w_i}{\sum_{i=1}^nw_i} \le ub\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\Rightarrow -lb + \frac{w_i}{\sum_{i=1}^nw_i} \ge 0\)</span></td>
<td align="left"><span class="math inline">\(\Rightarrow ub - \frac{w_i}{\sum_{i=1}^nw_i} \ge 0\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\Rightarrow -lb + \frac{w_i}{e^Tw} \ge 0\)</span></td>
<td align="left"><span class="math inline">\(\Rightarrow ub - \frac{w_i}{e^Tw} \ge 0\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\Rightarrow -lb \times e^Tw + w \ge 0\)</span></td>
<td align="left"><span class="math inline">\(\Rightarrow ub \times e^Tw - w \ge 0\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\Rightarrow (-lb \times e^T + I)w \ge 0\)</span></td>
<td align="left"><span class="math inline">\(\Rightarrow (ub \times e^T - I)w \ge 0\)</span></td>
</tr>
</tbody>
</table>
<p>최소 비중 제약조건인 <span class="math inline">\(-lb \times e^T + I\)</span>의 예를 행렬로 풀어보도록 하겠습니다. <span class="math inline">\(-lb \times e^T\)</span>의 경우 행렬로 표현할 경우 다음과 같으며, -lb로 이루어진 <span class="math inline">\(n \times n\)</span> 행렬입니다.</p>
<p><span class="math display">\[ \begin{bmatrix} -lb \\ \vdots \\ -lb \end{bmatrix}
\begin{bmatrix} 1 \\ \vdots \\ 1 \end{bmatrix}^T 
= \begin{bmatrix} -lb \\ \vdots \\ -lb \end{bmatrix}
\begin{bmatrix} 1 &amp; \dots &amp; 1 \end{bmatrix}  
= \begin{bmatrix} -lb &amp; \dots &amp; -lb \\ \vdots &amp; \ddots &amp; \vdots \\ -lb &amp; \dots &amp; -lb \end{bmatrix}\]</span></p>
<p><span class="math inline">\(I\)</span>는 대각선 부분이 1, 나머지가 0인 항등행렬을 의미합니다. 따라서 <span class="math inline">\((-lb \times e^T + I)\)</span>를 계산하면 다음과 같습니다.</p>
<p><span class="math display">\[\begin{bmatrix} -lb  + 1 &amp; \dots &amp; -lb \\ \vdots &amp; \ddots &amp; \vdots \\ -lb &amp; \dots &amp; -lb + 1 \end{bmatrix}\]</span></p>
<p>최소분산 포트폴리오와는 다르게 Duality 방법으로 최대분산효과 포트폴리오를 구현할 경우 최소 및 최대 제약조건이 우변이 아닌 좌변에 들어가게 되며, 해당 제약조건을 고려하여 행렬로 표현하면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix}
\sigma_1 &amp; \dots &amp; \sigma_{10} \\ -lb + 1 &amp; \dots &amp; -lb \\ \vdots &amp; \ddots &amp; \vdots \\
-lb &amp; \dots &amp; -lb + 1 \\ ub-1 &amp; \dots &amp;  ub \\ \vdots &amp; \ddots &amp; \vdots \\ ub &amp; \dots &amp; ub-1 \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} = 
\begin{bmatrix} \sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10} \\ -lb(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}) + w_1 \\ \vdots \\ -lb(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}) + w_{10} \\
wb(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}) - w_1 \\ \vdots \\
ub(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}) - w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix} \]</span></p>
<p>첫번째 행 <span class="math inline">\(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}\)</span>은 등위 제약조건인 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1\)</span>에 해당하며, 두번째 행부터는 부등위 제약조건에 해당합니다. 두번째 행을 정리하면 <span class="math inline">\(\frac{w_1}{w_1+w_2+\dots+w_{10}} \ge lb\)</span>, 즉 비중의 표준화가 고려된 최소비중 지약조건입니다. 마지막 행 역시 정리하면 <span class="math inline">\(\frac{w_1}{w_1+w_2+\dots+w_{10}} \le ub\)</span>가 되어 비중의 표준화가 고려된 최대비중 제약조건을 의미합니다. 위 행렬을 고려하여 Amat과 bvec을 수정한 코드는 다음과 같습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">Dmat =<span class="st"> </span>covmat
dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)
Alb =<span class="st"> </span><span class="op">-</span><span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>) <span class="op">%*%</span><span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">+</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)
Aub =<span class="st"> </span><span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>) <span class="op">%*%</span><span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">-</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)

Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(covmat)), Alb, Aub))
bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>))
meq =<span class="st"> </span><span class="dv">1</span>

result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)

w =<span class="st"> </span>result<span class="op">$</span>solution 
w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))
  
<span class="kw">print</span>(w)</code></pre>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX    GLD    DBC 
## 0.0500 0.0500 0.0500 0.0500 0.2000 0.2000 0.0500 0.0500 0.1928 0.1072</code></pre>
<p>Alb의 -rep(0.05, 10)는 -lb 부분, matrix(1, 1, 10)은 <span class="math inline">\(e^T\)</span> 부분, diag(10)부분은 <span class="math inline">\(I\)</span> 부분을 의미하며, 이는 최소비중 제약조건의 좌변부분(<span class="math inline">\(-lb \times e^T + I\)</span>)과 같습니다. 동일하게 Aub는 최대비중 제약조건의 좌변부분(<span class="math inline">\(ub \times e^T - I\)</span>)과 같으며, 결과를 확인하면 최소 및 최대비중 제약조건인 [5%, 20%]가 제대로 반영되었음이 확인됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data.frame</span>(w) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),
                        <span class="dt">y =</span> w)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.05</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.20</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</code></pre>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
</div>
<div id="section-74" class="section level3">
<h3><span class="header-section-number">11.2.4</span> 각 자산 별 제약조건의 추가</h3>
<p>최소분산 포트폴리오의 경우와 동일하게 자산 별로 다른 제약조건을 추가하여 포트폴리오를 구성하도록 하겠습니다. 아래 표는 각 자산 별 최소 및 최대 투자비중 값과, 변경된 제약조건을 행렬의 형태로 나타낸 것입니다. 주의해야 할 점은 최소비중과 최대비중의 제약조건 추가 시, <span class="math inline">\(\frac{w_1}{w_1+w_2+\dots+w_{10}} \ge lb\)</span> 형태로 고려해 주어야 한다는 점입니다.</p>
<table>
<caption><span id="tab:unnamed-chunk-34">Table 11.11: </span>각 자산 별 최소 및 최대 제약조건</caption>
<thead>
<tr class="header">
<th align="left">제약</th>
<th align="left">1</th>
<th align="left">2</th>
<th align="left">3</th>
<th align="left">4</th>
<th align="left">5</th>
<th align="left">6</th>
<th align="left">7</th>
<th align="left">8</th>
<th align="left">9</th>
<th align="left">10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">최소</td>
<td align="left">0.10</td>
<td align="left">0.10</td>
<td align="left">0.05</td>
<td align="left">0.05</td>
<td align="left">0.10</td>
<td align="left">0.10</td>
<td align="left">0.05</td>
<td align="left">0.05</td>
<td align="left">0.03</td>
<td align="left">0.03</td>
</tr>
<tr class="even">
<td align="left">최대</td>
<td align="left">0.25</td>
<td align="left">0.25</td>
<td align="left">0.20</td>
<td align="left">0.20</td>
<td align="left">0.20</td>
<td align="left">0.20</td>
<td align="left">0.10</td>
<td align="left">0.10</td>
<td align="left">0.08</td>
<td align="left">0.08</td>
</tr>
</tbody>
</table>
<p>기존에 공통적으로 적용되던 최소 및 최대 투자비중이 자산 별로 다르게 구성되었습니다. 따라서 <span class="math inline">\(-lb \times e^T + I\)</span>와 <span class="math inline">\(ub \times e^T - I\)</span>부분만 <span class="math inline">\(-lb_i \times e^T + I\)</span> <span class="math inline">\(ub_i \times e^T - I\)</span>로 수정하면 해당 제약조건 역시 손쉽게 구현이 가능합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">Dmat =<span class="st"> </span>covmat
dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)
Alb =<span class="st"> </span><span class="op">-</span><span class="kw">c</span>(<span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.03</span>, <span class="fl">0.03</span>) <span class="op">%*%</span><span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">+</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)
Aub =<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.08</span>, <span class="fl">0.08</span>) <span class="op">%*%</span><span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">-</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)

Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(covmat)), Alb, Aub))
bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>))
meq =<span class="st"> </span><span class="dv">1</span>

result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)

w =<span class="st"> </span>result<span class="op">$</span>solution 
w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))
  
<span class="kw">print</span>(w)</code></pre>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.10 0.10 0.09 0.05 0.20 0.20 0.05 0.05 0.08 0.08</code></pre>
<p>최소 및 최대투자비중 제약조건을 나타내는 Alb와 Aub 부분이 자산 별 각각의 제약비중으로 변경되었으며, 나머지 부분은 모두 동일합니다. 결과 값들이 모두 최소 및 최대 투자비중 제약조건 내에 위치함을 확인할 수 있습니다.</p>
</div>
</div>
<div id="section-75" class="section level2">
<h2><span class="header-section-number">11.3</span> 위험균형 포트폴리오</h2>
<p>포트폴리오를 구성하는 자산들과 전체 위험의 관계를 이해하기 위해서는, 먼저 한계 위험기여도(MRC: Marginal Risk Contribution)와 위험기여도(RC: Risk Contribution)에 대해 알아야 합니다. 한계 위험기여도는 특정 자산의 비중을 한 단위 증가시켰을 때 전체 포트폴리오의 위험의 증가를 나타내는 단위로써, 수학의 편미분과 같은 개념입니다. i번째 자산의 한계 위험기여도는 아래와 같이 나타낼 수 있습니다.</p>
<p><span class="math display">\[MRC_i = \frac{\partial\sigma_p}{\partial w_i} \]</span></p>
<p><span class="math inline">\(\sqrt {f&#39;(x)} = \frac{f&#39;(x)}{2\sqrt{f(x)}}\)</span>인 사실을 이용하면, 한계 위험기여도는 아래와 같이 풀 수 있습니다. 결과적으로 분자는 분산-공분산 행렬과 각 자산의 비중의 곱, 분모는 포트폴리오의 표준편차 형태로 나타납니다.</p>
<p><span class="math display">\[\begin{equation} 
\begin{split}
\frac{\partial\sigma_p}{\partial w} &amp; = \frac{\partial(\sqrt{w&#39;\Omega w})}{\partial w} \\
&amp; =\frac{\partial(w&#39;\Omega w)}{\partial w} \times \frac{1}{2\sqrt{w&#39;\Omega w}} \\
&amp; =\frac{2\Omega w}{2\sqrt{w&#39;\Omega w}} \\
&amp; =\frac{\Omega w}{\sqrt{w&#39;\Omega w}}
\end{split}
\end{equation}\]</span></p>
<p>위험기여도는 특정 자산이 포트폴리오 내에서 차지하는 위험의 비중입니다. 한계 위험기여도가 큰 자산도 포트폴리오 내에서 비중이 작다면, 포트폴리오 내에서 차지하는 위험의 비중은 작을 것입니다. 반면에, 한계 위험기여도가 작은 자산일지라도 비중이 압도적으로 많다면, 포트폴리오 내에서 차지하는 위험의 비중은 클 것입니다.</p>
<p>결과적으로 <span class="math inline">\(i\)</span>번째 자산의 위험기여도는, <span class="math inline">\(i\)</span>번째 자산의 한계 위험기여도와 포트폴리오 내 비중의 곱으로 이루어집니다.</p>
<p><span class="math display">\[RC_i = \frac{\partial\sigma_p}{\partial w_i} \times w_i\]</span>
위험기여도를 코드로 나타내면 다음과 같습니다. 먼저 포트폴리오 비중인 w와 분산-공분산 행렬인 covmat을 이용하여 한계 위험기여도를 계산하여 줍니다. 그 후, 비중 w를 곱하여 위험기여도를 계산해 준 후, 합계가 1이 되도록 표준화를 해줍니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">get_RC =<span class="st"> </span><span class="cf">function</span>(w, covmat) {
  port_vol =<span class="st"> </span><span class="kw">t</span>(w) <span class="op">%*%</span><span class="st"> </span>covmat <span class="op">%*%</span><span class="st"> </span>w
  port_std =<span class="st"> </span><span class="kw">sqrt</span>(port_vol)
  
  MRC =<span class="st"> </span>(covmat <span class="op">%*%</span><span class="st"> </span>w) <span class="op">/</span><span class="st"> </span><span class="kw">as.numeric</span>(port_std)
  RC =<span class="st"> </span>MRC <span class="op">*</span><span class="st"> </span>w
  RC =<span class="st"> </span><span class="kw">c</span>(RC <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(RC))
  
  <span class="kw">return</span>(RC)
}</code></pre>
<div id="section-76" class="section level3">
<h3><span class="header-section-number">11.3.1</span> 전통적 자산배분, 주식 60%와 채권 40%</h3>
<p>자산배분에서 가장 많이 사용되는 투자방법은 주식에 60%, 채권에 40% 가량의 비율로 투자하는 것입니다. 주식과 채권이 서로 상관관계가 낮아 분산효과가 있다는 점, 장기적으로 주식이 채권에 비해 장기적으로 수익률이 높다는 점을 감안하면 이는 꽤나 합리적인 방법으로 보입니다.</p>
<p>그러나 눈에 보이는 비중은 60대 40의 형태일지라도, 포트폴리오 내에서 각 자산이 가지고 있는 위험기여도 60대 40의 비중이 아닌 전혀 다른 비중을 가지고 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r">ret_stock_bond =<span class="st"> </span>rets[, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>)]
cov_stock_bond =<span class="st"> </span><span class="kw">cov</span>(ret_stock_bond)
RC_stock_bond =<span class="st"> </span><span class="kw">get_RC</span>(<span class="kw">c</span>(<span class="fl">0.6</span>, <span class="fl">0.4</span>), cov_stock_bond)
RC_stock_bond =<span class="st"> </span><span class="kw">round</span>(RC_stock_bond, <span class="dv">4</span>)

<span class="kw">print</span>(RC_stock_bond)</code></pre>
<pre><code>## [1] 0.97 0.03</code></pre>
<p>rets 데이터에서 첫번째 행은 미국 주식 수익률을, 다섯번째 행은 미국 장기채를 의미하므로, 해당 부분을 ret_stock_bond 변수에 지정합니다. 그 후 <code>cov()</code> 함수를 이용해 두 자산의 분산-공분산 행렬을 만들어 주며, 위에서 만든 get_RC 함수를 통해 자산 별 위험기여도를 계산하도록 합니다.</p>
<p>주식과 채권이 가지는 위험기여도는 각각 97%, 3%로써 투자 비중인 60%, 40% 와는 전혀 다른 위험 비중을 보입니다. 즉, 주식이 포트폴리오 위험의 대부분을 차지하는 모습을 보입니다.</p>
</div>
<div id="rp---" class="section level3">
<h3><span class="header-section-number">11.3.2</span> <code>rp()</code> 함수를 이용한 최적화</h3>
<p>위 예제와 같이 특정 자산이 포트폴리오의 위험을 대부분 차지하는 문제를 막고, 모든 자산이 동일한 위험기여도를 가지는 포트폴리오가 위험균형 포트폴리오(Risk Parity Portfolio) 혹은 동일 위험기여도 포트폴리오(Equal Risk Contribution Portfolio) 입니다. 이를 수식으로 쓰면 다음과 같습니다.</p>
<p><span class="math display">\[RC_1 = RC_2 = \dots = RC_n \\
\frac{\partial\sigma_p}{\partial w_1} \times w_1 = \frac{\partial\sigma_p}{\partial w_2} \times w_2
= \dots = \frac{\partial\sigma_p}{\partial w_n} \times w_n = \frac{1}{n}\]</span></p>
<p>위험균형 포트폴리오 역시 <code>slsqp()</code>나 <code>optimalPortfolio()</code> 함수를 이용하여 구현할 수 있으나, 간혹 최적화된 값을 찾지 못할때도 있습니다. 반면 <code>cccp</code> 패키지의 <code>rp()</code> 함수를 사용하면 매우 정확하게 위험균형 포트폴리오를 구성하는 비중을 계산할 수 있습니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(cccp)

opt =<span class="st"> </span><span class="kw">rp</span>(<span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),
         <span class="dt">P =</span> covmat,
         <span class="dt">mrc =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>))</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">w =<span class="st"> </span><span class="kw">getx</span>(opt) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop</span>()
w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w)</code></pre>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX    GLD    DBC 
## 0.0621 0.0469 0.0555 0.0360 0.1811 0.3654 0.0396 0.0514 0.0867 0.0753</code></pre>
<ol style="list-style-type: decimal">
<li>x0은 최적화를 위한 초기 입력값이며 동일비중인 10%씩을 입력해 줍니다.</li>
<li>P는 분산-공분산 행렬을 입력해줍니다.</li>
<li>mrc는 목표로 하는 각 자산 별 위험기여도 값<a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a>이며, 위험균형 포트폴리오의 경우 모든 자산의 위험기여도가 동일해야하므로 10%씩을 입력해 줍니다.</li>
</ol>
<p><code>rp()</code> 함수는 위 입력변수를 바탕으로 최적화를 만족하는 해를 찾아줍니다. <code>getx()</code> 함수를 통해 해를 추출할 수 있으며, <code>drop()</code>을 통해 벡터 형태로 변환해줍니다. 마지막으로 비중의 합이 1이 되기 위해 비중들의 합으로 나눠주도록 합니다.</p>
<p>최종적으로 계싼된 비중이 위험균형 포트폴리오를 만족하는 해가 됩니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_RC</span>(w, covmat)</code></pre>
<pre><code>##  [1] 0.09994352 0.09995531 0.10000193 0.10008569 0.10000014 0.09998490
##  [7] 0.10002759 0.10007123 0.10001596 0.09991373</code></pre>
<p><code>get_RC()</code> 함수를 통해 위험기여도를 확인해보면, 모든 자산이 거의 동일한 위험기여도를 가지는 것이 확인됩니다.</p>
</div>
<div id="section-77" class="section level3">
<h3><span class="header-section-number">11.3.3</span> 위험예산 포트폴리오</h3>
<p>모든 자산의 위험기여도가 동일한 값이 아닌, 자산 별로 다른 위험기여도를 가져가는 포트폴리오를 구성해야 할 경우도 있습니다. 이러한 포트폴리오를 위험예산 포트폴리오(Risk Budget Portfolio)라 합니다. 위험균형 포트폴리오 역시 각 자산의 위험예산이 <span class="math inline">\(^1⁄_n\)</span>로 동일한 특수 형태이며, <code>rp()</code> 함수를 이용하면 원하는 위험예산 포트폴리오 역시 손쉽게 구현할 수 있습니다.</p>
<p>먼저 각 자산 별 위험예산을 표 <a href="section-67.html#tab:rb">11.12</a>와 같이 정합니다. 1~4번 자산은 각각 15%씩, 5~6번 자산은 각각 10%씩, 7~10번 자산은 각각 5%씩 위험예산을 부여하고자 합니다.</p>
<table>
<caption><span id="tab:rb">Table 11.12: </span>위험예산 포트폴리오 예시</caption>
<thead>
<tr class="header">
<th align="left">자산</th>
<th align="left">1</th>
<th align="left">2</th>
<th align="left">3</th>
<th align="left">4</th>
<th align="left">5</th>
<th align="left">6</th>
<th align="left">7</th>
<th align="left">8</th>
<th align="left">9</th>
<th align="left">10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">예산</td>
<td align="left">0.15</td>
<td align="left">0.15</td>
<td align="left">0.15</td>
<td align="left">0.15</td>
<td align="left">0.1</td>
<td align="left">0.1</td>
<td align="left">0.05</td>
<td align="left">0.05</td>
<td align="left">0.05</td>
<td align="left">0.05</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(cccp)

opt =<span class="st"> </span><span class="kw">rp</span>(<span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),
         <span class="dt">P =</span> covmat,
         <span class="dt">mrc =</span> <span class="kw">c</span>(<span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>))</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">w =<span class="st"> </span><span class="kw">getx</span>(opt) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop</span>()
w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))

<span class="kw">print</span>(w)</code></pre>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX    GLD    DBC 
## 0.0873 0.0670 0.0768 0.0514 0.1884 0.3857 0.0198 0.0254 0.0547 0.0434</code></pre>
<p>mrc에 목표로 하는 각 자산 별 위험기여도를 입력하며, 나머지는 기존 위험균형 포트폴리오와 동일하게 입력합니다.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_RC</span>(w, covmat)</code></pre>
<pre><code>##  [1] 0.15006760 0.14999864 0.15008967 0.14987577 0.09993798 0.09995499
##  [7] 0.05006674 0.05010484 0.04996138 0.04994238</code></pre>
<p><code>get_RC()</code> 함수를 통해 위험기여도를 확인해보면, 우리가 원하던 자산 별 위험예산과 거의 동일함이 확인됩니다.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="21">
<li id="fn21"><p>Choueifaty, Y., &amp; Coignard, Y. (2008). Toward maximum diversification. Journal of Portfolio Management, 35(1), 40.<a href="section-67.html#fnref21" class="footnote-back">↩</a></p></li>
<li id="fn22"><p>Choueifaty, Y., Froidure, T., &amp; Reynier, J. (2011). Properties of the most diversified portfolio.<a href="section-67.html#fnref22" class="footnote-back">↩</a></p></li>
<li id="fn23"><p>엄밀하게는 mrc가 아닌 rc가 맞는 용어입니다.<a href="section-67.html#fnref23" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="section-58.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="section-78.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
