<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 포트폴리오 구성 | R을 이용한 퀀트 투자 포트폴리오 만들기</title>
  <meta name="description" content="Chapter 11 포트폴리오 구성 | R을 이용한 퀀트 투자 포트폴리오 만들기" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 포트폴리오 구성 | R을 이용한 퀀트 투자 포트폴리오 만들기" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="hyunyulhenry/quant_cookbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 포트폴리오 구성 | R을 이용한 퀀트 투자 포트폴리오 만들기" />
  
  
  

<meta name="author" content="이현열" />


<meta name="date" content="2020-12-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="퀀트-전략을-이용한-종목선정-심화.html"/>
<link rel="next" href="포트폴리오-백테스트.html"/>
<script src="libs/jquery-3.5.0/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<script src="libs/proj4js-2.3.15/proj4.js"></script>
<link href="libs/highcharts-8.1.2/css/motion.css" rel="stylesheet" />
<script src="libs/highcharts-8.1.2/highcharts.js"></script>
<script src="libs/highcharts-8.1.2/highcharts-3d.js"></script>
<script src="libs/highcharts-8.1.2/highcharts-more.js"></script>
<script src="libs/highcharts-8.1.2/modules/stock.js"></script>
<script src="libs/highcharts-8.1.2/modules/map.js"></script>
<script src="libs/highcharts-8.1.2/modules/annotations.js"></script>
<script src="libs/highcharts-8.1.2/modules/data.js"></script>
<script src="libs/highcharts-8.1.2/modules/drilldown.js"></script>
<script src="libs/highcharts-8.1.2/modules/item-series.js"></script>
<script src="libs/highcharts-8.1.2/modules/offline-exporting.js"></script>
<script src="libs/highcharts-8.1.2/modules/overlapping-datalabels.js"></script>
<script src="libs/highcharts-8.1.2/modules/exporting.js"></script>
<script src="libs/highcharts-8.1.2/modules/export-data.js"></script>
<script src="libs/highcharts-8.1.2/modules/funnel.js"></script>
<script src="libs/highcharts-8.1.2/modules/heatmap.js"></script>
<script src="libs/highcharts-8.1.2/modules/treemap.js"></script>
<script src="libs/highcharts-8.1.2/modules/sankey.js"></script>
<script src="libs/highcharts-8.1.2/modules/dependency-wheel.js"></script>
<script src="libs/highcharts-8.1.2/modules/organization.js"></script>
<script src="libs/highcharts-8.1.2/modules/solid-gauge.js"></script>
<script src="libs/highcharts-8.1.2/modules/streamgraph.js"></script>
<script src="libs/highcharts-8.1.2/modules/sunburst.js"></script>
<script src="libs/highcharts-8.1.2/modules/vector.js"></script>
<script src="libs/highcharts-8.1.2/modules/wordcloud.js"></script>
<script src="libs/highcharts-8.1.2/modules/xrange.js"></script>
<script src="libs/highcharts-8.1.2/modules/tilemap.js"></script>
<script src="libs/highcharts-8.1.2/modules/venn.js"></script>
<script src="libs/highcharts-8.1.2/modules/gantt.js"></script>
<script src="libs/highcharts-8.1.2/modules/timeline.js"></script>
<script src="libs/highcharts-8.1.2/modules/parallel-coordinates.js"></script>
<script src="libs/highcharts-8.1.2/modules/bullet.js"></script>
<script src="libs/highcharts-8.1.2/modules/coloraxis.js"></script>
<script src="libs/highcharts-8.1.2/modules/dumbbell.js"></script>
<script src="libs/highcharts-8.1.2/modules/lollipop.js"></script>
<script src="libs/highcharts-8.1.2/modules/series-label.js"></script>
<script src="libs/highcharts-8.1.2/plugins/motion.js"></script>
<script src="libs/highcharts-8.1.2/custom/reset.js"></script>
<script src="libs/highcharts-8.1.2/modules/boost.js"></script>
<script src="libs/highchart-binding-0.8.2/highchart.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R을 이용한 퀀트 투자 포트폴리오 만들기</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#지은이-소개"><i class="fa fa-check"></i>지은이 소개</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#머리말"><i class="fa fa-check"></i>머리말</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#이-책의-구성"><i class="fa fa-check"></i>이 책의 구성</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#이-책에서-다루지-않은-주제"><i class="fa fa-check"></i>이 책에서 다루지 않은 주제</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#도움이-될-만한-자료들"><i class="fa fa-check"></i>도움이 될 만한 자료들</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#이-책의-지원-페이지"><i class="fa fa-check"></i>이 책의 지원 페이지</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#종목과-관련된-유의사항"><i class="fa fa-check"></i>종목과 관련된 유의사항</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#세션정보"><i class="fa fa-check"></i>세션정보</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="퀀트-투자의-심장-데이터와-프로그래밍.html"><a href="퀀트-투자의-심장-데이터와-프로그래밍.html"><i class="fa fa-check"></i><b>1</b> 퀀트 투자의 심장: 데이터와 프로그래밍</a><ul>
<li class="chapter" data-level="1.1" data-path="퀀트-투자의-심장-데이터와-프로그래밍.html"><a href="퀀트-투자의-심장-데이터와-프로그래밍.html#데이터-구하기"><i class="fa fa-check"></i><b>1.1</b> 데이터 구하기</a></li>
<li class="chapter" data-level="1.2" data-path="퀀트-투자의-심장-데이터와-프로그래밍.html"><a href="퀀트-투자의-심장-데이터와-프로그래밍.html#퀀트-투자와-프로그래밍"><i class="fa fa-check"></i><b>1.2</b> 퀀트 투자와 프로그래밍</a></li>
<li class="chapter" data-level="1.3" data-path="퀀트-투자의-심장-데이터와-프로그래밍.html"><a href="퀀트-투자의-심장-데이터와-프로그래밍.html#r-프로그램"><i class="fa fa-check"></i><b>1.3</b> R 프로그램</a></li>
<li class="chapter" data-level="1.4" data-path="퀀트-투자의-심장-데이터와-프로그래밍.html"><a href="퀀트-투자의-심장-데이터와-프로그래밍.html#퀀트-투자에-유용한-r-패키지"><i class="fa fa-check"></i><b>1.4</b> 퀀트 투자에 유용한 R 패키지</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html"><i class="fa fa-check"></i><b>2</b> 크롤링을 위한 기본 지식</a><ul>
<li class="chapter" data-level="2.1" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#인코딩의-이해와-r에서-utf-8-설정하기"><i class="fa fa-check"></i><b>2.1</b> 인코딩의 이해와 R에서 UTF-8 설정하기</a><ul>
<li class="chapter" data-level="2.1.1" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#인간과-컴퓨터-간-번역의-시작-ascii"><i class="fa fa-check"></i><b>2.1.1</b> 인간과 컴퓨터 간 번역의 시작, ASCII</a></li>
<li class="chapter" data-level="2.1.2" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#한글-인코딩-방식의-종류"><i class="fa fa-check"></i><b>2.1.2</b> 한글 인코딩 방식의 종류</a></li>
<li class="chapter" data-level="2.1.3" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#r에서-utf-8-설정하기"><i class="fa fa-check"></i><b>2.1.3</b> R에서 UTF-8 설정하기</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#웹의-동작-방식"><i class="fa fa-check"></i><b>2.2</b> 웹의 동작 방식</a><ul>
<li class="chapter" data-level="2.2.1" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#http"><i class="fa fa-check"></i><b>2.2.1</b> HTTP</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#html과-css"><i class="fa fa-check"></i><b>2.3</b> HTML과 CSS</a><ul>
<li class="chapter" data-level="2.3.1" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#html-기본-구조"><i class="fa fa-check"></i><b>2.3.1</b> HTML 기본 구조</a></li>
<li class="chapter" data-level="2.3.2" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#태그와-속성"><i class="fa fa-check"></i><b>2.3.2</b> 태그와 속성</a></li>
<li class="chapter" data-level="2.3.3" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#h-태그와-p-태그"><i class="fa fa-check"></i><b>2.3.3</b> h 태그와 p 태그</a></li>
<li class="chapter" data-level="2.3.4" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#리스트를-나타내는-ul-태그와-ol-태그"><i class="fa fa-check"></i><b>2.3.4</b> 리스트를 나타내는 ul 태그와 ol 태그</a></li>
<li class="chapter" data-level="2.3.5" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#table-태그"><i class="fa fa-check"></i><b>2.3.5</b> table 태그</a></li>
<li class="chapter" data-level="2.3.6" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#a-태그와-src-태그-및-속성"><i class="fa fa-check"></i><b>2.3.6</b> a 태그와 src 태그 및 속성</a></li>
<li class="chapter" data-level="2.3.7" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#div-태그"><i class="fa fa-check"></i><b>2.3.7</b> div 태그</a></li>
<li class="chapter" data-level="2.3.8" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#css"><i class="fa fa-check"></i><b>2.3.8</b> CSS</a></li>
<li class="chapter" data-level="2.3.9" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#클래스와-id"><i class="fa fa-check"></i><b>2.3.9</b> 클래스와 id</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#파이프-오퍼레이터"><i class="fa fa-check"></i><b>2.4</b> 파이프 오퍼레이터(<code>%&gt;%</code>)</a></li>
<li class="chapter" data-level="2.5" data-path="크롤링을-위한-기본-지식.html"><a href="크롤링을-위한-기본-지식.html#오류에-대한-예외처리"><i class="fa fa-check"></i><b>2.5</b> 오류에 대한 예외처리</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="api를-이용한-데이터-수집.html"><a href="api를-이용한-데이터-수집.html"><i class="fa fa-check"></i><b>3</b> API를 이용한 데이터 수집</a><ul>
<li class="chapter" data-level="3.1" data-path="api를-이용한-데이터-수집.html"><a href="api를-이용한-데이터-수집.html#api를-이용한-quandl-데이터-다운로드"><i class="fa fa-check"></i><b>3.1</b> API를 이용한 Quandl 데이터 다운로드</a></li>
<li class="chapter" data-level="3.2" data-path="api를-이용한-데이터-수집.html"><a href="api를-이용한-데이터-수집.html#getsymbols-함수를-이용한-api-다운로드"><i class="fa fa-check"></i><b>3.2</b> <code>getSymbols()</code> 함수를 이용한 API 다운로드</a><ul>
<li class="chapter" data-level="3.2.1" data-path="api를-이용한-데이터-수집.html"><a href="api를-이용한-데이터-수집.html#주가-다운로드"><i class="fa fa-check"></i><b>3.2.1</b> 주가 다운로드</a></li>
<li class="chapter" data-level="3.2.2" data-path="api를-이용한-데이터-수집.html"><a href="api를-이용한-데이터-수집.html#국내-종목-주가-다운로드"><i class="fa fa-check"></i><b>3.2.2</b> 국내 종목 주가 다운로드</a></li>
<li class="chapter" data-level="3.2.3" data-path="api를-이용한-데이터-수집.html"><a href="api를-이용한-데이터-수집.html#fred-데이터-다운로드"><i class="fa fa-check"></i><b>3.2.3</b> FRED 데이터 다운로드</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html"><i class="fa fa-check"></i><b>4</b> 크롤링 이해하기</a><ul>
<li class="chapter" data-level="4.1" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html#get과-post-방식-이해하기"><i class="fa fa-check"></i><b>4.1</b> GET과 POST 방식 이해하기</a><ul>
<li class="chapter" data-level="4.1.1" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html#get-방식"><i class="fa fa-check"></i><b>4.1.1</b> GET 방식</a></li>
<li class="chapter" data-level="4.1.2" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html#post-방식"><i class="fa fa-check"></i><b>4.1.2</b> POST 방식</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html#크롤링-예제"><i class="fa fa-check"></i><b>4.2</b> 크롤링 예제</a><ul>
<li class="chapter" data-level="4.2.1" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html#금융-속보-크롤링"><i class="fa fa-check"></i><b>4.2.1</b> 금융 속보 크롤링</a></li>
<li class="chapter" data-level="4.2.2" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html#기업공시채널에서-오늘의-공시-불러오기"><i class="fa fa-check"></i><b>4.2.2</b> 기업공시채널에서 오늘의 공시 불러오기</a></li>
<li class="chapter" data-level="4.2.3" data-path="크롤링-이해하기.html"><a href="크롤링-이해하기.html#네이버-금융에서-주식티커-크롤링"><i class="fa fa-check"></i><b>4.2.3</b> 네이버 금융에서 주식티커 크롤링</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="금융-데이터-수집하기-기본.html"><a href="금융-데이터-수집하기-기본.html"><i class="fa fa-check"></i><b>5</b> 금융 데이터 수집하기 (기본)</a><ul>
<li class="chapter" data-level="5.1" data-path="금융-데이터-수집하기-기본.html"><a href="금융-데이터-수집하기-기본.html#한국거래소의-산업별-현황-및-개별지표-크롤링"><i class="fa fa-check"></i><b>5.1</b> 한국거래소의 산업별 현황 및 개별지표 크롤링</a><ul>
<li class="chapter" data-level="5.1.1" data-path="금융-데이터-수집하기-기본.html"><a href="금융-데이터-수집하기-기본.html#산업별-현황-크롤링"><i class="fa fa-check"></i><b>5.1.1</b> 산업별 현황 크롤링</a></li>
<li class="chapter" data-level="5.1.2" data-path="금융-데이터-수집하기-기본.html"><a href="금융-데이터-수집하기-기본.html#개별종목-지표-크롤링"><i class="fa fa-check"></i><b>5.1.2</b> 개별종목 지표 크롤링</a></li>
<li class="chapter" data-level="5.1.3" data-path="금융-데이터-수집하기-기본.html"><a href="금융-데이터-수집하기-기본.html#최근-영업일-기준-데이터-받기"><i class="fa fa-check"></i><b>5.1.3</b> 최근 영업일 기준 데이터 받기</a></li>
<li class="chapter" data-level="5.1.4" data-path="금융-데이터-수집하기-기본.html"><a href="금융-데이터-수집하기-기본.html#거래소-데이터-정리하기"><i class="fa fa-check"></i><b>5.1.4</b> 거래소 데이터 정리하기</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="금융-데이터-수집하기-기본.html"><a href="금융-데이터-수집하기-기본.html#wics-기준-섹터정보-크롤링"><i class="fa fa-check"></i><b>5.2</b> WICS 기준 섹터정보 크롤링</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html"><i class="fa fa-check"></i><b>6</b> 금융 데이터 수집하기 (심화)</a><ul>
<li class="chapter" data-level="6.1" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#수정주가-크롤링"><i class="fa fa-check"></i><b>6.1</b> 수정주가 크롤링</a><ul>
<li class="chapter" data-level="6.1.1" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#개별종목-주가-크롤링"><i class="fa fa-check"></i><b>6.1.1</b> 개별종목 주가 크롤링</a></li>
<li class="chapter" data-level="6.1.2" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#전-종목-주가-크롤링"><i class="fa fa-check"></i><b>6.1.2</b> 전 종목 주가 크롤링</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#재무제표-및-가치지표-크롤링"><i class="fa fa-check"></i><b>6.2</b> 재무제표 및 가치지표 크롤링</a><ul>
<li class="chapter" data-level="6.2.1" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#재무제표-다운로드"><i class="fa fa-check"></i><b>6.2.1</b> 재무제표 다운로드</a></li>
<li class="chapter" data-level="6.2.2" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#가치지표-계산하기"><i class="fa fa-check"></i><b>6.2.2</b> 가치지표 계산하기</a></li>
<li class="chapter" data-level="6.2.3" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#전-종목-재무제표-및-가치지표-다운로드"><i class="fa fa-check"></i><b>6.2.3</b> 전 종목 재무제표 및 가치지표 다운로드</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#dart의-open-api를-이용한-데이터-수집하기"><i class="fa fa-check"></i><b>6.3</b> DART의 Open API를 이용한 데이터 수집하기</a><ul>
<li class="chapter" data-level="6.3.1" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#api-key발급-및-추가하기"><i class="fa fa-check"></i><b>6.3.1</b> API Key발급 및 추가하기</a></li>
<li class="chapter" data-level="6.3.2" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#고유번호-다운로드"><i class="fa fa-check"></i><b>6.3.2</b> 고유번호 다운로드</a></li>
<li class="chapter" data-level="6.3.3" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#공시검색"><i class="fa fa-check"></i><b>6.3.3</b> 공시검색</a></li>
<li class="chapter" data-level="6.3.4" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#사업보고서-주요-정보"><i class="fa fa-check"></i><b>6.3.4</b> 사업보고서 주요 정보</a></li>
<li class="chapter" data-level="6.3.5" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#상장기업-재무정보"><i class="fa fa-check"></i><b>6.3.5</b> 상장기업 재무정보</a></li>
<li class="chapter" data-level="6.3.6" data-path="금융-데이터-수집하기-심화.html"><a href="금융-데이터-수집하기-심화.html#단일회사-전체-재무제표"><i class="fa fa-check"></i><b>6.3.6</b> 단일회사 전체 재무제표</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="데이터-정리하기.html"><a href="데이터-정리하기.html"><i class="fa fa-check"></i><b>7</b> 데이터 정리하기</a><ul>
<li class="chapter" data-level="7.1" data-path="데이터-정리하기.html"><a href="데이터-정리하기.html#주가-정리하기"><i class="fa fa-check"></i><b>7.1</b> 주가 정리하기</a></li>
<li class="chapter" data-level="7.2" data-path="데이터-정리하기.html"><a href="데이터-정리하기.html#재무제표-정리하기"><i class="fa fa-check"></i><b>7.2</b> 재무제표 정리하기</a></li>
<li class="chapter" data-level="7.3" data-path="데이터-정리하기.html"><a href="데이터-정리하기.html#가치지표-정리하기"><i class="fa fa-check"></i><b>7.3</b> 가치지표 정리하기</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html"><i class="fa fa-check"></i><b>8</b> 데이터 분석 및 시각화하기</a><ul>
<li class="chapter" data-level="8.1" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#종목정보-데이터-분석"><i class="fa fa-check"></i><b>8.1</b> 종목정보 데이터 분석</a><ul>
<li class="chapter" data-level="8.1.1" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#join-데이터-합치기"><i class="fa fa-check"></i><b>8.1.1</b> <code>*_join</code>: 데이터 합치기</a></li>
<li class="chapter" data-level="8.1.2" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#glimpse-데이터-구조-확인하기"><i class="fa fa-check"></i><b>8.1.2</b> <code>glimpse()</code>: 데이터 구조 확인하기</a></li>
<li class="chapter" data-level="8.1.3" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#rename-열-이름-바꾸기"><i class="fa fa-check"></i><b>8.1.3</b> <code>rename()</code>: 열 이름 바꾸기</a></li>
<li class="chapter" data-level="8.1.4" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#distinct-고유한-값-확인"><i class="fa fa-check"></i><b>8.1.4</b> distinct(): 고유한 값 확인</a></li>
<li class="chapter" data-level="8.1.5" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#select-원하는-열만-선택"><i class="fa fa-check"></i><b>8.1.5</b> <code>select()</code>: 원하는 열만 선택</a></li>
<li class="chapter" data-level="8.1.6" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#mutate-열-생성-및-데이터-변형"><i class="fa fa-check"></i><b>8.1.6</b> <code>mutate()</code>: 열 생성 및 데이터 변형</a></li>
<li class="chapter" data-level="8.1.7" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#filter-조건을-충족하는-행-선택"><i class="fa fa-check"></i><b>8.1.7</b> <code>filter()</code>: 조건을 충족하는 행 선택</a></li>
<li class="chapter" data-level="8.1.8" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#summarize-요약-통곗값-계산"><i class="fa fa-check"></i><b>8.1.8</b> <code>summarize()</code>: 요약 통곗값 계산</a></li>
<li class="chapter" data-level="8.1.9" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#arrange-데이터-정렬"><i class="fa fa-check"></i><b>8.1.9</b> <code>arrange()</code>: 데이터 정렬</a></li>
<li class="chapter" data-level="8.1.10" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#row_number-순위-계산"><i class="fa fa-check"></i><b>8.1.10</b> <code>row_number()</code>: 순위 계산</a></li>
<li class="chapter" data-level="8.1.11" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#ntile-분위수-계산"><i class="fa fa-check"></i><b>8.1.11</b> <code>ntile()</code>: 분위수 계산</a></li>
<li class="chapter" data-level="8.1.12" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#group_by-그룹별로-데이터를-묶기"><i class="fa fa-check"></i><b>8.1.12</b> <code>group_by()</code>: 그룹별로 데이터를 묶기</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#ggplot-기초"><i class="fa fa-check"></i><b>8.2</b> <code>ggplot()</code> 기초</a><ul>
<li class="chapter" data-level="8.2.1" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#diamonds-데이터셋"><i class="fa fa-check"></i><b>8.2.1</b> diamonds 데이터셋</a></li>
<li class="chapter" data-level="8.2.2" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#data-aesthetics-geometrics"><i class="fa fa-check"></i><b>8.2.2</b> Data, Aesthetics, Geometrics</a></li>
<li class="chapter" data-level="8.2.3" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#facets"><i class="fa fa-check"></i><b>8.2.3</b> Facets</a></li>
<li class="chapter" data-level="8.2.4" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#statistics"><i class="fa fa-check"></i><b>8.2.4</b> Statistics</a></li>
<li class="chapter" data-level="8.2.5" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#coordinates"><i class="fa fa-check"></i><b>8.2.5</b> Coordinates</a></li>
<li class="chapter" data-level="8.2.6" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#theme"><i class="fa fa-check"></i><b>8.2.6</b> Theme</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#종목정보-시각화"><i class="fa fa-check"></i><b>8.3</b> 종목정보 시각화</a><ul>
<li class="chapter" data-level="8.3.1" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#geom_point-산점도-나타내기"><i class="fa fa-check"></i><b>8.3.1</b> <code>geom_point()</code>: 산점도 나타내기</a></li>
<li class="chapter" data-level="8.3.2" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#geom_histogram-히스토그램-나타내기"><i class="fa fa-check"></i><b>8.3.2</b> <code>geom_histogram()</code>: 히스토그램 나타내기</a></li>
<li class="chapter" data-level="8.3.3" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#geom_boxplot-박스-플롯-나타내기"><i class="fa fa-check"></i><b>8.3.3</b> <code>geom_boxplot()</code>: 박스 플롯 나타내기</a></li>
<li class="chapter" data-level="8.3.4" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#dplyr과-ggplot을-연결하여-사용하기"><i class="fa fa-check"></i><b>8.3.4</b> <code>dplyr</code>과 <code>ggplot</code>을 연결하여 사용하기</a></li>
<li class="chapter" data-level="8.3.5" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#geom_bar-막대-그래프-나타내기"><i class="fa fa-check"></i><b>8.3.5</b> <code>geom_bar()</code>: 막대 그래프 나타내기</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#주가-및-수익률-시각화"><i class="fa fa-check"></i><b>8.4</b> 주가 및 수익률 시각화</a><ul>
<li class="chapter" data-level="8.4.1" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#주가-그래프-나타내기"><i class="fa fa-check"></i><b>8.4.1</b> 주가 그래프 나타내기</a></li>
<li class="chapter" data-level="8.4.2" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#인터랙티브-그래프-나타내기"><i class="fa fa-check"></i><b>8.4.2</b> 인터랙티브 그래프 나타내기</a></li>
<li class="chapter" data-level="8.4.3" data-path="데이터-분석-및-시각화하기.html"><a href="데이터-분석-및-시각화하기.html#연도별-수익률-나타내기"><i class="fa fa-check"></i><b>8.4.3</b> 연도별 수익률 나타내기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html"><i class="fa fa-check"></i><b>9</b> 퀀트 전략을 이용한 종목선정 (기본)</a><ul>
<li class="chapter" data-level="9.1" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#베타-이해하기"><i class="fa fa-check"></i><b>9.1</b> 베타 이해하기</a><ul>
<li class="chapter" data-level="9.1.1" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#베타-계산하기"><i class="fa fa-check"></i><b>9.1.1</b> 베타 계산하기</a></li>
<li class="chapter" data-level="9.1.2" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#베타-시각화"><i class="fa fa-check"></i><b>9.1.2</b> 베타 시각화</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#저변동성-전략"><i class="fa fa-check"></i><b>9.2</b> 저변동성 전략</a><ul>
<li class="chapter" data-level="9.2.1" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#저변동성-포트폴리오-구하기-일간-기준"><i class="fa fa-check"></i><b>9.2.1</b> 저변동성 포트폴리오 구하기: 일간 기준</a></li>
<li class="chapter" data-level="9.2.2" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#저변동성-포트폴리오-구하기-주간-기준"><i class="fa fa-check"></i><b>9.2.2</b> 저변동성 포트폴리오 구하기: 주간 기준</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#모멘텀-전략"><i class="fa fa-check"></i><b>9.3</b> 모멘텀 전략</a><ul>
<li class="chapter" data-level="9.3.1" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#모멘텀-포트폴리오-구하기-12개월-모멘텀"><i class="fa fa-check"></i><b>9.3.1</b> 모멘텀 포트폴리오 구하기: 12개월 모멘텀</a></li>
<li class="chapter" data-level="9.3.2" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#모멘텀-포트폴리오-구하기-위험조정-수익률"><i class="fa fa-check"></i><b>9.3.2</b> 모멘텀 포트폴리오 구하기: 위험조정 수익률</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#밸류-전략"><i class="fa fa-check"></i><b>9.4</b> 밸류 전략</a><ul>
<li class="chapter" data-level="9.4.1" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#밸류-포트폴리오-구하기-저pbr"><i class="fa fa-check"></i><b>9.4.1</b> 밸류 포트폴리오 구하기: 저PBR</a></li>
<li class="chapter" data-level="9.4.2" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#각-지표-결합하기"><i class="fa fa-check"></i><b>9.4.2</b> 각 지표 결합하기</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#퀄리티-전략"><i class="fa fa-check"></i><b>9.5</b> 퀄리티 전략</a><ul>
<li class="chapter" data-level="9.5.1" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#f-score"><i class="fa fa-check"></i><b>9.5.1</b> F-Score</a></li>
<li class="chapter" data-level="9.5.2" data-path="퀀트-전략을-이용한-종목선정-기본.html"><a href="퀀트-전략을-이용한-종목선정-기본.html#각-지표를-결합하기"><i class="fa fa-check"></i><b>9.5.2</b> 각 지표를 결합하기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html"><i class="fa fa-check"></i><b>10</b> 퀀트 전략을 이용한 종목선정 (심화)</a><ul>
<li class="chapter" data-level="10.1" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#섹터-중립-포트폴리오"><i class="fa fa-check"></i><b>10.1</b> 섹터 중립 포트폴리오</a></li>
<li class="chapter" data-level="10.2" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#마법공식"><i class="fa fa-check"></i><b>10.2</b> 마법공식</a><ul>
<li class="chapter" data-level="10.2.1" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#퀄리티와-밸류-간의-관계"><i class="fa fa-check"></i><b>10.2.1</b> 퀄리티와 밸류 간의 관계</a></li>
<li class="chapter" data-level="10.2.2" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#마법공식-이해하기"><i class="fa fa-check"></i><b>10.2.2</b> 마법공식 이해하기</a></li>
<li class="chapter" data-level="10.2.3" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#마법공식-구성하기"><i class="fa fa-check"></i><b>10.2.3</b> 마법공식 구성하기</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#이상치-데이터-제거-및-팩터의-결합"><i class="fa fa-check"></i><b>10.3</b> 이상치 데이터 제거 및 팩터의 결합</a><ul>
<li class="chapter" data-level="10.3.1" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#트림trim-이상치-데이터-삭제"><i class="fa fa-check"></i><b>10.3.1</b> 트림(Trim): 이상치 데이터 삭제</a></li>
<li class="chapter" data-level="10.3.2" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#윈저라이징winsorizing-이상치-데이터-대체"><i class="fa fa-check"></i><b>10.3.2</b> 윈저라이징(Winsorizing): 이상치 데이터 대체</a></li>
<li class="chapter" data-level="10.3.3" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#팩터의-결합-방법"><i class="fa fa-check"></i><b>10.3.3</b> 팩터의 결합 방법</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="퀀트-전략을-이용한-종목선정-심화.html"><a href="퀀트-전략을-이용한-종목선정-심화.html#멀티팩터-포트폴리오"><i class="fa fa-check"></i><b>10.4</b> 멀티팩터 포트폴리오</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html"><i class="fa fa-check"></i><b>11</b> 포트폴리오 구성</a><ul>
<li class="chapter" data-level="11.1" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#최소분산-포트폴리오"><i class="fa fa-check"></i><b>11.1</b> 최소분산 포트폴리오</a><ul>
<li class="chapter" data-level="11.1.1" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#slsqp-함수를-이용한-최적화"><i class="fa fa-check"></i><b>11.1.1</b> <code>slsqp()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.2" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#solve.qp-함수를-이용한-최적화"><i class="fa fa-check"></i><b>11.1.2</b> <code>solve.QP()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.3" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#optimalportfolio-함수를-이용한-최적화"><i class="fa fa-check"></i><b>11.1.3</b> <code>optimalPortfolio()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.1.4" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#결괏값들의-비교"><i class="fa fa-check"></i><b>11.1.4</b> 결괏값들의 비교</a></li>
<li class="chapter" data-level="11.1.5" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#최소-및-최대-투자비중-제약조건"><i class="fa fa-check"></i><b>11.1.5</b> 최소 및 최대 투자비중 제약조건</a></li>
<li class="chapter" data-level="11.1.6" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#각-자산별-제약조건의-추가"><i class="fa fa-check"></i><b>11.1.6</b> 각 자산별 제약조건의 추가</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#최대분산효과-포트폴리오"><i class="fa fa-check"></i><b>11.2</b> 최대분산효과 포트폴리오</a><ul>
<li class="chapter" data-level="11.2.1" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#solve.qp-함수를-이용한-최적화-1"><i class="fa fa-check"></i><b>11.2.1</b> <code>solve.QP()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.2.2" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#optimalportfolio-함수를-이용한-최적화-1"><i class="fa fa-check"></i><b>11.2.2</b> <code>optimalPortfolio()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.2.3" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#최소-및-최대-투자비중-제약조건-1"><i class="fa fa-check"></i><b>11.2.3</b> 최소 및 최대 투자비중 제약조건</a></li>
<li class="chapter" data-level="11.2.4" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#각-자산-별-제약조건의-추가"><i class="fa fa-check"></i><b>11.2.4</b> 각 자산 별 제약조건의 추가</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#위험균형-포트폴리오"><i class="fa fa-check"></i><b>11.3</b> 위험균형 포트폴리오</a><ul>
<li class="chapter" data-level="11.3.1" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#주식-60와-채권-40-포트폴리오의-위험기여도"><i class="fa fa-check"></i><b>11.3.1</b> 주식 60%와 채권 40% 포트폴리오의 위험기여도</a></li>
<li class="chapter" data-level="11.3.2" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#rp-함수를-이용한-최적화"><i class="fa fa-check"></i><b>11.3.2</b> <code>rp()</code> 함수를 이용한 최적화</a></li>
<li class="chapter" data-level="11.3.3" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#위험예산-포트폴리오"><i class="fa fa-check"></i><b>11.3.3</b> 위험예산 포트폴리오</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#인덱스-포트폴리오-구성하기"><i class="fa fa-check"></i><b>11.4</b> 인덱스 포트폴리오 구성하기</a><ul>
<li class="chapter" data-level="11.4.1" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#시가총액비중-계산하기"><i class="fa fa-check"></i><b>11.4.1</b> 시가총액비중 계산하기</a></li>
<li class="chapter" data-level="11.4.2" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#인덱스-포트폴리오-복제하기"><i class="fa fa-check"></i><b>11.4.2</b> 인덱스 포트폴리오 복제하기</a></li>
<li class="chapter" data-level="11.4.3" data-path="포트폴리오-구성.html"><a href="포트폴리오-구성.html#팩터를-이용한-인핸스드-포트폴리오-구성하기"><i class="fa fa-check"></i><b>11.4.3</b> 팩터를 이용한 인핸스드 포트폴리오 구성하기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="포트폴리오-백테스트.html"><a href="포트폴리오-백테스트.html"><i class="fa fa-check"></i><b>12</b> 포트폴리오 백테스트</a><ul>
<li class="chapter" data-level="12.1" data-path="포트폴리오-백테스트.html"><a href="포트폴리오-백테스트.html#return.portfolio-함수"><i class="fa fa-check"></i><b>12.1</b> <code>Return.Portfolio()</code> 함수</a><ul>
<li class="chapter" data-level="12.1.1" data-path="포트폴리오-백테스트.html"><a href="포트폴리오-백테스트.html#인자-목록-살펴보기"><i class="fa fa-check"></i><b>12.1.1</b> 인자 목록 살펴보기</a></li>
<li class="chapter" data-level="12.1.2" data-path="포트폴리오-백테스트.html"><a href="포트폴리오-백테스트.html#출력값-살펴보기"><i class="fa fa-check"></i><b>12.1.2</b> 출력값 살펴보기</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="포트폴리오-백테스트.html"><a href="포트폴리오-백테스트.html#전통적인-60대-40-포트폴리오-백테스트"><i class="fa fa-check"></i><b>12.2</b> 전통적인 60대 40 포트폴리오 백테스트</a></li>
<li class="chapter" data-level="12.3" data-path="포트폴리오-백테스트.html"><a href="포트폴리오-백테스트.html#시점-선택-전략-백테스트"><i class="fa fa-check"></i><b>12.3</b> 시점 선택 전략 백테스트</a></li>
<li class="chapter" data-level="12.4" data-path="포트폴리오-백테스트.html"><a href="포트폴리오-백테스트.html#동적-자산배분-백테스트"><i class="fa fa-check"></i><b>12.4</b> 동적 자산배분 백테스트</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="성과-및-위험-평가.html"><a href="성과-및-위험-평가.html"><i class="fa fa-check"></i><b>13</b> 성과 및 위험 평가</a><ul>
<li class="chapter" data-level="13.1" data-path="성과-및-위험-평가.html"><a href="성과-및-위험-평가.html#결과-측정-지표"><i class="fa fa-check"></i><b>13.1</b> 결과 측정 지표</a><ul>
<li class="chapter" data-level="13.1.1" data-path="성과-및-위험-평가.html"><a href="성과-및-위험-평가.html#수익률-및-변동성"><i class="fa fa-check"></i><b>13.1.1</b> 수익률 및 변동성</a></li>
<li class="chapter" data-level="13.1.2" data-path="성과-및-위험-평가.html"><a href="성과-및-위험-평가.html#낙폭과-최대낙폭"><i class="fa fa-check"></i><b>13.1.2</b> 낙폭과 최대낙폭</a></li>
<li class="chapter" data-level="13.1.3" data-path="성과-및-위험-평가.html"><a href="성과-및-위험-평가.html#연도별-수익률"><i class="fa fa-check"></i><b>13.1.3</b> 연도별 수익률</a></li>
<li class="chapter" data-level="13.1.4" data-path="성과-및-위험-평가.html"><a href="성과-및-위험-평가.html#승률-및-롤링-윈도우-값"><i class="fa fa-check"></i><b>13.1.4</b> 승률 및 롤링 윈도우 값</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="성과-및-위험-평가.html"><a href="성과-및-위험-평가.html#팩터-회귀분석-및-테이블로-나타내기"><i class="fa fa-check"></i><b>13.2</b> 팩터 회귀분석 및 테이블로 나타내기</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="http://henryquant.blogspot.com/" target="blank">Henry's Quantopia</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R을 이용한 퀀트 투자 포트폴리오 만들기</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="포트폴리오-구성" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> 포트폴리오 구성</h1>
<p>종목별로 비중을 어떻게 배분하느냐에 따라 성과가 달라지므로, 종목의 선택 못지 않게 중요한 것이 포트폴리오를 구성하는 방법입니다. 최적 포트폴리오의 구성은 수식을 기반으로 최적화된 해를 찾습니다. 물론 엑셀의 해 찾기와 같은 기능을 사용해 간단한 형태의 최적화 구현이 가능하지만, 방대한 데이터를 다룰 경우에는 속도가 지나치게
느려지거나 계산할 수 없게 되기도 합니다.</p>
<p>동일한 최적화 방법을 지속적으로 사용한다면 프로그래밍을 통해 함수를 만들고, 입력 변수만 변경하는 것이 훨씬 효율적인 방법입니다. 또한 포트폴리오 최적화에 관한 좋은 패키지들이 이미 많이 나와 있으므로, 대략적인 내용만 이해하고 실제 구현은 패키지를 이용하는 것도 좋은 방법입니다.</p>
<p>이 CHAPTER에서는 일반적으로 많이 사용되는 최소분산 포트폴리오, 최대분산효과 포트폴리오, 위험균형 포트폴리오를 구현해보도록 합니다. 또한 실무에서 많이 사용되는 인덱스 포트폴리오를 구성하는 방법에 대해서도 살펴보겠습니다.</p>
<p>먼저 최소분산, 최대분산효과, 위험균형 포트폴리오 구성을 위해 글로벌 자산을 대표하는 ETF 데이터를 다운로드하겠습니다.</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="포트폴리오-구성.html#cb394-1"></a><span class="kw">library</span>(quantmod)</span>
<span id="cb394-2"><a href="포트폴리오-구성.html#cb394-2"></a><span class="kw">library</span>(PerformanceAnalytics)</span>
<span id="cb394-3"><a href="포트폴리오-구성.html#cb394-3"></a><span class="kw">library</span>(magrittr)</span>
<span id="cb394-4"><a href="포트폴리오-구성.html#cb394-4"></a></span>
<span id="cb394-5"><a href="포트폴리오-구성.html#cb394-5"></a>symbols =<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;SPY&#39;</span>, <span class="co"># 미국 주식</span></span>
<span id="cb394-6"><a href="포트폴리오-구성.html#cb394-6"></a>            <span class="st">&#39;IEV&#39;</span>, <span class="co"># 유럽 주식 </span></span>
<span id="cb394-7"><a href="포트폴리오-구성.html#cb394-7"></a>            <span class="st">&#39;EWJ&#39;</span>, <span class="co"># 일본 주식</span></span>
<span id="cb394-8"><a href="포트폴리오-구성.html#cb394-8"></a>            <span class="st">&#39;EEM&#39;</span>, <span class="co"># 이머징 주식</span></span>
<span id="cb394-9"><a href="포트폴리오-구성.html#cb394-9"></a>            <span class="st">&#39;TLT&#39;</span>, <span class="co"># 미국 장기채</span></span>
<span id="cb394-10"><a href="포트폴리오-구성.html#cb394-10"></a>            <span class="st">&#39;IEF&#39;</span>, <span class="co"># 미국 중기채</span></span>
<span id="cb394-11"><a href="포트폴리오-구성.html#cb394-11"></a>            <span class="st">&#39;IYR&#39;</span>, <span class="co"># 미국 리츠</span></span>
<span id="cb394-12"><a href="포트폴리오-구성.html#cb394-12"></a>            <span class="st">&#39;RWX&#39;</span>, <span class="co"># 글로벌 리츠</span></span>
<span id="cb394-13"><a href="포트폴리오-구성.html#cb394-13"></a>            <span class="st">&#39;GLD&#39;</span>, <span class="co"># 금</span></span>
<span id="cb394-14"><a href="포트폴리오-구성.html#cb394-14"></a>            <span class="st">&#39;DBC&#39;</span>  <span class="co"># 상품</span></span>
<span id="cb394-15"><a href="포트폴리오-구성.html#cb394-15"></a>            )</span>
<span id="cb394-16"><a href="포트폴리오-구성.html#cb394-16"></a><span class="kw">getSymbols</span>(symbols, <span class="dt">src =</span> <span class="st">&#39;yahoo&#39;</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;SPY&quot; &quot;IEV&quot; &quot;EWJ&quot; &quot;EEM&quot; &quot;TLT&quot; &quot;IEF&quot; &quot;IYR&quot; &quot;RWX&quot;
##  [9] &quot;GLD&quot; &quot;DBC&quot;</code></pre>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="포트폴리오-구성.html#cb396-1"></a>prices =<span class="st"> </span><span class="kw">do.call</span>(cbind,</span>
<span id="cb396-2"><a href="포트폴리오-구성.html#cb396-2"></a>                 <span class="kw">lapply</span>(symbols, <span class="cf">function</span>(x) <span class="kw">Ad</span>(<span class="kw">get</span>(x)))) <span class="op">%&gt;%</span></span>
<span id="cb396-3"><a href="포트폴리오-구성.html#cb396-3"></a><span class="st">  </span><span class="kw">setNames</span>(symbols)</span>
<span id="cb396-4"><a href="포트폴리오-구성.html#cb396-4"></a></span>
<span id="cb396-5"><a href="포트폴리오-구성.html#cb396-5"></a>rets =<span class="st"> </span><span class="kw">Return.calculate</span>(prices) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">na.omit</span>()</span></code></pre></div>
<p><code>getSymbols()</code> 함수를 통해 일반적으로 자산배분에서 많이 사용되는 주식과 채권, 대체자산에 해당하는 ETF 가격 데이터를 받은 후 <code>lapply()</code>와 <code>Ad()</code>, <code>get()</code> 함수의 조합을 통해 수정주가만을 선택하고 열의 형태로 묶어줍니다. 그 후 <code>Return.calculate()</code> 함수를 통해 수익률을 계산합니다.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="포트폴리오-구성.html#cb397-1"></a><span class="kw">library</span>(tidyr)</span>
<span id="cb397-2"><a href="포트폴리오-구성.html#cb397-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb397-3"><a href="포트폴리오-구성.html#cb397-3"></a><span class="kw">library</span>(corrplot)</span>
<span id="cb397-4"><a href="포트폴리오-구성.html#cb397-4"></a></span>
<span id="cb397-5"><a href="포트폴리오-구성.html#cb397-5"></a><span class="kw">cor</span>(rets) <span class="op">%&gt;%</span></span>
<span id="cb397-6"><a href="포트폴리오-구성.html#cb397-6"></a><span class="st">  </span><span class="kw">corrplot</span>(<span class="dt">method =</span> <span class="st">&#39;color&#39;</span>, <span class="dt">type =</span> <span class="st">&#39;upper&#39;</span>,</span>
<span id="cb397-7"><a href="포트폴리오-구성.html#cb397-7"></a>           <span class="dt">addCoef.col =</span> <span class="st">&#39;black&#39;</span>, <span class="dt">number.cex =</span> <span class="fl">0.7</span>,</span>
<span id="cb397-8"><a href="포트폴리오-구성.html#cb397-8"></a>           <span class="dt">tl.cex =</span> <span class="fl">0.6</span>, <span class="dt">tl.srt=</span><span class="dv">45</span>, <span class="dt">tl.col =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb397-9"><a href="포트폴리오-구성.html#cb397-9"></a>           <span class="dt">col =</span></span>
<span id="cb397-10"><a href="포트폴리오-구성.html#cb397-10"></a>             <span class="kw">colorRampPalette</span>(<span class="kw">c</span>(<span class="st">&#39;blue&#39;</span>, <span class="st">&#39;white&#39;</span>, <span class="st">&#39;red&#39;</span>))(<span class="dv">200</span>),</span>
<span id="cb397-11"><a href="포트폴리오-구성.html#cb397-11"></a>           <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="dv">0</span>))</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-3-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>각 ETF의 수익률 간 상관관계를 살펴보면 같은 자산군 내에서는 강한 상관관계를 보이며, 주식과 채권 간에는 매우 낮은 상관관계를 보입니다. 또한 주식과 리츠 간에도 꽤 높은 상관관계를 보입니다.</p>
<p>포트폴리오 최적화에는 분산-공분산 행렬이 대부분 사용되며, 이는 <code>cov()</code> 함수를 통해 손쉽게 계산할 수 있습니다.</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="포트폴리오-구성.html#cb398-1"></a>covmat =<span class="st"> </span><span class="kw">cov</span>(rets)</span></code></pre></div>
<div id="최소분산-포트폴리오" class="section level2">
<h2><span class="header-section-number">11.1</span> 최소분산 포트폴리오</h2>
<p>최소분산 포트폴리오(Minimum Variance Portfolio)는 변동성이 최소인 포트폴리오입니다. 포트폴리오의 변동성은 일반적으로 <span class="math inline">\(\sum_{i=1}^{n}\sum_{j=1}^{n}w_iw_j\sigma_{ij}\)</span>의 형태로 표현되지만, 최적화 작업을 위해서는 행렬의 형태인 <span class="math inline">\(w&#39;\Omega w\)</span>로 표현하는 것이 더욱 편리합니다. 이 중 <span class="math inline">\(w\)</span>는 각 자산들의 비중을 행렬의 형태로 나타낸 것이며, <span class="math inline">\(\Omega\)</span>는 분산-공분산 행렬을 나타낸 것입니다. 분산-공분산 행렬은 사전에 고정되어 있는 값이므로, 각 자산들의 비중인 <span class="math inline">\(w\)</span>를 변화시킴으로써 포트폴리오의 변동성이 최소인 지점을 찾을 수 있습니다.</p>
<p>최소분산 포트폴리오의 목적함수는 아래의 수식으로 표현할 수 있습니다. 이 중 <span class="math inline">\(^1/_2\)</span>은 단지 미분했을 때 계산을 용이하게 하기 위한 장치일 뿐 결과에는 영향을 미치지 않습니다.</p>
<p><span class="math display">\[ 최소분산\,포트폴리오의\,목적함수: min\,^1/_2\,w&#39;\Omega w \]</span></p>
<p>다만 단순히 위의 목적함수를 찾는 해를 구하면 결괏값이 음수가 나오기도 하는데 이것은 공매도를 의미합니다. 일반적으로 공매도가 불가능하다는 점과, 투자비중의 합이 100%가 되어야 한다는 점을 고려하면 아래와 같은 제약조건을 추가해야 합니다.</p>
<p><span class="math display">\[ 최소분산\,포트폴리오의\,제약조건: \sum_{i=1}^{n}w_i = 1, w_i \ge 0 \]</span>
물론 이 외에도 각 섹터의 투자비중 합에 대한 제약조건이나 회전율에 대한 제약조건 등도 추가할 수 있습니다.</p>
<div id="slsqp-함수를-이용한-최적화" class="section level3">
<h3><span class="header-section-number">11.1.1</span> <code>slsqp()</code> 함수를 이용한 최적화</h3>
<p>R에서 가장 손쉽게 최적화 작업을 수행하는 방법은 nloptr 패키지의 <code>slsqp()</code> 함수를 이용하는 것입니다. slsqp() 함수는 순차적 이차 계획(Sequential Quadratic Programming)을 이용해 해를 찾으며, 목적함수와 제약조건은 다음과 같습니다.</p>
<table>
<caption><span id="tab:unnamed-chunk-5">표 11.1: </span><code>slsqp()</code> 함수 목적함수와 제약조건</caption>
<thead>
<tr class="header">
<th align="center">목적함수</th>
<th align="center">제약조건</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(min\,f(x)\)</span></td>
<td align="center"><span class="math inline">\(b(x)\ge0, c(x)=0\)</span></td>
</tr>
</tbody>
</table>
<p>목적함수에서 <span class="math inline">\(f(x)\)</span> 는 최소화하고자 하는 값, 즉 포트폴리오의 변동성입니다. 제약조건은 크게 개별 자산의 투자 비중이 0 이상인 것과, 투자 비중의 합이 1이 되도록 하는 것입니다. 첫 번째 제약조건은 자연스럽게 개별 자산의 투자비중이 0 이상인 것을 의미합니다. 두 번째 제약조건은 약간의 변형을 통해 투자비중의 합이 1이 되는 제약조건을 만들 수 있습니다. <span class="math inline">\(c(x)\)</span>를 <strong>투자비중의 합 – 1</strong> 로 변형할 경우 -1을 우변으로 넘기면 결국 <strong>투자비중의 합 = 1</strong>의 형태로 나타낼 수 있습니다. <code>slsqp()</code> 함수의 구성은 다음과 같습니다.</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="포트폴리오-구성.html#cb399-1"></a><span class="kw">slsqp</span>(x0, fn, <span class="dt">gr =</span> <span class="ot">NULL</span>, <span class="dt">lower =</span> <span class="ot">NULL</span>, <span class="dt">upper =</span> <span class="ot">NULL</span>,</span>
<span id="cb399-2"><a href="포트폴리오-구성.html#cb399-2"></a>      <span class="dt">hin =</span> <span class="ot">NULL</span>, <span class="dt">hinjac =</span> <span class="ot">NULL</span>, <span class="dt">heq =</span> <span class="ot">NULL</span>, <span class="dt">heqjac =</span> <span class="ot">NULL</span>,</span>
<span id="cb399-3"><a href="포트폴리오-구성.html#cb399-3"></a>      <span class="dt">nl.info =</span> <span class="ot">FALSE</span>, <span class="dt">control =</span> <span class="kw">list</span>(), ...)</span></code></pre></div>
<p>이 중 우리가 구체적으로 입력해야 할 값은 x0, fn, hin, heq 항목 입니다.</p>
<ol style="list-style-type: decimal">
<li>x0은 초기값이며, 일반적으로 모든 x에 대해 동일한 값을 입력합니다.</li>
<li>fn은 최소화하고자 하는 목적함수로, 포트폴리오 변동성에 해당합니다.</li>
<li>hin은 부등위 제약조건(inequality constraints)을 의미하며, 프로그래밍 내에서는 hin &gt;= 0로 인식하며, 각 자산의 비중이 0보다 크다는 제약조건과 연결됩니다.</li>
<li>heq는 등위 제약조건(equality constraints)을 의미하며, 프로그래밍 내에서는 heq == 0을 의미합니다. <strong>투자비중의 합 - 1</strong>의 형태를 입력한다면 투자비중의 합이 1 이라는 제약조건과 연결됩니다.</li>
</ol>
<p>표 <a href="포트폴리오-구성.html#tab:slsqp">11.2</a>는 최소분산 포트폴리오를 구할 때 필요한 주요 변수에 대한 내용입니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:slsqp">표 11.2: </span>slsqp() 함수의 인자와 포트폴리오 내 변수
</caption>
<thead>
<tr>
<th style="text-align:center;">
변수명
</th>
<th style="text-align:center;">
내용
</th>
<th style="text-align:center;">
포트폴리오 내 변수
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
x0
</td>
<td style="text-align:center;">
초기값
</td>
<td style="text-align:center;">
없음
</td>
</tr>
<tr>
<td style="text-align:center;">
fn
</td>
<td style="text-align:center;">
목적함수
</td>
<td style="text-align:center;">
포트폴리오 변동성
</td>
</tr>
<tr>
<td style="text-align:center;">
hin
</td>
<td style="text-align:center;">
부등위 제약조건
</td>
<td style="text-align:center;">
각 자산의 비중이 0 보다 큰 제약조건
</td>
</tr>
<tr>
<td style="text-align:center;">
heq
</td>
<td style="text-align:center;">
등위 제약조건
</td>
<td style="text-align:center;">
투자 비중의 합이 1인 제약조건
</td>
</tr>
</tbody>
</table>
<p><code>slsqp()</code> 함수를 이용해 최소분산 포트폴리오를 만족하는 자산의 투자비중을 구하는 과정은 다음과 같습니다. 먼저 fn, hin, heq에 해당하는 함수들을 각각 만든 후 이를 <code>slsqp()</code> 함수와 결합해 최적화된 결괏값을 얻을 수 있습니다. 구체적인 과정은 아래와 같습니다.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="포트폴리오-구성.html#cb400-1"></a>objective =<span class="st"> </span><span class="cf">function</span>(w) {</span>
<span id="cb400-2"><a href="포트폴리오-구성.html#cb400-2"></a>  obj =<span class="st"> </span><span class="kw">t</span>(w) <span class="op">%*%</span><span class="st"> </span>covmat <span class="op">%*%</span><span class="st"> </span>w</span>
<span id="cb400-3"><a href="포트폴리오-구성.html#cb400-3"></a>  <span class="kw">return</span>(obj)</span>
<span id="cb400-4"><a href="포트폴리오-구성.html#cb400-4"></a>}</span></code></pre></div>
<p>먼저 목적함수에 해당하는 부분입니다. covmat은 사전에 계산된 분산-공분산 행렬이며, <span class="math inline">\(w\)</span>는 각 자산의 투자비중입니다. obj는 포트폴리오의 변동성인 <span class="math inline">\(w&#39;\Omega w\)</span>를 계산한 것입니다. 즉, 해당 함수는 계산된 <span class="math inline">\(w\)</span>를 바탕으로 포트폴리오의 변동성을 반환하고, 우리의 목적은 해당 값이 최소가 되도록 하는 것입니다.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="포트폴리오-구성.html#cb401-1"></a>hin.objective =<span class="st"> </span><span class="cf">function</span>(w) {</span>
<span id="cb401-2"><a href="포트폴리오-구성.html#cb401-2"></a>  <span class="kw">return</span>(w)</span>
<span id="cb401-3"><a href="포트폴리오-구성.html#cb401-3"></a>}</span></code></pre></div>
<p><span class="math inline">\(w_i \ge 0\)</span> 제약조건에 해당하는 부등위 제약조건입니다. 패키지 내에서는 hin &gt;= 0 의 형태로 인식하므로, 계산된 비중인 <span class="math inline">\(w\)</span>를 단순히 입력하기만 하면 됩니다.</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="포트폴리오-구성.html#cb402-1"></a>heq.objective =<span class="st"> </span><span class="cf">function</span>(w) {</span>
<span id="cb402-2"><a href="포트폴리오-구성.html#cb402-2"></a>  sum_w =<span class="st"> </span><span class="kw">sum</span>(w)</span>
<span id="cb402-3"><a href="포트폴리오-구성.html#cb402-3"></a>  <span class="kw">return</span>( sum_w <span class="op">-</span><span class="st"> </span><span class="dv">1</span> )</span>
<span id="cb402-4"><a href="포트폴리오-구성.html#cb402-4"></a>}</span></code></pre></div>
<p><span class="math inline">\(\sum_{i=1}^{n}w_i = 1\)</span> 제약조건에 해당하는 등위 제약조건입니다. 먼저 계산된 비중인 <span class="math inline">\(w\)</span>들의 합계를 구한 후 해당 값에서 1을 빼주는 값을 반환하도록 합니다. 프로그래밍 내에서는 heq == 0 의 형태로 인식을 하므로 결국 (sum_w – 1) == 0, 즉 sum_w == 1의 제약조건과 동일합니다.</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="포트폴리오-구성.html#cb403-1"></a><span class="kw">library</span>(nloptr)</span>
<span id="cb403-2"><a href="포트폴리오-구성.html#cb403-2"></a></span>
<span id="cb403-3"><a href="포트폴리오-구성.html#cb403-3"></a>result =<span class="st"> </span><span class="kw">slsqp</span>( <span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),</span>
<span id="cb403-4"><a href="포트폴리오-구성.html#cb403-4"></a>                <span class="dt">fn =</span> objective,</span>
<span id="cb403-5"><a href="포트폴리오-구성.html#cb403-5"></a>                <span class="dt">hin =</span> hin.objective,</span>
<span id="cb403-6"><a href="포트폴리오-구성.html#cb403-6"></a>                <span class="dt">heq =</span> heq.objective)</span>
<span id="cb403-7"><a href="포트폴리오-구성.html#cb403-7"></a></span>
<span id="cb403-8"><a href="포트폴리오-구성.html#cb403-8"></a><span class="kw">print</span>(result<span class="op">$</span>par)</span></code></pre></div>
<pre><code>##  [1]  1.427e-01 -8.243e-19 -1.215e-17  3.376e-18
##  [5]  8.500e-17  7.924e-01  5.714e-19  6.046e-19
##  [9]  1.081e-17  6.491e-02</code></pre>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="포트폴리오-구성.html#cb405-1"></a><span class="kw">print</span>(result<span class="op">$</span>value)</span></code></pre></div>
<pre><code>## [1] 0.000009852</code></pre>
<p>위에서 만들어진 함수들을 바탕으로 최적화 작업을 실행합니다. 초기값인 x0에는 먼저 동일한 비중들을 입력합니다. 예제에서는 종목이 10개 이므로, x0값에는 <code>rep(0.1, 10)</code> 인 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1을 입력합니다. 최소화하고자 하는 목적함수 fn에는 위에서 구성한 objective 함수를 입력합니다. 부등위 제약조건과 등위 제약조건에도 각각 위에서 구성한 hin.objective와 heq.objective 함수를 입력합니다.</p>
<p>즉, 해당 함수는 초기값을 시작점으로 해 주어진 제약조건을 만족하는 해를 찾기 위해 <span class="math inline">\(w\)</span>값들을 조정하는 작업을 반복한 후 목적함수가 최소가 되는 지점의 <span class="math inline">\(w\)</span>를 반환합니다.</p>
<p>result 값 중 $par는 최적화된 지점의 해를 의미하며, 최소분산 포트폴리오를 구성하는 자산들의 투자 비중을 의미합니다. $value는 $par에서 산출된 값을 목적함수 fn에 입력하였을 때 나오는 결괏값으로써, 포트폴리오의 분산을 의미합니다.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="포트폴리오-구성.html#cb407-1"></a>w_<span class="dv">1</span> =<span class="st"> </span>result<span class="op">$</span>par <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb407-2"><a href="포트폴리오-구성.html#cb407-2"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb407-3"><a href="포트폴리오-구성.html#cb407-3"></a></span>
<span id="cb407-4"><a href="포트폴리오-구성.html#cb407-4"></a><span class="kw">print</span>(w_<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.1427 0.0000 0.0000 0.0000 0.0000 0.7924 0.0000 0.0000 
##    GLD    DBC 
## 0.0000 0.0649</code></pre>
<p>자산들의 투자비중은 result$par를 통해 추출한 후, <code>round()</code> 함수를 이용해 반올림합니다. 마지막으로 이름에 종목명을 입력합니다. 계산된 비중으로 포트폴리오를 구성하면 포트폴리오의 비중이 최소가 됩니다.</p>
</div>
<div id="solve.qp-함수를-이용한-최적화" class="section level3">
<h3><span class="header-section-number">11.1.2</span> <code>solve.QP()</code> 함수를 이용한 최적화</h3>
<p>다음으로는 quadprog 패키지 내의 <code>solve.QP()</code> 함수를 이용해 포트폴리오 최적화를 하는 방법이 있습니다. 해당 함수는 쌍대기법(Dual Method)을 이용해 제약조건 내에서 목적함수가 최소화되는 해를 구합니다. 해당 함수의 목적함수와 제약조건은 표 <a href="포트폴리오-구성.html#tab:solveqp">11.3</a>과 같습니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:solveqp">표 11.3: </span>solve.QP 함수 목적함수와 제약조건
</caption>
<thead>
<tr>
<th style="text-align:center;">
목적함수
</th>
<th style="text-align:center;">
제약조건
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
<span class="math inline">\(min(-d^Tb+^1/_2b^TDb)\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(A^Tb \ge b_0\)</span>
</td>
</tr>
</tbody>
</table>
<p>최소분산 포트폴리오의 목적함수가 <span class="math inline">\(min\,^1/_2\,w&#39;\Omega w\)</span>로 표시된다는 점을 생각하면, 해당 함수는 매우 이해하기 쉽게 구성되어 있습니다. <span class="math inline">\(b\)</span>를 각 개별 자산의 투자 비중인 <span class="math inline">\(w\)</span>, <span class="math inline">\(D\)</span>를 분산-공분산 행렬인 <span class="math inline">\(\Omega\)</span>라 생각하면, 목적함수 중 <span class="math inline">\(min\,^1/_2\,wDw\)</span>는 최소분산 포트폴리오의 목적함수와 정확히 동일합니다. <span class="math inline">\(d\)</span>를 0으로 생각하면 <span class="math inline">\(-d^Tb\)</span> 또한 0이 되어 목적함수에 아무런 영향도 미치지 않습니다.</p>
<p>제약조건 역시 <span class="math inline">\(A^T\)</span> 항목을 적절하게 수정한다면, 개별 자산의 투자비중이 0 이상인 것과, 투자비중의 합이 1이 되도록 만들 수 있습니다. 이에 대해서는 뒤에서 구체적으로 다루도록 합니다. <code>solve.QP()</code> 함수의 사용법은 아래와 같습니다.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="포트폴리오-구성.html#cb409-1"></a><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, <span class="dt">meq =</span> <span class="dv">0</span>, <span class="dt">factorized =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<ol style="list-style-type: decimal">
<li>Dmat은 목적함수 중 <span class="math inline">\(D\)</span>에 해당하는 행렬 부분으로서 분산-공분산 행렬과 일치합니다.</li>
<li>dvec은 목적함수 중 <span class="math inline">\(d\)</span>에 해당하는 벡터 부분이며, 포트폴리오 최적화에서는 역할이 없습니다.</li>
<li>Amat은 제약조건 중 <span class="math inline">\(A^T\)</span>에 해당하는 부분으로써, 제약조건 중 좌변에 위치하는 항목입니다. 제약조건에서 보듯이 제약조건 행렬을 구한 후 이것의 전치(Transpose) 행렬을 입력해야 하는 데 주의합니다.</li>
<li>bvec은 제약조건 중 <span class="math inline">\(b_0\)</span>에 해당하는 부분으로써, 제약조건 중 우변에 위치하는 항목입니다.</li>
<li>meq는 bvec의 몇 번째까지를 등위 제약조건으로 설정할지에 대한 부분입니다.</li>
</ol>
<p>표 <a href="포트폴리오-구성.html#tab:solveqp2">11.4</a>는 위의 내용을 요약한 것이며, 각 변수를 입력한 후 함수를 실행하면 위의 목적함수와 제약조건을 만족하는 <span class="math inline">\(b\)</span> 값을 찾습니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:solveqp2">표 11.4: </span><code>solve.QP</code> 함수의 인자와 포트폴리오 내 변수
</caption>
<thead>
<tr>
<th style="text-align:center;">
변수명
</th>
<th style="text-align:center;">
내용
</th>
<th style="text-align:center;">
포트폴리오 내 변수
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Dmat
</td>
<td style="text-align:center;">
목적함수 중 D
</td>
<td style="text-align:center;">
분산-공분산 행렬
</td>
</tr>
<tr>
<td style="text-align:center;">
dvec
</td>
<td style="text-align:center;">
목적함수 중 d
</td>
<td style="text-align:center;">
해당사항 없음
</td>
</tr>
<tr>
<td style="text-align:center;">
Amat
</td>
<td style="text-align:center;">
제약조건 (좌변)
</td>
<td style="text-align:center;">
<span class="math inline">\(\sum_{i=1}^{n}w_i, w_i\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
bvec
</td>
<td style="text-align:center;">
제약조건 (우변)
</td>
<td style="text-align:center;">
비중의 합이 1, 각 비중이 0보다 큼
</td>
</tr>
<tr>
<td style="text-align:center;">
meq
</td>
<td style="text-align:center;">
등위 제약조건 개수
</td>
<td style="text-align:center;">
1개 (비중의 합이 1)
</td>
</tr>
</tbody>
</table>
<p><code>solve.QP()</code> 함수를 이용해 최소분산 포트폴리오 비중을 구할 때는 Amat 항목을 제대로 입력하는 것이 가장 중요하며, 나머지 항목은 매우 손쉽게 입력이 가능합니다. 설명된 내용에 해당하는 행렬을 손으로 직접 써가며 계산해본다면 훨씬 이해하기가 쉬울 것입니다. 구체적인 과정은 아래와 같습니다.</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="포트폴리오-구성.html#cb410-1"></a>Dmat =<span class="st"> </span>covmat</span>
<span id="cb410-2"><a href="포트폴리오-구성.html#cb410-2"></a>dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb410-3"><a href="포트폴리오-구성.html#cb410-3"></a>Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="kw">diag</span>(<span class="dv">10</span>), <span class="op">-</span><span class="kw">diag</span>(<span class="dv">10</span>)))</span>
<span id="cb410-4"><a href="포트폴리오-구성.html#cb410-4"></a>bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="op">-</span><span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>))</span>
<span id="cb410-5"><a href="포트폴리오-구성.html#cb410-5"></a>meq =<span class="st"> </span><span class="dv">1</span></span></code></pre></div>
<p>Dmat에는 분산-공분산 행렬을 입력하며,dvec은 최소분산 포트폴리오를 구하는데는 필요한 값이 아니므로 0벡터를 입력합니다. 등위 제약조건과 부등위 제약조건(<span class="math inline">\(A^Tb \ge b_0\)</span>)을 행렬의 형태로 표현하면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix}
1 &amp;  \dots &amp; 1 \\ 1 &amp;  \dots &amp; 0 \\ \vdots &amp;  \ddots &amp; \vdots \\
0 &amp;  \dots &amp; 1 \\ -1 &amp; \dots &amp; 0 \\ \vdots &amp;  \ddots &amp; \vdots \\
0 &amp;  \dots &amp; -1 \\ \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} = 
\begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ \vdots \\ w_{10} \\ -w_1 \\ 
\vdots \\ -w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ -1 \\ \vdots \\ -1 \end{bmatrix} \]</span></p>
<p>이 중 맨 왼쪽 행렬의 전치행렬이 제약조건의 좌변인 Amat에 해당합니다.</p>
<p><span class="math display">\[ Amat = \begin{bmatrix}
1 &amp; \dots &amp; 1 \\ 1 &amp; \dots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\
0 &amp; \dots &amp; 1 \\ -1 &amp; \dots &amp; 0 \\ \vdots &amp;  \ddots &amp; \vdots \\
0 &amp;  \dots &amp; -1 \end{bmatrix} ^T \]</span></p>
<p>맨 오른쪽 행렬이 제약조건의 우변인 bvec에 해당합니다.
<span class="math display">\[ bvec = \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ -1 \\ \vdots \\ -1 \end{bmatrix} \]</span></p>
<p>위의 제약조건은 크게 투자비중의 합이 1인 제약조건, 최소 투자비중이 0 이상인 제약조건, 최대 투자비중이 1 이하인 제약조건, 총 세 개 부분으로 나눌 수 있습니다.</p>
<p><span class="math display">\[ (1)\; \sum_{i = 1}^nw_i = 1 \Rightarrow \begin{bmatrix} w_1 + w_2 + \dots \ w_{10}  \end{bmatrix} = 
\begin{bmatrix} 1 \end{bmatrix} \]</span></p>
<p><span class="math display">\[(2)\; w_i \ge 0 \Rightarrow \begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10}  \end{bmatrix} \ge
\begin{bmatrix} 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix} \\\]</span></p>
<p><span class="math display">\[(3)\;-w_i \ge -1 \Rightarrow  \begin{bmatrix} -w_1 \\ -w_2 \\ \vdots \\ -w_{10}  \end{bmatrix} \ge \begin{bmatrix} -1 \\ -1 \\ \vdots \\ -1 \end{bmatrix} \]</span></p>
<p><code>solve.QP()</code> 함수의 제약조건은 항상 좌변이 큰 형태이므로, 최대 투자비중에 대한 제약조건은 다음 행렬의 양변에 마이너스(-)를 곱해 부등호를 맞춰주었습니다.</p>
<p><span class="math display">\[\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10}  \end{bmatrix} \le
\begin{bmatrix} 1 \\ 1 \\ \vdots \\ 1 \end{bmatrix}\]</span></p>
<p>첫 번째 제약조건은 부등호가 아닌 등호, 즉 투자비중의 합이 1인 조건을 의미하므로 meq = 1을 통해 첫 번째 제약조건은 등식 제약조건임을 선언할 수 있습니다.</p>
<p>제약조건의 좌변에 해당하는 Amat을 만드는 과정은 다음과 같습니다. 먼저 <code>rep(1, 10)</code>을 통해 최상단에 위치한 1로 이루어진 행렬을 만들어줍니다.</p>
<p><span class="math display">\[\begin{bmatrix} 1 &amp; 1 &amp; \dots &amp; 1 \end{bmatrix}\]</span></p>
<p>하단의 1과 -1로 이루어진 대각행렬은 <code>diag()</code> 함수를 통해 쉽게 만들 수 있습니다.</p>
<p><span class="math display">\[ diag(10) = \begin{bmatrix} 1 &amp; \dots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\ 0 &amp; \dots &amp;\ 1\end{bmatrix}\]</span></p>
<p><span class="math display">\[ -diag(10) = \begin{bmatrix} -1 &amp; \dots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\ 0 &amp; \dots &amp;\ -1\end{bmatrix}\]</span>
<code>rbind()</code> 함수를 통해 세 개의 행렬을 행으로 묶어주면 제약조건의 맨 왼쪽 행렬과 동일한 형태가 됩니다. 이를 <code>t()</code> 함수를 통해 전치행렬을 만들어 준 뒤 Amat에 입력합니다.</p>
<p>제약조건에 해당하는 bvec은 1, 0, -1로 이루어진 벡터를 통해 손쉽게 만들 수 있습니다.</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="포트폴리오-구성.html#cb411-1"></a><span class="kw">library</span>(quadprog)</span>
<span id="cb411-2"><a href="포트폴리오-구성.html#cb411-2"></a>result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)</span>
<span id="cb411-3"><a href="포트폴리오-구성.html#cb411-3"></a></span>
<span id="cb411-4"><a href="포트폴리오-구성.html#cb411-4"></a><span class="kw">print</span>(result<span class="op">$</span>solution)</span></code></pre></div>
<pre><code>##  [1]  1.427e-01 -3.407e-19  0.000e+00  1.137e-17
##  [5] -2.769e-17  7.924e-01 -1.881e-18 -2.249e-18
##  [9] -1.908e-19  6.491e-02</code></pre>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="포트폴리오-구성.html#cb413-1"></a><span class="kw">print</span>(result<span class="op">$</span>value)</span></code></pre></div>
<pre><code>## [1] 0.000004926</code></pre>
<p>위에 입력된 내역들을 <code>solve.QP()</code> 함수에 넣어 최적화 값을 찾아줍니다. 결과 중 $solution은 최적화된 지점의 해, 즉 최소분산 포트폴리오를 구성하는 자산들의 투자비중을 의미합니다. $value는 $solution에서 산출된 값을 목적함수에 입력했을때 나오는 결괏값으로서, 포트폴리오의 분산을 의미합니다.</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="포트폴리오-구성.html#cb415-1"></a>w_<span class="dv">2</span> =<span class="st"> </span>result<span class="op">$</span>solution <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb415-2"><a href="포트폴리오-구성.html#cb415-2"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb415-3"><a href="포트폴리오-구성.html#cb415-3"></a></span>
<span id="cb415-4"><a href="포트폴리오-구성.html#cb415-4"></a><span class="kw">print</span>(w_<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.1427 0.0000 0.0000 0.0000 0.0000 0.7924 0.0000 0.0000 
##    GLD    DBC 
## 0.0000 0.0649</code></pre>
<p>자산들의 투자비중은 result$solution을 통해 추출한 후 <code>round()</code> 함수를 이용해 반올림합니다. 마지막으로 이름에 종목명을 입력합니다. 계산된 비중으로 포트폴리오를 구성하면 포트폴리오의 비중이 최소화됩니다.</p>
</div>
<div id="optimalportfolio-함수를-이용한-최적화" class="section level3">
<h3><span class="header-section-number">11.1.3</span> <code>optimalPortfolio()</code> 함수를 이용한 최적화</h3>
<p>RiskPortfolios 패키지의 <code>optimalPortfolio()</code> 함수를 이용해 매우 간단하게 최적화 포트폴리오를 구현할 수도 있습니다. 해당 함수의 사용법은 다음과 같습니다.</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="포트폴리오-구성.html#cb417-1"></a><span class="kw">optimalPortfolio</span>(Sigma, <span class="dt">mu =</span> <span class="ot">NULL</span>, <span class="dt">semiDev =</span> <span class="ot">NULL</span>,</span>
<span id="cb417-2"><a href="포트폴리오-구성.html#cb417-2"></a>                 <span class="dt">control =</span> <span class="kw">list</span>())</span></code></pre></div>
<p>Sigma는 분산-공분산 행렬입니다. mu와 semiDev는 각각 기대수익률과 세미 편차(Semi Deviation)로서, 입력하지 않아도 됩니다. control은 포트폴리오 종류 및 제약조건에 해당하는 부분이며, 자세한 내용은 표 <a href="포트폴리오-구성.html#tab:optimal">11.5</a>와 같습니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:optimal">표 11.5: </span>optimalPortfolio() 포트폴리오 내 control 인자
</caption>
<thead>
<tr>
<th style="text-align:center;">
종류
</th>
<th style="text-align:center;">
입력값
</th>
<th style="text-align:center;">
내용
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;vertical-align: middle !important;" rowspan="5">
type
</td>
<td style="text-align:center;">
minvol
</td>
<td style="text-align:center;">
최소분산 포트폴리오
</td>
</tr>
<tr>
<td style="text-align:center;">
invvol
</td>
<td style="text-align:center;">
역변동성 포트폴리오
</td>
</tr>
<tr>
<td style="text-align:center;">
erc
</td>
<td style="text-align:center;">
위험 균형 포트폴리오
</td>
</tr>
<tr>
<td style="text-align:center;">
maxdiv
</td>
<td style="text-align:center;">
최대 분산효과 포트폴리오
</td>
</tr>
<tr>
<td style="text-align:center;">
riskeff
</td>
<td style="text-align:center;">
위험-효율적 포트폴리오
</td>
</tr>
<tr>
<td style="text-align:center;vertical-align: middle !important;" rowspan="2">
constraint
</td>
<td style="text-align:center;">
lo
</td>
<td style="text-align:center;">
최소 투자 비중이 0 보다 클것
</td>
</tr>
<tr>
<td style="text-align:center;">
user
</td>
<td style="text-align:center;">
최소(LB) 및 최대 투자 비중(UB) 설정
</td>
</tr>
</tbody>
</table>
<p>control 항목에서 원하는 포트폴리오 타입과 제약조건을 입력해주면, 매우 손쉽게 최적화 포트폴리오를 구현할 수 있습니다.</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="포트폴리오-구성.html#cb418-1"></a><span class="kw">library</span>(RiskPortfolios)</span>
<span id="cb418-2"><a href="포트폴리오-구성.html#cb418-2"></a></span>
<span id="cb418-3"><a href="포트폴리오-구성.html#cb418-3"></a>w_<span class="dv">3</span> =<span class="st"> </span><span class="kw">optimalPortfolio</span>(covmat,</span>
<span id="cb418-4"><a href="포트폴리오-구성.html#cb418-4"></a>                       <span class="dt">control =</span> <span class="kw">list</span>(<span class="dt">type =</span> <span class="st">&#39;minvol&#39;</span>,</span>
<span id="cb418-5"><a href="포트폴리오-구성.html#cb418-5"></a>                                      <span class="dt">constraint =</span> <span class="st">&#39;lo&#39;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb418-6"><a href="포트폴리오-구성.html#cb418-6"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb418-7"><a href="포트폴리오-구성.html#cb418-7"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb418-8"><a href="포트폴리오-구성.html#cb418-8"></a></span>
<span id="cb418-9"><a href="포트폴리오-구성.html#cb418-9"></a><span class="kw">print</span>(w_<span class="dv">3</span>)  </span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.1427 0.0000 0.0000 0.0000 0.0000 0.7924 0.0000 0.0000 
##    GLD    DBC 
## 0.0000 0.0649</code></pre>
<p><code>optimalPortfolio()</code> 함수 내부에 분산-공분산 행렬을 입력합니다. type 부분에 최소분산 포트폴리오에 해당하는 minvol을 입력하며, constraint에는 각 자산의 비중이 0보다 큰 제약조건인 lo(Long Only)를 입력합니다. 비중의 합이 1인 제약조건은 자동적으로 적용이 됩니다.</p>
<p>이처럼 패키지를 이용하면 훨씬 간단하게 원하는 값을 얻을 수 있습니다. GitHub를 통해 해당 함수의 코드를 살펴보면 <code>solve.QP()</code> 함수를 이용해 작성한 방법과 거의 동일합니다. 따라서 위의 과정들을 대략적으로 이해한 후 패키지를 사용해 포트폴리오 최적화를 구현하는 것이 현명한 방법이 될 수도 있습니다.</p>
</div>
<div id="결괏값들의-비교" class="section level3">
<h3><span class="header-section-number">11.1.4</span> 결괏값들의 비교</h3>
<p>아래 표는 <code>slsqp()</code>, <code>solve.QP()</code>, <code>optimalPortfolio()</code>를 이용하여 구한 값들의 비교입니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-18">표 11.6: </span>최적화 결과 비교
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
SPY
</th>
<th style="text-align:center;">
IEV
</th>
<th style="text-align:center;">
EWJ
</th>
<th style="text-align:center;">
EEM
</th>
<th style="text-align:center;">
TLT
</th>
<th style="text-align:center;">
IEF
</th>
<th style="text-align:center;">
IYR
</th>
<th style="text-align:center;">
RWX
</th>
<th style="text-align:center;">
GLD
</th>
<th style="text-align:center;">
DBC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
slsqp
</td>
<td style="text-align:center;">
0.1427
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.7924
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.0649
</td>
</tr>
<tr>
<td style="text-align:left;">
solve.QP
</td>
<td style="text-align:center;">
0.1427
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.7924
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.0649
</td>
</tr>
<tr>
<td style="text-align:left;">
optimalPortfolio
</td>
<td style="text-align:center;">
0.1427
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.7924
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.0649
</td>
</tr>
</tbody>
</table>
<p>세 가지 방법 모두 결과가 동일합니다. 그러나 여기서 나온 결과를 이용해 그대로 투자하기에는 문제가 있습니다. 일부 자산은 투자비중이 0%, 즉 전혀 투자하지 않는 반면, 특정 자산에 대부분의 비중인 79.24%를 투자하는 편중된 결과가 나옵니다.</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="포트폴리오-구성.html#cb420-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb420-2"><a href="포트폴리오-구성.html#cb420-2"></a></span>
<span id="cb420-3"><a href="포트폴리오-구성.html#cb420-3"></a><span class="kw">data.frame</span>(w_<span class="dv">1</span>) <span class="op">%&gt;%</span></span>
<span id="cb420-4"><a href="포트폴리오-구성.html#cb420-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),</span>
<span id="cb420-5"><a href="포트폴리오-구성.html#cb420-5"></a>                        <span class="dt">y =</span> w_<span class="dv">1</span>)) <span class="op">+</span></span>
<span id="cb420-6"><a href="포트폴리오-구성.html#cb420-6"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb420-7"><a href="포트폴리오-구성.html#cb420-7"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-19-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>이처럼 변동성이 가장 낮은 종목에 대부분의 비중이 투자되는 구석해(Corner Solution) 문제를 해결하기 위해 각 자산의 최소 및 최대 투자비중 제약조건을 추가해 줄 필요가 있습니다.</p>
</div>
<div id="최소-및-최대-투자비중-제약조건" class="section level3">
<h3><span class="header-section-number">11.1.5</span> 최소 및 최대 투자비중 제약조건</h3>
<p>구석해 문제를 방지하고, 모든 자산에 골고루 투자하기 위해 개별 투자비중을 최소 5%, 최대 20%로 하는 제약조건을 추가하겠습니다. 먼저 <code>slsqp()</code> 함수에서 제약조건을 추가하는 방법은 다음과 같습니다.</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="포트폴리오-구성.html#cb421-1"></a>result =<span class="st"> </span><span class="kw">slsqp</span>( <span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),</span>
<span id="cb421-2"><a href="포트폴리오-구성.html#cb421-2"></a>                <span class="dt">fn =</span> objective,</span>
<span id="cb421-3"><a href="포트폴리오-구성.html#cb421-3"></a>                <span class="dt">hin =</span> hin.objective,</span>
<span id="cb421-4"><a href="포트폴리오-구성.html#cb421-4"></a>                <span class="dt">heq =</span> heq.objective,</span>
<span id="cb421-5"><a href="포트폴리오-구성.html#cb421-5"></a>                <span class="dt">lower =</span> <span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>),</span>
<span id="cb421-6"><a href="포트폴리오-구성.html#cb421-6"></a>                <span class="dt">upper =</span> <span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>))</span>
<span id="cb421-7"><a href="포트폴리오-구성.html#cb421-7"></a></span>
<span id="cb421-8"><a href="포트폴리오-구성.html#cb421-8"></a>w_<span class="dv">4</span> =<span class="st"> </span>result<span class="op">$</span>par <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb421-9"><a href="포트폴리오-구성.html#cb421-9"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb421-10"><a href="포트폴리오-구성.html#cb421-10"></a></span>
<span id="cb421-11"><a href="포트폴리오-구성.html#cb421-11"></a><span class="kw">print</span>(w_<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.05 0.05 0.05 0.05 0.20 0.20 0.05 0.05 0.20 0.10</code></pre>
<p>함수의 마지막에 lower와 upper 제약조건을 추가로 입력하면 해당 값 사이에서 최적화를 만족하는 해를 찾게 되며, 해당 예에서는 5%와 20% 사이에서 해를 찾게 됩니다. 추가로 입력한 제약조건에 맞게, 최소 투자비중은 5%이며, 최대 투자비중은 20%임을 확인할 수 있습니다.</p>
<p>다음은 <code>solve.QP()</code> 함수 내에서 제약조건을 추가하는 방법입니다. 해당 함수 역시 다른 입력값은 모두 동일하며, 제약조건의 우변에 해당하는 bvec 항목만 수정하면 됩니다. 최소, 최대 투자비중 제약조건을 기존 [0, 1]에서 [0.05, 0.20] 로 변경하면, bvec에 해당하는 행렬은 다음과 같이 변경됩니다.</p>
<p><span class="math display">\[ 기존: \begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ \vdots \\ w_{10} \\ -w_1 \\ 
\vdots \\ -w_{10} \end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ -1 \\ \vdots \\ -1 \end{bmatrix} \\ \]</span>
<span class="math display">\[변경: \begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ \vdots \\ w_{10} \\ -w_1 \\ 
\vdots \\ -w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0.05 \\ \vdots \\ 0.05 \\ -0.20 \\ \vdots \\ -0.20 \end{bmatrix} \]</span></p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="포트폴리오-구성.html#cb423-1"></a>Dmat =<span class="st"> </span>covmat</span>
<span id="cb423-2"><a href="포트폴리오-구성.html#cb423-2"></a>dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb423-3"><a href="포트폴리오-구성.html#cb423-3"></a>Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="kw">diag</span>(<span class="dv">10</span>), <span class="op">-</span><span class="kw">diag</span>(<span class="dv">10</span>)))</span>
<span id="cb423-4"><a href="포트폴리오-구성.html#cb423-4"></a>bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>), <span class="op">-</span><span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>))</span>
<span id="cb423-5"><a href="포트폴리오-구성.html#cb423-5"></a>meq =<span class="st"> </span><span class="dv">1</span></span>
<span id="cb423-6"><a href="포트폴리오-구성.html#cb423-6"></a></span>
<span id="cb423-7"><a href="포트폴리오-구성.html#cb423-7"></a>result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)</span>
<span id="cb423-8"><a href="포트폴리오-구성.html#cb423-8"></a></span>
<span id="cb423-9"><a href="포트폴리오-구성.html#cb423-9"></a>w_<span class="dv">5</span> =<span class="st"> </span>result<span class="op">$</span>solution <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb423-10"><a href="포트폴리오-구성.html#cb423-10"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb423-11"><a href="포트폴리오-구성.html#cb423-11"></a></span>
<span id="cb423-12"><a href="포트폴리오-구성.html#cb423-12"></a><span class="kw">print</span>(w_<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.05 0.05 0.05 0.05 0.20 0.20 0.05 0.05 0.20 0.10</code></pre>
<p>bvec 항목을 제외한 모든 코드는 기존과 동일하며, 조건함수의 우변인 bvec만 각각 최소 투자비중과 최대 투자비중이 [0, 1]에서 [0.05, 0.20]으로 변경되었습니다. 해당 방법 역시 추가적인 투자비중 제약이 잘 적용되었음이 확인됩니다.</p>
<p>마지막으로 <code>optimalPortfolio()</code> 함수 내에서 최소 및 최대 투자비중을 추가하는 방법입니다. 입력변수의 control 항목 중 constraint 부분을 간단하게 수정해 원하는 조건을 입력할 수 있습니다.</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="포트폴리오-구성.html#cb425-1"></a>w_<span class="dv">6</span> =<span class="st"> </span><span class="kw">optimalPortfolio</span>(covmat,</span>
<span id="cb425-2"><a href="포트폴리오-구성.html#cb425-2"></a>                       <span class="dt">control =</span> <span class="kw">list</span>(<span class="dt">type =</span> <span class="st">&#39;minvol&#39;</span>,</span>
<span id="cb425-3"><a href="포트폴리오-구성.html#cb425-3"></a>                                      <span class="dt">constraint =</span> <span class="st">&#39;user&#39;</span>,</span>
<span id="cb425-4"><a href="포트폴리오-구성.html#cb425-4"></a>                                      <span class="dt">LB =</span> <span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>),</span>
<span id="cb425-5"><a href="포트폴리오-구성.html#cb425-5"></a>                                      <span class="dt">UB =</span> <span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>))) <span class="op">%&gt;%</span></span>
<span id="cb425-6"><a href="포트폴리오-구성.html#cb425-6"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb425-7"><a href="포트폴리오-구성.html#cb425-7"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb425-8"><a href="포트폴리오-구성.html#cb425-8"></a></span>
<span id="cb425-9"><a href="포트폴리오-구성.html#cb425-9"></a><span class="kw">print</span>(w_<span class="dv">6</span>)</span></code></pre></div>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.05 0.05 0.05 0.05 0.20 0.20 0.05 0.05 0.20 0.10</code></pre>
<p>constraint 부분에 롱온리 제약조건에 해당하는 lo 대신 직접 제약값들을 입력할 수 있는 user를 입력하며, LB에는 최소 투자비중 벡터를, UB에는 최대 투자비중 벡터를 입력합니다. 따라서 원하는 제약조건 내에서 결괏값이 계산됩니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-23">표 11.7: </span>최소 및 최대 비중제약 조건 후 결과 비교
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
SPY
</th>
<th style="text-align:center;">
IEV
</th>
<th style="text-align:center;">
EWJ
</th>
<th style="text-align:center;">
EEM
</th>
<th style="text-align:center;">
TLT
</th>
<th style="text-align:center;">
IEF
</th>
<th style="text-align:center;">
IYR
</th>
<th style="text-align:center;">
RWX
</th>
<th style="text-align:center;">
GLD
</th>
<th style="text-align:center;">
DBC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
slsqp
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.1
</td>
</tr>
<tr>
<td style="text-align:left;">
solve.QP
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.1
</td>
</tr>
<tr>
<td style="text-align:left;">
optimalPortfolio
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
0.1
</td>
</tr>
</tbody>
</table>
<p>최소 및 최대 제약조건을 추가한 경우도 세 가지 방법 모두 동일한 결과가 나오게 되며, 비중도 각각 5%와 20%로 제한되어 구석해 문제 또한 해결되었음이 확인됩니다.</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="포트폴리오-구성.html#cb427-1"></a><span class="kw">data.frame</span>(w_<span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb427-2"><a href="포트폴리오-구성.html#cb427-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),</span>
<span id="cb427-3"><a href="포트폴리오-구성.html#cb427-3"></a>                        <span class="dt">y =</span> w_<span class="dv">4</span>)) <span class="op">+</span></span>
<span id="cb427-4"><a href="포트폴리오-구성.html#cb427-4"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb427-5"><a href="포트폴리오-구성.html#cb427-5"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.05</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb427-6"><a href="포트폴리오-구성.html#cb427-6"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.20</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb427-7"><a href="포트폴리오-구성.html#cb427-7"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-24-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<div id="각-자산별-제약조건의-추가" class="section level3">
<h3><span class="header-section-number">11.1.6</span> 각 자산별 제약조건의 추가</h3>
<p>투자 규모가 크지 않다면 위에서 추가한 제약조건만으로도 충분히 훌륭한 포트폴리오가 구성됩니다. 그러나 투자 규모가 커지면 추가적인 제약조건들을 고려해야 할 경우가 생깁니다. 벤치마크 비중과의 괴리로 인한 추적오차(Tracking Error)를 고려해야 할 수도 있고, 투자 대상별 거래량을 고려한 제약조건을 추가해야 할 때도 있습니다.</p>
<p>기존 제약조건에는 자산별로 동일한 최소 및 최대 투자비중 제약조건을 다루었지만, 자산별로 상이한 제약조건이 필요할 경우도 있습니다. <code>slsqp()와</code> <code>optimalPortfolio()</code> 함수에서는 복잡한 제약조건을 다루기가 힘들지만, <code>solve.QP()</code> 함수는 bvec 부분을 간단하게 수정해 어렵지 않게 구현이 가능합니다.</p>
<p>먼저 표 <a href="포트폴리오-구성.html#tab:assetconst">11.8</a>은 새롭게 설정하고자 하는 각 자산별 최소 및 최대 제약조건입니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:assetconst">표 11.8: </span>각 자산 별 최소 및 최대 제약조건
</caption>
<thead>
<tr>
<th style="text-align:center;">
제약
</th>
<th style="text-align:center;">
1
</th>
<th style="text-align:center;">
2
</th>
<th style="text-align:center;">
3
</th>
<th style="text-align:center;">
4
</th>
<th style="text-align:center;">
5
</th>
<th style="text-align:center;">
6
</th>
<th style="text-align:center;">
7
</th>
<th style="text-align:center;">
8
</th>
<th style="text-align:center;">
9
</th>
<th style="text-align:center;">
10
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
최소
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.03
</td>
<td style="text-align:center;">
0.03
</td>
</tr>
<tr>
<td style="text-align:center;">
최대
</td>
<td style="text-align:center;">
0.25
</td>
<td style="text-align:center;">
0.25
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.08
</td>
<td style="text-align:center;">
0.08
</td>
</tr>
</tbody>
</table>
<p>이를 행렬의 형태로 나타내면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix} 1 &amp; \dots &amp; 1 \\ 1 &amp; \dots &amp; 0 \\ \vdots &amp;  \ddots &amp; \vdots \\
0 &amp; \dots &amp; 1 \\ -1 &amp; \dots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\
0 &amp; \dots &amp; -1 \\ \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} 
= \begin{bmatrix} w_1 + w_2 + \dots + w_{10} \\ w_1 \\ w_2 \\ w_3 \\ w_4 \\ w_5 \\ w_6 \\
w_7\\ w_8\\ w_9\\ w_{10} \\ -w_1 \\ -w_2 \\ -w_3 \\ -w_4 \\ -w_5 \\ -w_6 \\ -w_7 \\ -w_8 \\ -w_9 \\ -w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0.10 \\ 0.10 \\ 0.05 \\ 0.05 \\ 0.10 \\ 0.10 \\ 0.05 \\ 0.05 \\ 0.03 \\ 0.03 \\ -0.25 \\ -0.25 \\ -0.20 \\ -0.20 \\ -0.20 \\ -0.20 \\ -0.10 \\ -0.10 \\ -0.08 \\ -0.08
\end{bmatrix} \]</span></p>
<p>위의 행렬 중 오른쪽 부분을 bvec에 그대로 입력합니다.</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="포트폴리오-구성.html#cb428-1"></a>Dmat =<span class="st"> </span>covmat</span>
<span id="cb428-2"><a href="포트폴리오-구성.html#cb428-2"></a>dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb428-3"><a href="포트폴리오-구성.html#cb428-3"></a>Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="kw">diag</span>(<span class="dv">10</span>), <span class="op">-</span><span class="kw">diag</span>(<span class="dv">10</span>))) </span>
<span id="cb428-4"><a href="포트폴리오-구성.html#cb428-4"></a>bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">c</span>(<span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>,</span>
<span id="cb428-5"><a href="포트폴리오-구성.html#cb428-5"></a>              <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.03</span>, <span class="fl">0.03</span>),</span>
<span id="cb428-6"><a href="포트폴리오-구성.html#cb428-6"></a>         <span class="op">-</span><span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>,</span>
<span id="cb428-7"><a href="포트폴리오-구성.html#cb428-7"></a>            <span class="fl">0.20</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.08</span>, <span class="fl">0.08</span>))</span>
<span id="cb428-8"><a href="포트폴리오-구성.html#cb428-8"></a>meq =<span class="st"> </span><span class="dv">1</span></span>
<span id="cb428-9"><a href="포트폴리오-구성.html#cb428-9"></a></span>
<span id="cb428-10"><a href="포트폴리오-구성.html#cb428-10"></a>result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)</span>
<span id="cb428-11"><a href="포트폴리오-구성.html#cb428-11"></a></span>
<span id="cb428-12"><a href="포트폴리오-구성.html#cb428-12"></a>result<span class="op">$</span>solution <span class="op">%&gt;%</span></span>
<span id="cb428-13"><a href="포트폴리오-구성.html#cb428-13"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb428-14"><a href="포트폴리오-구성.html#cb428-14"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.1034 0.1000 0.0866 0.0500 0.2000 0.2000 0.0500 0.0500 
##    GLD    DBC 
## 0.0800 0.0800</code></pre>
<p>결괏값을 확인해보면 각 자산별 제약조건 내에 위치함을 확인할 수 있습니다.</p>
</div>
</div>
<div id="최대분산효과-포트폴리오" class="section level2">
<h2><span class="header-section-number">11.2</span> 최대분산효과 포트폴리오</h2>
<p>앞서 설명했듯이 포트폴리오의 변동성은 <span class="math inline">\(\sum_{i=1}^{n}\sum_{j=1}^{n}w_iw_j\sigma_{ij}\)</span> 형태로 나타나며, 이는 다음과 같이 표현할 수도 있습니다.</p>
<p><span class="math display">\[\sigma_p^2 = \sum_{i=1}^{n}\sum_{j=1}^{n}w_iw_j\sigma_{ij} = \sum_{i=1}^nw_i^2\sigma_i^2 +
\sum_{i=1}^{n}\sum_{i \ne j}^{n}w_iw_j\rho_{ij}\sigma_i\sigma_j \]</span></p>
<p>이 중 <span class="math inline">\(\sum_{i=1}^{n}\sum_{i \ne j}^{n}w_iw_j\rho_{ij}\sigma_i\sigma_j\)</span> 부분에는 자산 간 상관관계<span class="math inline">\((\rho_{ij})\)</span>가 포함되어 있습니다. 상관관계는 -1과 1 사이에 위치하며 상관관계가 1, 즉 두 자산이 완벽하게 동일한 경우에는 포트폴리오의 변동성은 개별 자산 변동성의 가중합과 같습니다. 그러나 <strong>상관관계가 낮아질수록 포트폴리오의 변동성 또한 점차 낮아집니다.</strong> 이러한 효과를 투자에서는 <strong>분산효과</strong>라고 합니다.</p>
<p>이러한 분산효과의 정도를 측정하는 지표가 분산 비율(DR: Diversification Ratio)입니다. 분산 비율의 분자는 개별 변동성의 가중합이며, 분모는 포트폴리오의 변동성입니다. 이를 수식으로 나타내면 다음과 같습니다.</p>
<p><span class="math display">\[ 분산\,비율 =  \frac{\sum w_i \sigma_i}{\sigma_p} = \frac{w&#39;\sigma}{\sqrt{w&#39;\Omega w}}\]</span></p>
<p>모든 자산 간의 상관관계가 1일 경우, 위의 예시에서 살펴본 것과 같이 포트폴리오의 변동성은 개별 자산 변동성의 가중합과 같아지게 됩니다. 즉, <span class="math inline">\(\sum w_i \sigma_i = \sigma_p\)</span>가 되어, 분산 비율은 1이 됩니다. 그러나 대부분의 경우에서 자산 간의 상관관계는 1보다 낮으며, 이로 인해 포트폴리오의 분산은 단순 가중합보다 작아지게 되고(<span class="math inline">\(\sigma_p &lt; \sum w_i\sigma_i\)</span>), 분산 비율은 1보다 커지게 됩니다.</p>
<p>자산 간 상관관계가 낮은 종목을 위주로 포트폴리오를 구성할수록 분산효과로 인해 포트폴리오의 변동성은 낮아지고, 분산 비율은 점점 커집니다. 최대분산효과 포트폴리오(Most Diversified Portfolio)는 분산효과가 최대가 되는, 즉 분산 비율이 최대가 되는 포트폴리오를 구성하는 방법입니다. 이에 대한 목적함수와 제약조건은 다음과 같습니다.</p>
<p><span class="math display">\[목적함수: max\,DR = max \frac{\sum w_i \sigma_i}{\sigma_p}\]</span>
<span class="math display">\[제약조건: \sum_{i=1}^n w_i = 1, w_i \ge 0\]</span></p>
<p>최대분산효과 포트폴리오의 목적함수는 분산비율을 최대화하는 데 있는 반면, 대부분의 최적화 프로그래밍은 목적함수를 최소화하는 형태로 이루어집니다. 따라서 목적함수인 <span class="math inline">\(maxDR\)</span>을 최소화하는 형태로 바꿀 필요가 있는데 크게 세 가지 방법이 있습니다.</p>
<ol style="list-style-type: decimal">
<li>Choueifaty Synthetic Asset Back-Transformation을 이용하는 방법<span class="citation">(Choueifaty and Coignard <a href="#ref-choueifaty2008toward" role="doc-biblioref">2008</a>)</span></li>
<li>Duality를 이용하는 방법<span class="citation">(Choueifaty, Froidure, and Reynier <a href="#ref-choueifaty2013properties" role="doc-biblioref">2013</a>)</span></li>
<li>Min (-)DR 방법</li>
</ol>
<p>먼저 Choueifaty Synthetic Asset Back-Transformation 방법은 목적함수 <span class="math inline">\(min\,w_s&#39;cw_s\)</span>와 제약조건 <span class="math inline">\(\sum_{i=1}^n w_i = 1, w_i \ge 0\)</span>을 만족하는 자산별 비중을 구합니다. 그 후, 구해진 비중을 각각의 표준편차로 나누어주며, 비중의 합이 1이 되도록 표준화해줍니다. 여기서 주의할 점은 목적함수의 <span class="math inline">\(c\)</span>가 우리가 지금까지 사용하던 분산-공분산 행렬이 아닌, <strong>상관관계</strong> 행렬이라는 점입니다.</p>
<p>Duality 방법의 목적함수는 최소분산 포트폴리오와 동일한 <span class="math inline">\(min^1/_2w&#39;\sigma w\)</span>이며, 제약조건만 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1, w_i \ge 0\)</span>, 즉 개별 자산의 비중이 0보다 크고 개별 표준편차의 가중합이 1인 조건으로 바뀝니다. 그 후, 비중의 합이 1이 되도록 표준화를 해줍니다.</p>
<p>기존 두 방법이 수학적 증명에 의해 <span class="math inline">\(maxDR\)</span>을 최소화하는 형태로 풀어준 반면, 간단하게 목적함수를 <span class="math inline">\(min(-DR)\)</span>의 형태로 바꾸어 풀 수도 있습니다. 표 <a href="포트폴리오-구성.html#tab:solveqp">11.3</a>는 세 가지 방법을 요약한 내용입니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:mdp">표 11.9: </span>MDP 방법 비교
</caption>
<thead>
<tr>
<th style="text-align:center;">
방법
</th>
<th style="text-align:center;">
목적함수
</th>
<th style="text-align:center;">
제약조건
</th>
<th style="text-align:center;">
표준화
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Transformation
</td>
<td style="text-align:center;">
<span class="math inline">\(min\,w_s&#39;cw_s\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\sum_{i=1}^n w_i = 1\)</span>
<span class="math inline">\(w_i \ge 0\)</span>
</td>
<td style="text-align:center;">
비중을 각각의 표준편차로 나눈 후
비중의 합으로 표준화
</td>
</tr>
<tr>
<td style="text-align:center;">
Duality
</td>
<td style="text-align:center;">
<span class="math inline">\(min\,^1/_2w&#39;\sigma w\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1\)</span>
<span class="math inline">\(w_i \ge 0\)</span>
</td>
<td style="text-align:center;">
비중의 합으로 표준화
</td>
</tr>
<tr>
<td style="text-align:center;">
-DR
</td>
<td style="text-align:center;">
min(-DR)
</td>
<td style="text-align:center;">
<span class="math inline">\(\sum_{i=1}^n w_i = 1\)</span>
<span class="math inline">\(w_i \ge0\)</span>
</td>
<td style="text-align:center;">
불필요
</td>
</tr>
</tbody>
</table>
<div id="solve.qp-함수를-이용한-최적화-1" class="section level3">
<h3><span class="header-section-number">11.2.1</span> <code>solve.QP()</code> 함수를 이용한 최적화</h3>
<p>먼저 <code>solve.QP()</code> 함수를 이용해 Duality 방법을 통해 최대분산효과 포트폴리오를 만족하는 해를 찾도록 하겠습니다.</p>
<p>Duality 방법에서 목적함수는 <span class="math inline">\(min\,^1/_2w&#39;\sigma w\)</span>로 최소분산 포트폴리오와 동일하며, 제약조건은 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1, w_i \ge 0\)</span>입니다. 제약조건 부분인 Amat과 bvec 부분을 입력할 때 이 부분을 고려해야 합니다.</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="포트폴리오-구성.html#cb430-1"></a>Dmat =<span class="st"> </span>covmat</span>
<span id="cb430-2"><a href="포트폴리오-구성.html#cb430-2"></a>dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb430-3"><a href="포트폴리오-구성.html#cb430-3"></a>Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(covmat)), <span class="kw">diag</span>(<span class="dv">10</span>)))</span>
<span id="cb430-4"><a href="포트폴리오-구성.html#cb430-4"></a>bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>))</span>
<span id="cb430-5"><a href="포트폴리오-구성.html#cb430-5"></a>meq =<span class="st"> </span><span class="dv">1</span></span></code></pre></div>
<p>제약조건에 해당하는 Amat 부분과 bvec 부분은 최소분산 포트폴리오와 다소 다릅니다. 표 <a href="포트폴리오-구성.html#tab:mvmdp">11.10</a>에는 둘 간에 코드가 어떻게 다른지 나타나 있습니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:mvmdp">표 11.10: </span>Amat과 bvec 차이 비교
</caption>
<thead>
<tr>
<th style="text-align:center;">
인자
</th>
<th style="text-align:center;">
최소분산 포트폴리오
</th>
<th style="text-align:center;">
최대분산효과 포트폴리오
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Amat
</td>
<td style="text-align:center;">
t(rbind(rep(1, 10), diag(10), -diag(10)))
</td>
<td style="text-align:center;">
t(rbind(sqrt(diag(covmat)), diag(10)))
</td>
</tr>
<tr>
<td style="text-align:center;">
bvec
</td>
<td style="text-align:center;">
c(1, rep(0, 10), -rep(1, 10))
</td>
<td style="text-align:center;">
c(1, rep(0, 10))
</td>
</tr>
</tbody>
</table>
<p>이해를 위해 Duality 방법의 제약조건을 행렬의 형태로 표현하면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix}
\sigma_1 &amp; \dots &amp; \sigma_{10} \\ 1 &amp; \dots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\
0 &amp; \dots &amp; 1 \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} = 
\begin{bmatrix} \sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10} \\ w_1 \\ \vdots \\ w_{10} \\ \end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \end{bmatrix} \]</span></p>
<p>1행의 <span class="math inline">\(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}\)</span>은 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1\)</span>과 같으며, 해당 식은 등위제약조건으로서 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = \sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10} = 1\)</span>을 의미합니다. 2행부터 마지막 행까지는 모두 <span class="math inline">\(w_i \ge 0\)</span> 조건으로써, 개별 자산의 투자비중이 0보다 큰 조건을 의미합니다.</p>
<p>행렬의 맨 왼쪽에 해당하는 Amat은 각 자산의 표준편차로 이루어진 벡터 행렬과, 1로 이루어진 대각행렬로 구성되어 있습니다. 먼저 <code>diag(covmat)</code>을 통해 분산-공분산 부분에서 대각 부분, 즉 분산 부분만을 추출할 수 있습니다. 개별 자산의 분산인 <span class="math inline">\(\sigma_{i,i}\)</span>는 <span class="math inline">\(\sigma_i\sigma_i\rho_{1,1}\)</span> 형태로 쓸 수 있으며, <span class="math inline">\(\rho_{1,1} = 1\)</span>을 적용하면 <span class="math inline">\(\sigma_i^2\)</span>와 같습니다. 따라서 대각부분 값에 제곱근을 계산하는 <code>sqrt()</code> 함수를 적용하면 각각의 표준편차만 남게 됩니다. 이를 <code>diag(10)</code>을 통해 만든 대각행렬과 행으로 묶어준 후 전치행렬을 입력해 줍니다.</p>
<p>bvec는 행렬의 맨 오른쪽과 같이 등위 제약조건에 해당하는 1과 부등위 제약조건에 해당하는 0들로 구성되어 있습니다. 차후에 표준화 과정을 거쳐야 하므로 Duality 방법에서는 개별 자산의 투자비중이 1보다 작은 조건을 입력하지 않아도 됩니다.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="포트폴리오-구성.html#cb431-1"></a>result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)</span>
<span id="cb431-2"><a href="포트폴리오-구성.html#cb431-2"></a></span>
<span id="cb431-3"><a href="포트폴리오-구성.html#cb431-3"></a>w =<span class="st"> </span>result<span class="op">$</span>solution <span class="op">%&gt;%</span></span>
<span id="cb431-4"><a href="포트폴리오-구성.html#cb431-4"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb431-5"><a href="포트폴리오-구성.html#cb431-5"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb431-6"><a href="포트폴리오-구성.html#cb431-6"></a>  </span>
<span id="cb431-7"><a href="포트폴리오-구성.html#cb431-7"></a><span class="kw">print</span>(w)</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 17.001  1.199  4.617  0.000 26.176 37.925  2.864  0.000 
##    GLD    DBC 
##  7.859 11.959</code></pre>
<p>입력된 목적함수와 제약조건들을 바탕으로 <code>solve.QP()</code> 함수를 통해 최적화를 수행한 후 최대분산효과를 만족하는 해를 구해보면, 비중의 합이 1을 초과하게 됩니다. <span class="math inline">\(w_i = \frac{w_i}{\sum_{i=1}^nw_i}\)</span>를 통해 비중의 합이 1이 되도록 표준화를 해줍니다.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="포트폴리오-구성.html#cb433-1"></a>w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span></span>
<span id="cb433-2"><a href="포트폴리오-구성.html#cb433-2"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>)</span>
<span id="cb433-3"><a href="포트폴리오-구성.html#cb433-3"></a></span>
<span id="cb433-4"><a href="포트폴리오-구성.html#cb433-4"></a><span class="kw">print</span>(w)</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.1551 0.0109 0.0421 0.0000 0.2388 0.3460 0.0261 0.0000 
##    GLD    DBC 
## 0.0717 0.1091</code></pre>
<p>표준화 과정을 통해 비중의 합이 1이 되었습니다.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="포트폴리오-구성.html#cb435-1"></a><span class="kw">data.frame</span>(w) <span class="op">%&gt;%</span></span>
<span id="cb435-2"><a href="포트폴리오-구성.html#cb435-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),</span>
<span id="cb435-3"><a href="포트폴리오-구성.html#cb435-3"></a>                        <span class="dt">y =</span> w)) <span class="op">+</span></span>
<span id="cb435-4"><a href="포트폴리오-구성.html#cb435-4"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb435-5"><a href="포트폴리오-구성.html#cb435-5"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb435-6"><a href="포트폴리오-구성.html#cb435-6"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-29-1.png" width="50%" style="display: block; margin: auto;" /></p>
</div>
<div id="optimalportfolio-함수를-이용한-최적화-1" class="section level3">
<h3><span class="header-section-number">11.2.2</span> <code>optimalPortfolio()</code> 함수를 이용한 최적화</h3>
<p>최소분산 포트폴리오와 동일하게 <code>optimalPortfolio()</code> 함수를 이용해 매우 간단하게 최대분산효과 포트폴리오를 구현할 수 있습니다.</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="포트폴리오-구성.html#cb436-1"></a>w =<span class="st"> </span><span class="kw">optimalPortfolio</span>(covmat,</span>
<span id="cb436-2"><a href="포트폴리오-구성.html#cb436-2"></a>                     <span class="dt">control =</span> <span class="kw">list</span>(<span class="dt">type =</span> <span class="st">&#39;maxdiv&#39;</span>,</span>
<span id="cb436-3"><a href="포트폴리오-구성.html#cb436-3"></a>                                    <span class="dt">constraint =</span> <span class="st">&#39;lo&#39;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb436-4"><a href="포트폴리오-구성.html#cb436-4"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>)</span>
<span id="cb436-5"><a href="포트폴리오-구성.html#cb436-5"></a></span>
<span id="cb436-6"><a href="포트폴리오-구성.html#cb436-6"></a><span class="kw">print</span>(w)</span></code></pre></div>
<pre><code>##  [1] 0.1551 0.0109 0.0421 0.0000 0.2388 0.3460 0.0261
##  [8] 0.0000 0.0717 0.1091</code></pre>
<p>control 항목의 type에 maximum diversification을 의미하는 ’maxdiv’를 입력해주며, 제약조건에는 투자비중이 0보다 큰 lo(Long Only) 조건을 입력합니다. 패키지를 활용해 매우 간단하게 최대분산효과 포트폴리오를 구현할 수 있으며, 그 결과 또한 앞에서 계산한 것과 동일합니다. 해당 함수의 코드를 확인해보면, 최대분산효과 포트폴리오 계산 시 Min -DR 방법을 사용합니다.</p>
</div>
<div id="최소-및-최대-투자비중-제약조건-1" class="section level3">
<h3><span class="header-section-number">11.2.3</span> 최소 및 최대 투자비중 제약조건</h3>
<p>최대분산효과 포트폴리오 역시 구석해 문제가 발생하며, 모든 자산에 골고루 투자하기 위해 개별 투자비중을 최소 5%, 최대 20%로 하는 제약조건을 추가하겠습니다.</p>
<p>Duality 방법에서는 목적함수인 <span class="math inline">\(min\,^1/_2w&#39;\sigma w\)</span>과 제약조건인 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1, w_i \ge 0\)</span>에 맞게 해를 구한 후 비중의 합이 1이 되도록 표준화하는 과정을 거쳤습니다. 따라서 비중의 최소 및 최대 제약조건은 단순히 <span class="math inline">\(lb \le w_i \le ub\)</span>가 아닌 표준화 과정인 <span class="math inline">\(w_i = \frac{w_i}{\sum_{i=1}^nw_i}\)</span>까지 고려해 적용해야 합니다. 표 <a href="포트폴리오-구성.html#tab:mdpconst">11.11</a>는 이를 수식으로 나타낸 것입니다.</p>
<table class="table table" style="margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:mdpconst">표 11.11: </span>최소 및 최대비중 제약조건
</caption>
<thead>
<tr>
<th style="text-align:center;">
최소비중 제약조건
</th>
<th style="text-align:center;">
최대비중 제약조건
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
<span class="math inline">\(\frac{w_i}{\sum_{i=1}^nw_i} \ge lb\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\frac{w_i}{\sum_{i=1}^nw_i} \le ub\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow -lb + \frac{w_i}{\sum_{i=1}^nw_i} \ge 0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow ub - \frac{w_i}{\sum_{i=1}^nw_i} \ge 0\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow -lb + \frac{w_i}{e^Tw} \ge 0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow ub - \frac{w_i}{e^Tw} \ge 0\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow -lb \times e^Tw + w \ge 0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow ub \times e^Tw - w \ge 0\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow (-lb \times e^T + I)w \ge 0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(\Rightarrow (ub \times e^T - I)w \ge 0\)</span>
</td>
</tr>
</tbody>
</table>
<p>최소 비중 제약조건인 <span class="math inline">\(-lb \times e^T + I\)</span>의 예를 행렬로 풀어보도록 하겠습니다. <span class="math inline">\(-lb \times e^T\)</span>의 경우 행렬로 표현하면 다음과 같으며, <span class="math inline">\(-lb\)</span>로 이루어진 <span class="math inline">\(n \times n\)</span> 행렬입니다.</p>
<p><span class="math display">\[ \begin{bmatrix} -lb \\ \vdots \\ -lb \end{bmatrix}
\begin{bmatrix} 1 \\ \vdots \\ 1 \end{bmatrix}^T 
= \begin{bmatrix} -lb \\ \vdots \\ -lb \end{bmatrix}
\begin{bmatrix} 1 &amp; \dots &amp; 1 \end{bmatrix}  
= \begin{bmatrix} -lb &amp; \dots &amp; -lb \\ \vdots &amp; \ddots &amp; \vdots \\ -lb &amp; \dots &amp; -lb \end{bmatrix}\]</span></p>
<p><span class="math inline">\(I\)</span>는 대각선 부분이 1, 나머지가 0인 항등행렬을 의미합니다. 따라서 <span class="math inline">\((-lb \times e^T + I)\)</span>를 계산하면 다음과 같습니다.</p>
<p><span class="math display">\[\begin{bmatrix} -lb  + 1 &amp; \dots &amp; -lb \\ \vdots &amp; \ddots &amp; \vdots \\ -lb &amp; \dots &amp; -lb + 1 \end{bmatrix}\]</span></p>
<p>최소분산 포트폴리오와는 다르게 Duality 방법으로 최대분산효과 포트폴리오를 구현하면 최소 및 최대 제약조건이 우변이 아닌 좌변에 들어가게 되며, 해당 제약조건을 고려해 행렬로 표현하면 다음과 같습니다.</p>
<p><span class="math display">\[ \begin{bmatrix}
\sigma_1 &amp; \dots &amp; \sigma_{10} \\ -lb + 1 &amp; \dots &amp; -lb \\ \vdots &amp; \ddots &amp; \vdots \\
-lb &amp; \dots &amp; -lb + 1 \\ ub-1 &amp; \dots &amp;  ub \\ \vdots &amp; \ddots &amp; \vdots \\ ub &amp; \dots &amp; ub-1 \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} = 
\begin{bmatrix} \sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10} \\ -lb(w_1 + w_2 + \dots + w_{10}) + w_1 \\ \vdots \\ -lb(w_1 + w_2 + \dots + w_{10}) + w_{10} \\
wb(w_1 + w_2 + \dots + w_{10}) - w_1 \\ \vdots \\
ub(w_1 + w_2 + \dots + w_{10}) - w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix} \]</span></p>
<p>첫 번째 행 <span class="math inline">\(\sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10}\)</span>은 등위 제약조건인 <span class="math inline">\(\sum_{i=1}^n w_i \sigma_i = 1\)</span>에 해당하며, 두 번째 행부터는 부등위 제약조건에 해당합니다. 두 번째 행을 정리하면 <span class="math inline">\(\frac{w_1}{w_1+w_2+\dots+w_{10}} \ge lb\)</span>, 즉 비중의 표준화가 고려된 최소비중 제약조건입니다. 마지막 행 역시 정리하면 <span class="math inline">\(\frac{w_1}{w_1+w_2+\dots+w_{10}} \le ub\)</span>가 되어 비중의 표준화가 고려된 최대비중 제약조건을 의미합니다. 위 행렬을 고려해 Amat과 bvec을 수정한 코드는 다음과 같습니다.</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="포트폴리오-구성.html#cb438-1"></a>Dmat =<span class="st"> </span>covmat</span>
<span id="cb438-2"><a href="포트폴리오-구성.html#cb438-2"></a>dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb438-3"><a href="포트폴리오-구성.html#cb438-3"></a>Alb =<span class="st"> </span><span class="op">-</span><span class="kw">rep</span>(<span class="fl">0.05</span>, <span class="dv">10</span>) <span class="op">%*%</span><span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">+</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)</span>
<span id="cb438-4"><a href="포트폴리오-구성.html#cb438-4"></a>Aub =<span class="st"> </span><span class="kw">rep</span>(<span class="fl">0.20</span>, <span class="dv">10</span>) <span class="op">%*%</span><span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">-</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)</span>
<span id="cb438-5"><a href="포트폴리오-구성.html#cb438-5"></a></span>
<span id="cb438-6"><a href="포트폴리오-구성.html#cb438-6"></a>Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(covmat)), Alb, Aub))</span>
<span id="cb438-7"><a href="포트폴리오-구성.html#cb438-7"></a>bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>))</span>
<span id="cb438-8"><a href="포트폴리오-구성.html#cb438-8"></a>meq =<span class="st"> </span><span class="dv">1</span></span>
<span id="cb438-9"><a href="포트폴리오-구성.html#cb438-9"></a></span>
<span id="cb438-10"><a href="포트폴리오-구성.html#cb438-10"></a>result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)</span>
<span id="cb438-11"><a href="포트폴리오-구성.html#cb438-11"></a></span>
<span id="cb438-12"><a href="포트폴리오-구성.html#cb438-12"></a>w =<span class="st"> </span>result<span class="op">$</span>solution </span>
<span id="cb438-13"><a href="포트폴리오-구성.html#cb438-13"></a>w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span></span>
<span id="cb438-14"><a href="포트폴리오-구성.html#cb438-14"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb438-15"><a href="포트폴리오-구성.html#cb438-15"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb438-16"><a href="포트폴리오-구성.html#cb438-16"></a>  </span>
<span id="cb438-17"><a href="포트폴리오-구성.html#cb438-17"></a><span class="kw">print</span>(w)</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.0500 0.0500 0.0500 0.0500 0.2000 0.2000 0.0500 0.0500 
##    GLD    DBC 
## 0.1895 0.1105</code></pre>
<p>Alb의 -rep(0.05, 10)는 <span class="math inline">\(-lb\)</span> 부분, matrix(1, 1, 10)은 <span class="math inline">\(e^T\)</span> 부분, diag(10)부분은 <span class="math inline">\(I\)</span> 부분을 의미하며, 이는 최소비중 제약조건의 좌변(<span class="math inline">\(-lb \times e^T + I\)</span>)과 같습니다. 동일하게 Aub는 최대비중 제약조건의 좌변(<span class="math inline">\(ub \times e^T - I\)</span>)과 같으며, 결과를 확인하면 최소 및 최대비중 제약조건인 [5%, 20%]가 제대로 반영되었습니다.</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="포트폴리오-구성.html#cb440-1"></a><span class="kw">data.frame</span>(w) <span class="op">%&gt;%</span></span>
<span id="cb440-2"><a href="포트폴리오-구성.html#cb440-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(<span class="kw">rownames</span>(.), <span class="dt">levels =</span> <span class="kw">rownames</span>(.)),</span>
<span id="cb440-3"><a href="포트폴리오-구성.html#cb440-3"></a>                        <span class="dt">y =</span> w)) <span class="op">+</span></span>
<span id="cb440-4"><a href="포트폴리오-구성.html#cb440-4"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb440-5"><a href="포트폴리오-구성.html#cb440-5"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.05</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb440-6"><a href="포트폴리오-구성.html#cb440-6"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.20</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb440-7"><a href="포트폴리오-구성.html#cb440-7"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-32-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<div id="각-자산-별-제약조건의-추가" class="section level3">
<h3><span class="header-section-number">11.2.4</span> 각 자산 별 제약조건의 추가</h3>
<p>최소분산 포트폴리오와 동일하게 자산별로 다른 제약조건을 추가해 포트폴리오를 구성하겠습니다. 표 <a href="포트폴리오-구성.html#tab:mdpconst2">11.12</a>는 각 자산별 최소 및 최대 투자비중 값이며, 변경된 제약조건을 행렬의 형태로 나타내었습니다. 주의해야 할 점은 최소비중과 최대비중의 제약조건 추가 시 <span class="math inline">\(\frac{w_1}{w_1+w_2+\dots+w_{10}} \ge lb\)</span> 형태로 고려해야 한다는 점입니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:mdpconst2">표 11.12: </span>각 자산 별 최소 및 최대 제약조건
</caption>
<thead>
<tr>
<th style="text-align:center;">
제약
</th>
<th style="text-align:center;">
1
</th>
<th style="text-align:center;">
2
</th>
<th style="text-align:center;">
3
</th>
<th style="text-align:center;">
4
</th>
<th style="text-align:center;">
5
</th>
<th style="text-align:center;">
6
</th>
<th style="text-align:center;">
7
</th>
<th style="text-align:center;">
8
</th>
<th style="text-align:center;">
9
</th>
<th style="text-align:center;">
10
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
최소
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.03
</td>
<td style="text-align:center;">
0.03
</td>
</tr>
<tr>
<td style="text-align:center;">
최대
</td>
<td style="text-align:center;">
0.25
</td>
<td style="text-align:center;">
0.25
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.20
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.08
</td>
<td style="text-align:center;">
0.08
</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[ \scriptsize \begin{bmatrix}
 \sigma_1 &amp; \sigma_2 &amp; \dots &amp; \sigma_{10} \\ -lb_1 + 1 &amp; -lb_1 &amp; \dots &amp; -lb_1 \\ -lb_2  &amp; -lb_2 + 1 &amp; \dots &amp; -lb_2 \\ \vdots &amp; \ddots &amp; \dots &amp; \vdots \\
-lb_{10} &amp; -lb_{10} &amp; \dots &amp; -lb_{10} + 1 \\ ub_1 - 1 &amp; ub_1 &amp; \dots &amp; ub_1 \\ ub_2  &amp; ub_2 - 1 &amp; \dots &amp; ub_2 \\ \vdots &amp; \ddots &amp; \dots  &amp; \vdots \\
ub_{10} &amp; ub_{10} &amp; \dots &amp; ub_{10} - 1 \end{bmatrix}
\begin{bmatrix} w_1 \\ w_2 \\ \vdots \\ w_{10} \end{bmatrix} = 
\begin{bmatrix} \sigma_1w_1 + \sigma_2w_2 + \dots + \sigma_{10}w_{10} \\ -lb_1(w_1 + w_2 + \dots + w_{10}) + w_1 \\ -lb_2(w_1 + w_2 + \dots + w_{10}) + w_2\\ \vdots \\ -lb_{10}(w_1 + w_2 + \dots + w_{10}) + w_{10} \\
wb_1(w_1 + w_2 + \dots + w_{10}) - w_1 \\ wb_2(w_1 + w_2 + \dots + w_{10}) - w_2 \\ \vdots \\
ub_{10}(w_1 + w_2 + \dots + w_{10}) - w_{10}
\end{bmatrix} \ge \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix} \]</span></p>
<p>기존에 공통적으로 적용되던 최소 및 최대 투자비중이 자산별로 다르게 구성되었습니다. 따라서 <span class="math inline">\(-lb \times e^T + I\)</span>와 <span class="math inline">\(ub \times e^T - I\)</span>만 <span class="math inline">\(-lb_i \times e^T + I\)</span> <span class="math inline">\(ub_i \times e^T - I\)</span>로 수정하면 해당 제약조건 역시 손쉽게 구현이 가능합니다.</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="포트폴리오-구성.html#cb441-1"></a>Dmat =<span class="st"> </span>covmat</span>
<span id="cb441-2"><a href="포트폴리오-구성.html#cb441-2"></a>dvec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb441-3"><a href="포트폴리오-구성.html#cb441-3"></a>Alb =<span class="st"> </span><span class="op">-</span><span class="kw">c</span>(<span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>,</span>
<span id="cb441-4"><a href="포트폴리오-구성.html#cb441-4"></a>         <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.03</span>, <span class="fl">0.03</span>) <span class="op">%*%</span></span>
<span id="cb441-5"><a href="포트폴리오-구성.html#cb441-5"></a><span class="st">  </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">+</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)</span>
<span id="cb441-6"><a href="포트폴리오-구성.html#cb441-6"></a>Aub =<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>,</span>
<span id="cb441-7"><a href="포트폴리오-구성.html#cb441-7"></a>        <span class="fl">0.20</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.08</span>, <span class="fl">0.08</span>) <span class="op">%*%</span></span>
<span id="cb441-8"><a href="포트폴리오-구성.html#cb441-8"></a><span class="st">  </span><span class="kw">matrix</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">-</span><span class="st"> </span><span class="kw">diag</span>(<span class="dv">10</span>)</span>
<span id="cb441-9"><a href="포트폴리오-구성.html#cb441-9"></a></span>
<span id="cb441-10"><a href="포트폴리오-구성.html#cb441-10"></a>Amat =<span class="st"> </span><span class="kw">t</span>(<span class="kw">rbind</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(covmat)), Alb, Aub))</span>
<span id="cb441-11"><a href="포트폴리오-구성.html#cb441-11"></a>bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>))</span>
<span id="cb441-12"><a href="포트폴리오-구성.html#cb441-12"></a>meq =<span class="st"> </span><span class="dv">1</span></span>
<span id="cb441-13"><a href="포트폴리오-구성.html#cb441-13"></a></span>
<span id="cb441-14"><a href="포트폴리오-구성.html#cb441-14"></a>result =<span class="st"> </span><span class="kw">solve.QP</span>(Dmat, dvec, Amat, bvec, meq)</span>
<span id="cb441-15"><a href="포트폴리오-구성.html#cb441-15"></a></span>
<span id="cb441-16"><a href="포트폴리오-구성.html#cb441-16"></a>w =<span class="st"> </span>result<span class="op">$</span>solution </span>
<span id="cb441-17"><a href="포트폴리오-구성.html#cb441-17"></a>w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span></span>
<span id="cb441-18"><a href="포트폴리오-구성.html#cb441-18"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb441-19"><a href="포트폴리오-구성.html#cb441-19"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb441-20"><a href="포트폴리오-구성.html#cb441-20"></a>  </span>
<span id="cb441-21"><a href="포트폴리오-구성.html#cb441-21"></a><span class="kw">print</span>(w)</span></code></pre></div>
<pre><code>##  SPY  IEV  EWJ  EEM  TLT  IEF  IYR  RWX  GLD  DBC 
## 0.10 0.10 0.09 0.05 0.20 0.20 0.05 0.05 0.08 0.08</code></pre>
<p>최소 및 최대투자비중 제약조건을 나타내는 Alb와 Aub 부분이 자산별 각각의 제약비중으로 변경되었으며, 나머지 부분은 모두 동일합니다. 결괏값들이 모두 제약조건 내에 위치함을 확인할 수 있습니다.</p>
</div>
</div>
<div id="위험균형-포트폴리오" class="section level2">
<h2><span class="header-section-number">11.3</span> 위험균형 포트폴리오</h2>
<p>포트폴리오를 구성하는 자산들과 전체 위험의 관계를 이해하기 위해서는, 먼저 한계 위험기여도(MRC: Marginal Risk Contribution)와 위험기여도(RC: Risk Contribution)에 대해 알아야 합니다. 한계 위험기여도는 특정 자산의 비중을 한 단위 증가시켰을 때 전체 포트폴리오의 위험의 증가를 나타내는 단위로서, 수학의 편미분과 같은 개념입니다. <span class="math inline">\(i\)</span>번째 자산의 한계 위험기여도는 아래와 같이 나타낼 수 있습니다.</p>
<p><span class="math display">\[MRC_i = \frac{\partial\sigma_p}{\partial w_i} \]</span></p>
<p><span class="math inline">\(\sqrt {f&#39;(x)} = \frac{f&#39;(x)}{2\sqrt{f(x)}}\)</span>인 사실을 이용하면, 한계 위험기여도는 다음과 같이 풀 수 있습
니다. 결과적으로 분자는 분산-공분산 행렬과 각 자산의 비중의 곱, 분모는 포트폴리오의 표준편차 형태로 나타납니다.</p>
<p><span class="math display">\[\begin{equation*} 
\begin{split}
\frac{\partial\sigma_p}{\partial w} &amp; = \frac{\partial(\sqrt{w&#39;\Omega w})}{\partial w} \\
&amp; =\frac{\partial(w&#39;\Omega w)}{\partial w} \times \frac{1}{2\sqrt{w&#39;\Omega w}} \\
&amp; =\frac{2\Omega w}{2\sqrt{w&#39;\Omega w}} \\
&amp; =\frac{\Omega w}{\sqrt{w&#39;\Omega w}}
\end{split}
\end{equation*}\]</span></p>
<p>위험기여도는 특정 자산이 포트폴리오 내에서 차지하는 위험의 비중입니다. 한계 위험기여도가 큰 자산도 포트폴리오 내에서 비중이 작다면, 포트폴리오 내에서 차지하는 위험의 비중은 작을 것입니다. 반면에, 한계 위험기여도가 작은 자산일지라도 비중이 압도적으로 많다면, 포트폴리오 내에서 차지하는 위험의 비중은 클 것입니다.</p>
<p>결과적으로 <span class="math inline">\(i\)</span>번째 자산의 위험기여도는, <span class="math inline">\(i\)</span>번째 자산의 한계 위험기여도와 포트폴리오 내 비중의 곱으로 이루어집니다.</p>
<p><span class="math display">\[RC_i = \frac{\partial\sigma_p}{\partial w_i} \times w_i\]</span>
위험기여도를 코드로 나타내면 다음과 같습니다. 먼저 포트폴리오 비중인 <span class="math inline">\(w\)</span>와 분산-공분산 행렬인 covmat을 이용해 한계 위험기여도를 계산합니다. 그 후 비중 <span class="math inline">\(w\)</span>를 곱해 위험기여도를 계산해 준 후 합계가 1이 되도록 표준화를 해줍니다.</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="포트폴리오-구성.html#cb443-1"></a>get_RC =<span class="st"> </span><span class="cf">function</span>(w, covmat) {</span>
<span id="cb443-2"><a href="포트폴리오-구성.html#cb443-2"></a>  port_vol =<span class="st"> </span><span class="kw">t</span>(w) <span class="op">%*%</span><span class="st"> </span>covmat <span class="op">%*%</span><span class="st"> </span>w</span>
<span id="cb443-3"><a href="포트폴리오-구성.html#cb443-3"></a>  port_std =<span class="st"> </span><span class="kw">sqrt</span>(port_vol)</span>
<span id="cb443-4"><a href="포트폴리오-구성.html#cb443-4"></a>  </span>
<span id="cb443-5"><a href="포트폴리오-구성.html#cb443-5"></a>  MRC =<span class="st"> </span>(covmat <span class="op">%*%</span><span class="st"> </span>w) <span class="op">/</span><span class="st"> </span><span class="kw">as.numeric</span>(port_std)</span>
<span id="cb443-6"><a href="포트폴리오-구성.html#cb443-6"></a>  RC =<span class="st"> </span>MRC <span class="op">*</span><span class="st"> </span>w</span>
<span id="cb443-7"><a href="포트폴리오-구성.html#cb443-7"></a>  RC =<span class="st"> </span><span class="kw">c</span>(RC <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(RC))</span>
<span id="cb443-8"><a href="포트폴리오-구성.html#cb443-8"></a>  </span>
<span id="cb443-9"><a href="포트폴리오-구성.html#cb443-9"></a>  <span class="kw">return</span>(RC)</span>
<span id="cb443-10"><a href="포트폴리오-구성.html#cb443-10"></a>}</span></code></pre></div>
<div id="주식-60와-채권-40-포트폴리오의-위험기여도" class="section level3">
<h3><span class="header-section-number">11.3.1</span> 주식 60%와 채권 40% 포트폴리오의 위험기여도</h3>
<p>자산배분에서 가장 많이 사용되는 투자방법은 주식에 60%, 채권에 40% 가량의 비율로 투자하는 것입니다. 주식과 채권이 서로 상관관계가 낮아 분산효과가 있다는 점, 장기적으로 주식이 채권에 비해 장기적으로 수익률이 높다는 점을 감안하면 이는 꽤나 합리적인 방법으로 보입니다.</p>
<p>그러나 눈에 보이는 비중이 60대 40이라도, 포트폴리오 내에서 각 자산이 가지고 있는 위험기여도 60대 40의 비중이 아닌 전혀 다른 비중을 가지고 있습니다.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="포트폴리오-구성.html#cb444-1"></a>ret_stock_bond =<span class="st"> </span>rets[, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>)]</span>
<span id="cb444-2"><a href="포트폴리오-구성.html#cb444-2"></a>cov_stock_bond =<span class="st"> </span><span class="kw">cov</span>(ret_stock_bond)</span>
<span id="cb444-3"><a href="포트폴리오-구성.html#cb444-3"></a>RC_stock_bond =<span class="st"> </span><span class="kw">get_RC</span>(<span class="kw">c</span>(<span class="fl">0.6</span>, <span class="fl">0.4</span>), cov_stock_bond)</span>
<span id="cb444-4"><a href="포트폴리오-구성.html#cb444-4"></a>RC_stock_bond =<span class="st"> </span><span class="kw">round</span>(RC_stock_bond, <span class="dv">4</span>)</span>
<span id="cb444-5"><a href="포트폴리오-구성.html#cb444-5"></a></span>
<span id="cb444-6"><a href="포트폴리오-구성.html#cb444-6"></a><span class="kw">print</span>(RC_stock_bond)</span></code></pre></div>
<pre><code>## [1] 0.9764 0.0236</code></pre>
<p>rets 데이터에서 첫 번째 행은 미국 주식 수익률을, 다섯 번째 행은 미국 장기채를 의미하므로, 해당 부분을 ret_stock_bond 변수에 지정합니다. 그 후 <code>cov()</code> 함수를 이용해 두 자산의 분산-공분산 행렬을 만들어주며, 위에서 만든 get_RC 함수를 통해 자산별 위험기여도를 계산합니다.</p>
<p>주식과 채권이 가지는 위험기여도는 각각 97.64%, 2.36%로서 투자 비중인 60%, 40%와는 전혀 다른 위험 비중을 보입니다. 즉, 주식이 포트폴리오 위험의 대부분을 차지하고 있습니다.</p>
</div>
<div id="rp-함수를-이용한-최적화" class="section level3">
<h3><span class="header-section-number">11.3.2</span> <code>rp()</code> 함수를 이용한 최적화</h3>
<p>앞의 예제와 같이 특정 자산이 포트폴리오의 위험을 대부분 차지하는 문제를 막고, 모든 자산이 동일한 위험기여도를 가지는 포트폴리오가 위험균형 포트폴리오(Risk Parity Portfolio)<span class="citation">(Qian <a href="#ref-qian2011risk" role="doc-biblioref">2011</a>)</span> 혹은 동일 위험기여도 포트폴리오(Equal Risk Contribution Portfolio)입니다. 이를 수식으로 쓰면 다음과 같습니다.</p>
<p><span class="math display">\[RC_1 = RC_2 = \dots = RC_n\]</span>
<span class="math display">\[\frac{\partial\sigma_p}{\partial w_1} \times w_1 = \frac{\partial\sigma_p}{\partial w_2} \times w_2
= \dots = \frac{\partial\sigma_p}{\partial w_n} \times w_n = \frac{1}{n}\]</span></p>
<p>위험균형 포트폴리오 역시 <code>slsqp()</code>나 <code>optimalPortfolio()</code> 함수를 이용해 구현할 수 있으나, 간혹 최적화된 값을 찾지 못할 때도 있습니다. 반면 cccp 패키지의 rp() 함수를 사용하면 매우 정확하게 위험균형 포트폴리오를 구성하는 비중을 계산할 수 있습니다.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="포트폴리오-구성.html#cb446-1"></a><span class="kw">library</span>(cccp)</span>
<span id="cb446-2"><a href="포트폴리오-구성.html#cb446-2"></a></span>
<span id="cb446-3"><a href="포트폴리오-구성.html#cb446-3"></a>opt =<span class="st"> </span><span class="kw">rp</span>(<span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),</span>
<span id="cb446-4"><a href="포트폴리오-구성.html#cb446-4"></a>         <span class="dt">P =</span> covmat,</span>
<span id="cb446-5"><a href="포트폴리오-구성.html#cb446-5"></a>         <span class="dt">mrc =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>))</span></code></pre></div>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="포트폴리오-구성.html#cb447-1"></a>w =<span class="st"> </span><span class="kw">getx</span>(opt) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop</span>()</span>
<span id="cb447-2"><a href="포트폴리오-구성.html#cb447-2"></a>w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span></span>
<span id="cb447-3"><a href="포트폴리오-구성.html#cb447-3"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb447-4"><a href="포트폴리오-구성.html#cb447-4"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb447-5"><a href="포트폴리오-구성.html#cb447-5"></a></span>
<span id="cb447-6"><a href="포트폴리오-구성.html#cb447-6"></a><span class="kw">print</span>(w)</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.0600 0.0464 0.0565 0.0371 0.1748 0.3721 0.0394 0.0505 
##    GLD    DBC 
## 0.0868 0.0763</code></pre>
<ol style="list-style-type: decimal">
<li>x0은 최적화를 위한 초기 입력값이며 동일 비중인 10%씩을 입력합니다.</li>
<li>P는 분산-공분산 행렬을 입력해줍니다.</li>
<li>mrc는 목표로 하는 각 자산별 위험기여도 값<a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a>이며, 위험균형 포트폴리오의 경우 모든 자산의 위험기여도가 동일해야 하므로 10%씩을 입력합니다.</li>
</ol>
<p><code>rp()</code> 함수는 위 입력 변수를 바탕으로 최적해를 찾아줍니다. <code>getx()</code> 함수를 통해 해를 추출할 수 있으며, <code>drop()</code>을 통해 벡터 형태로 변환합니다. 마지막으로 비중의 합이 1이 되기 위해 비중들의 합으로 나눠줍니다.</p>
<p>최종적으로 계산된 비중이 위험균형 포트폴리오를 만족하는 해가 됩니다.</p>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="포트폴리오-구성.html#cb449-1"></a><span class="kw">get_RC</span>(w, covmat)</span></code></pre></div>
<pre><code>##  [1] 0.10004 0.09991 0.10003 0.10008 0.10004 0.10007
##  [7] 0.09991 0.10001 0.09998 0.09994</code></pre>
<p><code>get_RC()</code> 함수를 통해 위험기여도를 확인해보면, 모든 자산이 거의 동일한 위험기여도를 가지는 것을 알 수 있습니다.</p>
</div>
<div id="위험예산-포트폴리오" class="section level3">
<h3><span class="header-section-number">11.3.3</span> 위험예산 포트폴리오</h3>
<p>모든 자산의 위험기여도가 동일한 값이 아닌, 자산별로 다른 위험기여도를 가지는 포트폴리오를 구성해야 할 경우도 있습니다. 이러한 포트폴리오를 위험예산 포트폴리오(Risk Budget Portfolio)라고 합니다. 위험균형 포트폴리오 역시 각 자산의 위험예산이 <span class="math inline">\(\frac{1}{n}\)</span>로 동일한 특수 형태이며, <code>rp()</code> 함수를 이용하면 위험예산 포트폴리오 역시 손쉽게 구현할 수 있습니다.</p>
<p>먼저 각 자산 별 위험예산을 표 <a href="포트폴리오-구성.html#tab:rb">11.13</a>과 같이 정합니다. 1~4번 자산은 각각 15%씩, 5~6번 자산은 각각 10%씩, 7~10번 자산은 각각 5%씩 위험예산을 부여하고자 합니다.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:rb">표 11.13: </span>위험예산 포트폴리오 예시
</caption>
<thead>
<tr>
<th style="text-align:center;">
자산
</th>
<th style="text-align:center;">
1
</th>
<th style="text-align:center;">
2
</th>
<th style="text-align:center;">
3
</th>
<th style="text-align:center;">
4
</th>
<th style="text-align:center;">
5
</th>
<th style="text-align:center;">
6
</th>
<th style="text-align:center;">
7
</th>
<th style="text-align:center;">
8
</th>
<th style="text-align:center;">
9
</th>
<th style="text-align:center;">
10
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
예산
</td>
<td style="text-align:center;">
0.15
</td>
<td style="text-align:center;">
0.15
</td>
<td style="text-align:center;">
0.15
</td>
<td style="text-align:center;">
0.15
</td>
<td style="text-align:center;">
0.1
</td>
<td style="text-align:center;">
0.1
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.05
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="포트폴리오-구성.html#cb451-1"></a><span class="kw">library</span>(cccp)</span>
<span id="cb451-2"><a href="포트폴리오-구성.html#cb451-2"></a></span>
<span id="cb451-3"><a href="포트폴리오-구성.html#cb451-3"></a>opt =<span class="st"> </span><span class="kw">rp</span>(<span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="fl">0.1</span>, <span class="dv">10</span>),</span>
<span id="cb451-4"><a href="포트폴리오-구성.html#cb451-4"></a>         <span class="dt">P =</span> covmat,</span>
<span id="cb451-5"><a href="포트폴리오-구성.html#cb451-5"></a>         <span class="dt">mrc =</span> <span class="kw">c</span>(<span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="fl">0.10</span>,</span>
<span id="cb451-6"><a href="포트폴리오-구성.html#cb451-6"></a>                 <span class="fl">0.10</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>))</span></code></pre></div>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="포트폴리오-구성.html#cb452-1"></a>w =<span class="st"> </span><span class="kw">getx</span>(opt) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop</span>()</span>
<span id="cb452-2"><a href="포트폴리오-구성.html#cb452-2"></a>w =<span class="st"> </span>(w <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(w)) <span class="op">%&gt;%</span></span>
<span id="cb452-3"><a href="포트폴리오-구성.html#cb452-3"></a><span class="st">  </span><span class="kw">round</span>(., <span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb452-4"><a href="포트폴리오-구성.html#cb452-4"></a><span class="st">  </span><span class="kw">setNames</span>(<span class="kw">colnames</span>(rets))</span>
<span id="cb452-5"><a href="포트폴리오-구성.html#cb452-5"></a></span>
<span id="cb452-6"><a href="포트폴리오-구성.html#cb452-6"></a><span class="kw">print</span>(w)</span></code></pre></div>
<pre><code>##    SPY    IEV    EWJ    EEM    TLT    IEF    IYR    RWX 
## 0.0843 0.0663 0.0781 0.0529 0.1823 0.3934 0.0197 0.0250 
##    GLD    DBC 
## 0.0543 0.0437</code></pre>
<p>mrc에 목표로 하는 각 자산별 위험기여도를 입력하며, 나머지는 기존 위험균형 포트폴리오와 동일하게 입력합니다.</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="포트폴리오-구성.html#cb454-1"></a><span class="kw">get_RC</span>(w, covmat)</span></code></pre></div>
<pre><code>##  [1] 0.15006 0.15000 0.15007 0.15003 0.09989 0.09991
##  [7] 0.05009 0.04995 0.05003 0.04997</code></pre>
<p><code>get_RC()</code> 함수를 통해 위험기여도를 확인해보면 우리가 원하던 자산별 위험예산과 거의 동일한 것을 알 수 있습니다.</p>
</div>
</div>
<div id="인덱스-포트폴리오-구성하기" class="section level2">
<h2><span class="header-section-number">11.4</span> 인덱스 포트폴리오 구성하기</h2>
<p>이번에는 실제로 운용사에서 많이 사용되는 인덱스 포트폴리오 및 인핸스드 인덱스 포트폴리오 구성법에 대해 살펴보겠습니다.</p>
<p>투자는 크게 액티브 전략과 패시브 전략으로 나뉩니다. 액티브 전략이 벤치마크 대비 초과수익을 거두기 위해 적극적으로 투자를 하는 반면, 패시브 전략은 벤치마크를 그대로 추종하는 것을 목표로 합니다. 예를 들어 벤치마크가 2% 상승하였을 경우 액티브 전략은 이를 넘어서는 수익률을 얻고자 하지만, 패시브 전략은 정확히 2%의 수익률을 얻고자 합니다. 이러한 패시브 전략을 사용하는 펀드가 패시브 펀드 혹은 인덱스 펀드입니다.</p>
<p>흔히 벤치마크가 되는 지수(Index) 중 가장 많이 사용되는 것은 각 국가의 주가지수이며, 우리나라의 경우 <strong>KOSPI200</strong> 지수가 그 예입니다. 이 외에도 여러 국가를 대표하는 주가지수는 표 <a href="포트폴리오-구성.html#tab:index">11.14</a> 와 같습니다.</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:index">표 11.14: </span>각 국가의 대표 주가지수
</caption>
<thead>
<tr>
<th style="text-align:center;">
국가
</th>
<th style="text-align:center;">
지수명
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
미국
</td>
<td style="text-align:center;">
S&amp;P 500
</td>
</tr>
<tr>
<td style="text-align:center;">
영국
</td>
<td style="text-align:center;">
FTSE 100
</td>
</tr>
<tr>
<td style="text-align:center;">
일본
</td>
<td style="text-align:center;">
Nikkei 225
</td>
</tr>
<tr>
<td style="text-align:center;">
중국
</td>
<td style="text-align:center;">
CSI 300
</td>
</tr>
<tr>
<td style="text-align:center;">
한국
</td>
<td style="text-align:center;">
KOSPI 200
</td>
</tr>
</tbody>
</table>
<div id="시가총액비중-계산하기" class="section level3">
<h3><span class="header-section-number">11.4.1</span> 시가총액비중 계산하기</h3>
<p>주가지수는 대부분 각 주식의 시가총액비중을 이용해 구성되며, 간단한 예제는 표 <a href="포트폴리오-구성.html#tab:capexam">11.15</a>와 같습니다.</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:capexam">표 11.15: </span>시가총액비중 계산 예시
</caption>
<thead>
<tr>
<th style="text-align:center;">
종목
</th>
<th style="text-align:center;">
주가
</th>
<th style="text-align:center;">
상장 주식수
</th>
<th style="text-align:center;">
유동비
</th>
<th style="text-align:center;">
시가총액
</th>
<th style="text-align:center;">
지수 내 비중
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
A
</td>
<td style="text-align:center;">
40,000
</td>
<td style="text-align:center;">
4,000,000
</td>
<td style="text-align:center;">
70%
</td>
<td style="text-align:center;">
112,000,000,000
</td>
<td style="text-align:center;">
44.80%
</td>
</tr>
<tr>
<td style="text-align:center;">
B
</td>
<td style="text-align:center;">
50,000
</td>
<td style="text-align:center;">
3,000,000
</td>
<td style="text-align:center;">
60%
</td>
<td style="text-align:center;">
90,000,000,000
</td>
<td style="text-align:center;">
36.00%
</td>
</tr>
<tr>
<td style="text-align:center;">
C
</td>
<td style="text-align:center;">
30,000
</td>
<td style="text-align:center;">
2,000,000
</td>
<td style="text-align:center;">
80%
</td>
<td style="text-align:center;">
48,000,000,000
</td>
<td style="text-align:center;">
19.20%
</td>
</tr>
<tr>
<td style="text-align:center;">
합계
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
250,000,000,000
</td>
<td style="text-align:center;">
100.00%
</td>
</tr>
</tbody>
</table>
<p>일반적으로 시가총액은 [주가 X 상장 주식수]로 계산됩니다. 그러나 자사주 등의 이유로 기업의 상장된 모든 주식이 거래가 되는 것은 아니며, 상장된 주식 중 유동적으로 거래되는 비율을 <strong>유동비</strong>라고 합니다. 따라서 지수를 구성할 때는 시가총액을 [주가 X 상장 주식수 X 유동비]로 계산합니다. 이렇게 계산된 각 기업의 시가총액을 전체 시가총액의 합으로 나누어 지수 내 비중을 계산합니다.</p>
</div>
<div id="인덱스-포트폴리오-복제하기" class="section level3">
<h3><span class="header-section-number">11.4.2</span> 인덱스 포트폴리오 복제하기</h3>
<p>이번에는 앞서 구한 데이터를 바탕으로 KOSPI 200 지수를 복제하는 예제를 살펴보겠습니다. 해당 지수의 산출 방법은 다음과 같습니다.</p>
<div style="color:blue">
<p>한국거래소 유가증권시장(Stock Market)의 보통주 전 종목 가운데 시장 대표성, 유동성(거래량), 업종 대표성(업종은 9개 업종으로 구분)을 기준으로 한다. 즉 시가총액이 상위군에 속하고 거래량이 많은 종목 서열에 따른 200 종목이 편입된다.</p>
</div>
<p>즉 일정 규칙에 따라 200 종목이 선정되고, 각 종목들의 시가총액비중 만큼을 지수 내 비중으로 가지고 갑니다. 물론 선정된 200 종목이 단순하게 시가총액의 순서대로 선택되는 것은 아니며, 유동비의 경우 지수제공업체인 한국거래소에서 유료로 제공하므로 이를 구매하지 않는 이상 정확하게 알 수 없습니다. 그러나 지수 내 종목 및 대략의 시가총액비중은 해당 지수를 추종하는 ETF(예: KODEX 200)의 PDF를 통해 확인할 수 있으며, 본 책에서는 편의를 위해 시가총액상위 200 종목을 선택하고 유동비는 모두 100%로 가정하겠습니다.</p>
<p>앞서 구한 데이터를 이용해 상위 200 종목의 시가총액비중을 계산해보도록 하겠습니다.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="포트폴리오-구성.html#cb456-1"></a><span class="kw">library</span>(stringr)</span>
<span id="cb456-2"><a href="포트폴리오-구성.html#cb456-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb456-3"><a href="포트폴리오-구성.html#cb456-3"></a></span>
<span id="cb456-4"><a href="포트폴리오-구성.html#cb456-4"></a>KOR_ticker =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;data/KOR_ticker.csv&#39;</span>,</span>
<span id="cb456-5"><a href="포트폴리오-구성.html#cb456-5"></a>                      <span class="dt">row.names =</span> <span class="dv">1</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>) </span>
<span id="cb456-6"><a href="포트폴리오-구성.html#cb456-6"></a></span>
<span id="cb456-7"><a href="포트폴리오-구성.html#cb456-7"></a>KOSPI200 =<span class="st"> </span>KOR_ticker <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(시장구분 <span class="op">==</span><span class="st"> &#39;코스피&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb456-8"><a href="포트폴리오-구성.html#cb456-8"></a><span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">200</span>) <span class="op">%&gt;%</span></span>
<span id="cb456-9"><a href="포트폴리오-구성.html#cb456-9"></a><span class="st">  </span><span class="kw">rename</span>(<span class="st">`</span><span class="dt">시가총액</span><span class="st">`</span> =<span class="st"> `</span><span class="dt">시가총액.원.</span><span class="st">`</span>) <span class="op">%&gt;%</span></span>
<span id="cb456-10"><a href="포트폴리오-구성.html#cb456-10"></a><span class="st">  </span><span class="kw">mutate</span>(시가총액비중 =<span class="st"> </span>시가총액 <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(시가총액))</span></code></pre></div>
<ol style="list-style-type: decimal">
<li>저장해둔 티커 정보를 불러옵니다.</li>
<li><code>filter()</code> 함수를 통해 코스피 시장에 해당하는 종목만을 선택합니다.</li>
<li><code>slice()</code> 함수를 통해 1번부터 200번 행 까지 데이터를 선택합니다.</li>
<li><code>rename()</code> 함수를 통해 열 이름을 바꿔 줍니다.</li>
<li>각 주식의 시가총액을 전체 시가총액으로 나눈 후, 시가총액비중에 저장합니다.</li>
</ol>
<p>계산된 시가총액비중을 시각화하도록 하겠습니다.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="포트폴리오-구성.html#cb457-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb457-2"><a href="포트폴리오-구성.html#cb457-2"></a></span>
<span id="cb457-3"><a href="포트폴리오-구성.html#cb457-3"></a>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb457-4"><a href="포트폴리오-구성.html#cb457-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 시가총액비중)) <span class="op">+</span></span>
<span id="cb457-5"><a href="포트폴리오-구성.html#cb457-5"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb457-6"><a href="포트폴리오-구성.html#cb457-6"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb457-7"><a href="포트폴리오-구성.html#cb457-7"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;시가총액비중(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb457-8"><a href="포트폴리오-구성.html#cb457-8"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent)</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-43-1.png" width="70%" style="display: block; margin: auto;" /></p>
<ol style="list-style-type: decimal">
<li><code>ggplot()</code> 함수를 이용해 시각화를 해주도록 하며, <code>reorder()</code>를 통해 시가총액비중으로 <span class="math inline">\(x\)</span>축을 정리합니다.</li>
<li><code>geom_point()</code> 함수를 통해 산점도를 나타냅니다.</li>
<li><span class="math inline">\(x\)</span>축과 <span class="math inline">\(y\)</span>축의 이름을 변경합니다.</li>
<li><code>scale_y_continuous()</code> 함수 내 scales::percent 인자를 입력하여 <span class="math inline">\(y\)</span> 축을 퍼센트 형식으로 변경합니다.</li>
</ol>
<p>위 과정을 통해 코스피 시가총액 상위 200 종목의 시가총액비중을 계산 및 시각화 하였습니다. 그러나 <span class="math inline">\(x\)</span>축에 해당하는 종목이 200개나 되어 종목명이 잘 보이지 않으며, 국내의 경우 삼성전자의 시가총액비중이 지나치게 커 다른 종목들의 비중이 잘 보이지 않습니다. 이를 고려하여 그림을 다시 수정해주도록 합니다.</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="포트폴리오-구성.html#cb458-1"></a>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb458-2"><a href="포트폴리오-구성.html#cb458-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 시가총액비중)) <span class="op">+</span></span>
<span id="cb458-3"><a href="포트폴리오-구성.html#cb458-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb458-4"><a href="포트폴리오-구성.html#cb458-4"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb458-5"><a href="포트폴리오-구성.html#cb458-5"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;시가총액비중(로그 스케일링)&#39;</span>) <span class="op">+</span></span>
<span id="cb458-6"><a href="포트폴리오-구성.html#cb458-6"></a><span class="st">  </span><span class="kw">scale_y_log10</span>() <span class="op">+</span></span>
<span id="cb458-7"><a href="포트폴리오-구성.html#cb458-7"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">5</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb458-8"><a href="포트폴리오-구성.html#cb458-8"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-44-1.png" width="70%" style="display: block; margin: auto;" /></p>
<ol style="list-style-type: decimal">
<li><code>scale_y_log10()</code> 함수를 통해 <span class="math inline">\(y\)</span>축을 로그값으로 스케일링 하였습니다.</li>
<li><code>scale_x_discrete()</code> 함수를 통해 <span class="math inline">\(x\)</span>축에 일부 종목만을 표현하였습니다.</li>
<li><code>theme()</code> 내부에 <code>element_text()</code> 인자를 통해 <span class="math inline">\(x\)</span>축 글자를 회전시키고 위치를 조정하였습니다.</li>
</ol>
<p>다음으로 만일 여러분에게 1억이 있을 경우 KOSPI 200을 복제하는 방법을 알아보겠습니다.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="포트폴리오-구성.html#cb459-1"></a>KOSPI200 =<span class="st"> </span>KOSPI200 <span class="op">%&gt;%</span></span>
<span id="cb459-2"><a href="포트폴리오-구성.html#cb459-2"></a><span class="st">  </span><span class="kw">mutate</span>(매수금액 =<span class="st"> </span><span class="dv">100000000</span> <span class="op">*</span><span class="st"> </span>시가총액비중,</span>
<span id="cb459-3"><a href="포트폴리오-구성.html#cb459-3"></a>             매수주수 =<span class="st"> </span>매수금액 <span class="op">/</span><span class="st"> `</span><span class="dt">현재가.종가.</span><span class="st">`</span>)</span>
<span id="cb459-4"><a href="포트폴리오-구성.html#cb459-4"></a></span>
<span id="cb459-5"><a href="포트폴리오-구성.html#cb459-5"></a>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(매수금액, 매수주수) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</span></code></pre></div>
<pre><code>##   매수금액 매수주수
## 1 26142166  354.230
## 2  5075716   43.198
## 3  3430585    4.189
## 4  3168316    3.926
## 5  2831671    8.010
## 6  2782746    9.747</code></pre>
<p>여러분이 가지고 있는 금액에 시가총액비중을 곱해 각 주식당 매수해야 하는 금액을 구합니다. 그 후 각 금액을 현재가로 나누어 매수해야 하는 주식의 수를 계산합니다.</p>
<p>이론적으로는 계산된 주식수만큼 매수하여야 인덱스를 정확히 복제합니다. 그러나 주식은 1주 단위로 거래할 수 있으므로 소수점 단위로는 거래할 수는 없습니다. 만일 매수주수를 올림처리할 경우 총 매수금액이 보유금액보다 많이질 수 있으므로, 내림처리를 통해 매수주수를 수정해줍니다.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="포트폴리오-구성.html#cb461-1"></a>KOSPI200 =<span class="st"> </span>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(매수주수 =<span class="st"> </span><span class="kw">floor</span>(매수주수))</span>
<span id="cb461-2"><a href="포트폴리오-구성.html#cb461-2"></a>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(매수금액, 매수주수) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</span></code></pre></div>
<pre><code>##   매수금액 매수주수
## 1 26142166      354
## 2  5075716       43
## 3  3430585        4
## 4  3168316        3
## 5  2831671        8
## 6  2782746        9</code></pre>
<p><code>floor()</code> 함수를 통해 내림처리를 하였으며, 각 주수만큼 매수할 경우 KOSPI 200 지수를 매우 유사하게 복제할 수 있습니다.</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="포트폴리오-구성.html#cb463-1"></a>inv_money =<span class="st"> </span>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(실제매수금액 =<span class="st"> `</span><span class="dt">현재가.종가.</span><span class="st">`</span> <span class="op">*</span><span class="st"> </span>매수주수) <span class="op">%&gt;%</span></span>
<span id="cb463-2"><a href="포트폴리오-구성.html#cb463-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">sum</span>(실제매수금액))</span>
<span id="cb463-3"><a href="포트폴리오-구성.html#cb463-3"></a></span>
<span id="cb463-4"><a href="포트폴리오-구성.html#cb463-4"></a><span class="kw">print</span>(inv_money)</span></code></pre></div>
<pre><code>##   sum(실제매수금액)
## 1          89387460</code></pre>
<p>주수를 내림 처리하였으므로 실제 매수에 사용되는 금액은 1억원 보다 약간 모자르게 되며, 1억과 해당금액의 차이는 현금으로 보유하거나 해당 지수를 추종하는 ETF 및 펀드 투자에 사용해도 됩니다.</p>
</div>
<div id="팩터를-이용한-인핸스드-포트폴리오-구성하기" class="section level3">
<h3><span class="header-section-number">11.4.3</span> 팩터를 이용한 인핸스드 포트폴리오 구성하기</h3>
<p>위 방법을 통해 포트폴리오를 구성할 경우 이론적으로는 벤치마크와 수익률이 거의 동일합니다. 그러나 약간의 위험을 감수하여 벤치마크 대비 미세한 초과수익을 원하는 수요가 존재하며, 이러한 펀드가 <strong>인핸스드 인덱스 펀드</strong>입니다. 이를 위해 층화추출법, 비중조절법, 차익거래 등의 전략이 활용되며, 본 책에서는 가장 널리 사용되는 비중조절법에 대해 알아보겠습니다. 그 예제로써 PBR을 이용해 시가총액비중을 조절해보도록 하겠습니다.</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="포트폴리오-구성.html#cb465-1"></a>KOSPI200 =<span class="st"> </span>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(종목명, PBR, 시가총액비중) <span class="op">%&gt;%</span></span>
<span id="cb465-2"><a href="포트폴리오-구성.html#cb465-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">PBR =</span> <span class="kw">as.numeric</span>(PBR)) </span></code></pre></div>
<p>먼저 필요한 종목코드, 종목명, PBR, 시가총액비중 열만 선택합니다. 그 후 문자열 형태의 PBR을 숫자 형태로 변경해주며, PBR 데이터가 없어 [-]로 표시되었던 종목의 PBR은 NA로 변경됩니다.</p>
<div id="단순-가감법" class="section level4">
<h4><span class="header-section-number">11.4.3.1</span> 단순 가감법</h4>
<p>먼저 가장 손쉬운 방법은 PBR의 랭킹을 구한 후, PBR이 낮은 상위 n개 종목에는 일정 비중씩을 더하며, 나머지 종목들에서 해당 비중만큼을 빼는 방법입니다. 몇개의 종목에서 얼마씩의 비중을 조절할지는 투자자의 재량에 달렸으며, 본 예제에서는 상위 100 종목에 각각 5bp를 더해주며, 나머지 100 종목에서 각각 5bp를 빼주도록 하겠습니다.</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="포트폴리오-구성.html#cb466-1"></a>KOSPI200 =<span class="st"> </span>KOSPI200 <span class="op">%&gt;%</span></span>
<span id="cb466-2"><a href="포트폴리오-구성.html#cb466-2"></a><span class="st">  </span><span class="kw">mutate</span>(랭킹 =<span class="st"> </span><span class="kw">rank</span>(PBR),</span>
<span id="cb466-3"><a href="포트폴리오-구성.html#cb466-3"></a>           조절비중 =<span class="st"> </span><span class="kw">ifelse</span>(랭킹 <span class="op">&lt;=</span><span class="st"> </span><span class="dv">100</span>, 시가총액비중 <span class="op">+</span><span class="st"> </span><span class="fl">0.0005</span>, 시가총액비중 <span class="op">-</span><span class="st"> </span><span class="fl">0.0005</span>),</span>
<span id="cb466-4"><a href="포트폴리오-구성.html#cb466-4"></a>           조절비중 =<span class="st"> </span><span class="kw">ifelse</span>(조절비중 <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dv">0</span>, 조절비중),</span>
<span id="cb466-5"><a href="포트폴리오-구성.html#cb466-5"></a>           조절비중 =<span class="st"> </span>조절비중 <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(조절비중),</span>
<span id="cb466-6"><a href="포트폴리오-구성.html#cb466-6"></a>           차이 =<span class="st"> </span>조절비중 <span class="op">-</span><span class="st"> </span>시가총액비중) </span></code></pre></div>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="포트폴리오-구성.html#cb467-1"></a><span class="kw">library</span>(tidyr)</span>
<span id="cb467-2"><a href="포트폴리오-구성.html#cb467-2"></a></span>
<span id="cb467-3"><a href="포트폴리오-구성.html#cb467-3"></a><span class="kw">head</span>(KOSPI200)</span></code></pre></div>
<pre><code>##             종목명   PBR 시가총액비중  랭킹 조절비중
## 1         삼성전자  1.97      0.26142 126.5  0.26090
## 2       SK하이닉스  1.78      0.05076 120.0  0.05025
## 3           LG화학  3.77      0.03431 159.0  0.03380
## 4 삼성바이오로직스 12.26      0.03168 189.0  0.03118
## 5         셀트리온 17.00      0.02832 193.0  0.02781
## 6            NAVER  8.11      0.02783 185.0  0.02733
##         차이
## 1 -0.0005188
## 2 -0.0005036
## 3 -0.0005024
## 4 -0.0005022
## 5 -0.0005020
## 6 -0.0005020</code></pre>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="포트폴리오-구성.html#cb469-1"></a><span class="kw">tail</span>(KOSPI200)</span></code></pre></div>
<pre><code>##               종목명  PBR 시가총액비중  랭킹  조절비중
## 195       한미반도체 4.14    0.0004859 164.0 0.0000000
## 196 동아쏘시오홀딩스 1.08    0.0004784  92.0 0.0009784
## 197         동원산업 0.77    0.0004768  68.5 0.0009767
## 198             풍산 0.58    0.0004739  36.5 0.0009739
## 199           에스엘 0.58    0.0004719  36.5 0.0009719
## 200       신성이엔지 5.58    0.0004682 174.0 0.0000000
##           차이
## 195 -0.0004859
## 196  0.0004999
## 197  0.0004999
## 198  0.0004999
## 199  0.0004999
## 200 -0.0004682</code></pre>
<ol style="list-style-type: decimal">
<li><code>rank()</code> 함수를 통해 PBR의 랭킹을 구합니다.</li>
<li>랭킹이 100 이하일 시, 즉 저PBR 100개 종목에는 시가총액비중에서 5bp씩을 더해주며, 반대로 고PBR 100개 종목에는 5bp 씩을 빼줍니다.</li>
<li>시가총액비중이 5bp 미만인 종목에서 5bp를 차감할 경우 비중이 0 미만이 되므로, 이러한 경우는 투자비중을 0으로 만들어 줍니다.</li>
<li>3번 결과에 따라 비중의 합이 1과 다르게 되므로, 각각의 비중을 합으로 나누어 값을 다시 계산해 줍니다.</li>
<li>시가총액비중과 조절비중의 차이를 계산합니다.</li>
</ol>
<p>PBR 랭킹이 100 미만인 종목, 즉 저PBR 종목은 시가총액비중 대비 투자비중이 많으며, 이와 반대로 고PBR 종목은 시가총액비중 대비 투자비중이 작습니다. 즉 장기적으로 저PBR 종목이 고PBR 종목 대비 우수한 성과를 보일 경우, 저PBR 종목에 더 높은 비중을 준 해당 포트폴리오 역시 벤치마크 대비 우수한 성과를 기록할 수 있을 것입니다.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="포트폴리오-구성.html#cb471-1"></a>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb471-2"><a href="포트폴리오-구성.html#cb471-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 시가총액비중)) <span class="op">+</span></span>
<span id="cb471-3"><a href="포트폴리오-구성.html#cb471-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb471-4"><a href="포트폴리오-구성.html#cb471-4"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> KOSPI200, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 조절비중),</span>
<span id="cb471-5"><a href="포트폴리오-구성.html#cb471-5"></a>             <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">shape =</span> <span class="dv">4</span>) <span class="op">+</span></span>
<span id="cb471-6"><a href="포트폴리오-구성.html#cb471-6"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb471-7"><a href="포트폴리오-구성.html#cb471-7"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;비중(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb471-8"><a href="포트폴리오-구성.html#cb471-8"></a><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.03</span>)) <span class="op">+</span></span>
<span id="cb471-9"><a href="포트폴리오-구성.html#cb471-9"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">5</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb471-10"><a href="포트폴리오-구성.html#cb471-10"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent) <span class="op">+</span></span>
<span id="cb471-11"><a href="포트폴리오-구성.html#cb471-11"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-51-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>검은색 점은 인덱스 내 시가총액비중이며, 붉은색 엑스표시는 5bp씩 더하거나 뺀 투자비중입니다. 약간씩의 베팅만 했으므로 기초지수와 크게 차이가 없습니다.</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="포트폴리오-구성.html#cb472-1"></a>KOSPI200_mod =<span class="st"> </span>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(PBR)</span>
<span id="cb472-2"><a href="포트폴리오-구성.html#cb472-2"></a></span>
<span id="cb472-3"><a href="포트폴리오-구성.html#cb472-3"></a>KOSPI200_mod <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb472-4"><a href="포트폴리오-구성.html#cb472-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, PBR), <span class="dt">y =</span> 차이)) <span class="op">+</span></span>
<span id="cb472-5"><a href="포트폴리오-구성.html#cb472-5"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb472-6"><a href="포트폴리오-구성.html#cb472-6"></a><span class="st">  </span><span class="kw">geom_col</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, PBR), <span class="dt">y =</span> PBR <span class="op">/</span><span class="dv">10000</span>), <span class="dt">fill =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">alpha =</span> <span class="fl">0.2</span>) <span class="op">+</span></span>
<span id="cb472-7"><a href="포트폴리오-구성.html#cb472-7"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb472-8"><a href="포트폴리오-구성.html#cb472-8"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;차이(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb472-9"><a href="포트폴리오-구성.html#cb472-9"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent, </span>
<span id="cb472-10"><a href="포트폴리오-구성.html#cb472-10"></a>                     <span class="dt">sec.axis =</span> <span class="kw">sec_axis</span>(<span class="op">~</span>. <span class="op">*</span><span class="st"> </span><span class="dv">10000</span>, <span class="dt">name =</span> <span class="st">&quot;PBR&quot;</span>)) <span class="op">+</span></span>
<span id="cb472-11"><a href="포트폴리오-구성.html#cb472-11"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200_mod[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">10</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb472-12"><a href="포트폴리오-구성.html#cb472-12"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-52-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>PBR 기준 오름차순을 한 후 그림을 그려보면, PBR이 낮은 종목에는 비중이 추가되며 PBR이 높은 종목에는 비중이 감소되는 것이 쉽게 확인됩니다.</p>
</div>
<div id="팩터에-대한-전체-종목의-틸트" class="section level4">
<h4><span class="header-section-number">11.4.3.2</span> 팩터에 대한 전체 종목의 틸트</h4>
<p>위 방법의 경우 상위 종목과 하위 종목에 동일한 비중을 더하거나 빼주었습니다. 그러나 팩터가 강한 종목의 경우 더욱 많은 비중을 더하고, 팩터가 약한 종목의 경우 더욱 많은 비중을 빼는 등 훨씬 적극적으로 포트폴리오를 구성할 수도 있습니다. 이를 위해서는 먼저 확률밀도함수와 누적분포함수를 이해해야 합니다.</p>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-53-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>파란색 선은 확률밀도함수로써, 각 <span class="math inline">\(x\)</span>축에 대한 확률값을 나타냅니다. 빨간색 선은 누적분포함수로써, 각 <span class="math inline">\(x\)</span>축이 오른쪽으로 이동함에 따른 분포의 누적확률을 계산합니다. 확률의 합은 1이므로 가장 오른쪽은 1의 값을 가지게 됩니다.</p>
<p>이를 [팩터의 결합 방법]에서 계산한 Z-Score에 응용할 수도 있으며, 이 과정은 표 <a href="포트폴리오-구성.html#tab:cdfexam">11.16</a>에 나와있습니다.</p>
<table class="table table-striped table-hover table-condensed table" style="margin-left: auto; margin-right: auto; font-size: 8px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:cdfexam">표 11.16: </span>누적분포함수를 이용한 비중 조절
</caption>
<thead>
<tr>
<th style="text-align:center;">
종목
</th>
<th style="text-align:center;">
PBR
</th>
<th style="text-align:center;">
랭킹
</th>
<th style="text-align:center;">
Z-Score X (-1)
</th>
<th style="text-align:center;">
누적확률
</th>
<th style="text-align:center;">
시가총액비중
</th>
<th style="text-align:center;">
시총 X 누적확률
</th>
<th style="text-align:center;">
비중 재계산
</th>
<th style="text-align:center;">
차이
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
A
</td>
<td style="text-align:center;">
0.50
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1.26
</td>
<td style="text-align:center;">
0.90
</td>
<td style="text-align:center;">
20.69%
</td>
<td style="text-align:center;">
18.56%
</td>
<td style="text-align:center;">
33.10%
</td>
<td style="text-align:center;">
12.38%
</td>
</tr>
<tr>
<td style="text-align:center;">
B
</td>
<td style="text-align:center;">
0.70
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0.63
</td>
<td style="text-align:center;">
0.74
</td>
<td style="text-align:center;">
31.03%
</td>
<td style="text-align:center;">
22.86%
</td>
<td style="text-align:center;">
40.72%
</td>
<td style="text-align:center;">
9.68%
</td>
</tr>
<tr>
<td style="text-align:center;">
C
</td>
<td style="text-align:center;">
1.00
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
0.50
</td>
<td style="text-align:center;">
18.97%
</td>
<td style="text-align:center;">
9.48%
</td>
<td style="text-align:center;">
16.89%
</td>
<td style="text-align:center;">
-2.07%
</td>
</tr>
<tr>
<td style="text-align:center;">
D
</td>
<td style="text-align:center;">
1.20
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
-0.63
</td>
<td style="text-align:center;">
0.26
</td>
<td style="text-align:center;">
13.79%
</td>
<td style="text-align:center;">
3.64%
</td>
<td style="text-align:center;">
6.48%
</td>
<td style="text-align:center;">
-7.32%
</td>
</tr>
<tr>
<td style="text-align:center;">
E
</td>
<td style="text-align:center;">
1.50
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
-1.26
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
15.52%
</td>
<td style="text-align:center;">
1.60%
</td>
<td style="text-align:center;">
2.85%
</td>
<td style="text-align:center;">
-12.67%
</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li>각각의 PBR에 대해 랭킹을 구합니다.</li>
<li>랭킹을 바탕으로 Z-Score를 구하며, 결과에 (-1)을 곱해줍니다. 이는 랭킹이 높은 종목의 경우 Z-Score가 음수로 나오므로, 해당 종목의 누적확률 값을 높게하기 위해 양수로 전환해주는 것입니다.</li>
<li>구해진 Z-Score를 바탕으로 누적확률을 구합니다. 랭킹이 높은 종목, 즉 저PBR일 수록 해당 값이 크게 나옵니다.</li>
<li>지수 내 시가총액비중에 누적확률값을 곱해줍니다. 저PBR 종목일수록 원래의 시가총액비중과 비슷하게 유지되며, 고PBR 종목의 경우 시가총액비중 대비 훨씬 낮을 값을 보입니다.</li>
<li>투자비중의 합이 1이 되도록 재표준화를 해줍니다.</li>
<li>각 종목의 차이를 보면, PBR이 낮을수록 증가되는 비중이 크며, PBR아 높을수록 감소되는 비중 역시 큽니다.</li>
</ol>
<p>이처럼 Z-Score와 누적확률을 이용할 경우 훨씬 팩터에 대한 노출을 크게 할 수 있습니다. 이번에는 KOSPI 200 전 종목을 대상으로 PBR 대상 팩터 틸트 포트폴리오를 구성하도록 하겠습니다.</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="포트폴리오-구성.html#cb473-1"></a>KOSPI200_tilt =<span class="st"> </span>KOSPI200 <span class="op">%&gt;%</span></span>
<span id="cb473-2"><a href="포트폴리오-구성.html#cb473-2"></a><span class="st">  </span><span class="kw">select</span>(종목명, PBR, 시가총액비중, 랭킹) <span class="op">%&gt;%</span></span>
<span id="cb473-3"><a href="포트폴리오-구성.html#cb473-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">zscore =</span> <span class="op">-</span><span class="kw">scale</span>(랭킹),</span>
<span id="cb473-4"><a href="포트폴리오-구성.html#cb473-4"></a>         <span class="dt">cdf =</span> <span class="kw">pnorm</span>(zscore),</span>
<span id="cb473-5"><a href="포트폴리오-구성.html#cb473-5"></a>         투자비중 =<span class="st"> </span>시가총액비중 <span class="op">*</span><span class="st"> </span>cdf,</span>
<span id="cb473-6"><a href="포트폴리오-구성.html#cb473-6"></a>         투자비중 =<span class="st"> </span>투자비중 <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(투자비중),</span>
<span id="cb473-7"><a href="포트폴리오-구성.html#cb473-7"></a>         차이 =<span class="st"> </span>투자비중 <span class="op">-</span><span class="st"> </span>시가총액비중)</span></code></pre></div>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="포트폴리오-구성.html#cb474-1"></a><span class="kw">head</span>(KOSPI200_tilt)</span></code></pre></div>
<pre><code>##             종목명   PBR 시가총액비중  랭킹  zscore
## 1         삼성전자  1.97      0.26142 126.5 -0.4492
## 2       SK하이닉스  1.78      0.05076 120.0 -0.3369
## 3           LG화학  3.77      0.03431 159.0 -1.0108
## 4 삼성바이오로직스 12.26      0.03168 189.0 -1.5291
## 5         셀트리온 17.00      0.02832 193.0 -1.5982
## 6            NAVER  8.11      0.02783 185.0 -1.4600
##       cdf 투자비중      차이
## 1 0.32663 0.210228 -0.051194
## 2 0.36809 0.045998 -0.004759
## 3 0.15606 0.013181 -0.021125
## 4 0.06312 0.004923 -0.026760
## 5 0.05500 0.003834 -0.024483
## 6 0.07214 0.004943 -0.022885</code></pre>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="포트폴리오-구성.html#cb476-1"></a><span class="kw">tail</span>(KOSPI200_tilt)</span></code></pre></div>
<pre><code>##               종목명  PBR 시가총액비중  랭킹  zscore
## 195       한미반도체 4.14    0.0004859 164.0 -1.0972
## 196 동아쏘시오홀딩스 1.08    0.0004784  92.0  0.1469
## 197         동원산업 0.77    0.0004768  68.5  0.5529
## 198             풍산 0.58    0.0004739  36.5  1.1058
## 199           에스엘 0.58    0.0004719  36.5  1.1058
## 200       신성이엔지 5.58    0.0004682 174.0 -1.2699
##        cdf  투자비중       차이
## 195 0.1363 0.0001630 -0.0003229
## 196 0.5584 0.0006577  0.0001793
## 197 0.7098 0.0008333  0.0003565
## 198 0.8656 0.0010100  0.0005360
## 199 0.8656 0.0010057  0.0005338
## 200 0.1021 0.0001176 -0.0003506</code></pre>
<ol style="list-style-type: decimal">
<li>먼저 필요한 열만 선택합니다.</li>
<li><code>scale()</code> 함수를 통해 Z-Score를 구하며, (-1)을 곱해줍니다.</li>
<li><code>pnorm()</code> 함수를 통해 누적확률 값을 구해집니다.</li>
<li>시가총액비중에 누적확률을 곱해 새로운 투자비중을 구한 후, 이를 재표준화 해줍니다.</li>
<li>틸트된 비중과 기존 비중간의 차이를 구합니다.</li>
</ol>
<p>위 방법은 시가총액비중이 클수록, 그리고 Z-Score의 절대값이 클수록 비중의 차이가 많이 발생하게 됩니다. 각 종목의 투자비중을 그림으로 나타내겠습니다.</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="포트폴리오-구성.html#cb478-1"></a>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb478-2"><a href="포트폴리오-구성.html#cb478-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 시가총액비중)) <span class="op">+</span></span>
<span id="cb478-3"><a href="포트폴리오-구성.html#cb478-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb478-4"><a href="포트폴리오-구성.html#cb478-4"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> KOSPI200_tilt, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 투자비중),</span>
<span id="cb478-5"><a href="포트폴리오-구성.html#cb478-5"></a>             <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">shape =</span> <span class="dv">4</span>) <span class="op">+</span></span>
<span id="cb478-6"><a href="포트폴리오-구성.html#cb478-6"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb478-7"><a href="포트폴리오-구성.html#cb478-7"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;비중(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb478-8"><a href="포트폴리오-구성.html#cb478-8"></a><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.03</span>)) <span class="op">+</span></span>
<span id="cb478-9"><a href="포트폴리오-구성.html#cb478-9"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">5</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb478-10"><a href="포트폴리오-구성.html#cb478-10"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent) <span class="op">+</span></span>
<span id="cb478-11"><a href="포트폴리오-구성.html#cb478-11"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-56-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>검은색 점은 인덱스 내 시가총액비중이며, 붉은색 엑스표시는 새롭게 구한 투자비중입니다. 단순이 동일한 비중을 더하거나 빼는것 보다 비중 차이의 폭이 훨씬 크며, 이는 전체 포트폴리오가 팩터에 노출된 정도가 크다는 것을 의미합니다.</p>
<p>그러나 실무에서는 이러한 차이가 지나치게 벌어지는 것을 방지하기 위한 제약이 있습니다. 그 예로써 종목당 시가총액비중과 투자비중의 차이가 50bp 이상이 되지 않는 제약이 있는 경우를 생각해봅시다. (제약을 더 크게 설정할 수록, 지수 대비 베팅의 크기가 커집니다.)</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="포트폴리오-구성.html#cb479-1"></a>KOSPI200_tilt <span class="op">%&gt;%</span></span>
<span id="cb479-2"><a href="포트폴리오-구성.html#cb479-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 차이)) <span class="op">+</span></span>
<span id="cb479-3"><a href="포트폴리오-구성.html#cb479-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb479-4"><a href="포트폴리오-구성.html#cb479-4"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.005</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb479-5"><a href="포트폴리오-구성.html#cb479-5"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">-0.005</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb479-6"><a href="포트폴리오-구성.html#cb479-6"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb479-7"><a href="포트폴리오-구성.html#cb479-7"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;비중 차이(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb479-8"><a href="포트폴리오-구성.html#cb479-8"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">5</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb479-9"><a href="포트폴리오-구성.html#cb479-9"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent) <span class="op">+</span></span>
<span id="cb479-10"><a href="포트폴리오-구성.html#cb479-10"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-57-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>시가총액이 큰 종목의 경우 허용치인 50bp를 넘어가는 경우가 다수 존재합니다. 이를 방지하기 위해 비중에 제약조건을 두어야 합니다. 예를 들어 삼성전자의 경우 둘 간의 비중의 차이가 -0.0512 로 지나치게 크므로 [시가총액비중 - 50bp] 가 투자되도록 변경해 줍니다. 타 종목 역시 이와 동일하게 제약조건을 추가해 줍니다.</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="포트폴리오-구성.html#cb480-1"></a>KOSPI200_tilt =<span class="st"> </span>KOSPI200_tilt <span class="op">%&gt;%</span></span>
<span id="cb480-2"><a href="포트폴리오-구성.html#cb480-2"></a><span class="st">    </span><span class="kw">mutate_at</span>(<span class="kw">vars</span>(투자비중), <span class="kw">list</span>(<span class="op">~</span><span class="kw">ifelse</span>(차이 <span class="op">&lt;</span><span class="st"> </span><span class="fl">-0.005</span>, 시가총액비중 <span class="op">-</span><span class="st"> </span><span class="fl">0.005</span>, 투자비중))) <span class="op">%&gt;%</span></span>
<span id="cb480-3"><a href="포트폴리오-구성.html#cb480-3"></a><span class="st">    </span><span class="kw">mutate_at</span>(<span class="kw">vars</span>(투자비중), <span class="kw">list</span>(<span class="op">~</span><span class="kw">ifelse</span>(차이 <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.005</span>, 시가총액비중 <span class="op">+</span><span class="st"> </span><span class="fl">0.005</span>, 투자비중))) <span class="op">%&gt;%</span></span>
<span id="cb480-4"><a href="포트폴리오-구성.html#cb480-4"></a><span class="st">    </span><span class="kw">mutate</span>(투자비중 =<span class="st"> </span>투자비중 <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(투자비중), </span>
<span id="cb480-5"><a href="포트폴리오-구성.html#cb480-5"></a>               차이 =<span class="st"> </span>투자비중 <span class="op">-</span><span class="st"> </span>시가총액비중)</span>
<span id="cb480-6"><a href="포트폴리오-구성.html#cb480-6"></a></span>
<span id="cb480-7"><a href="포트폴리오-구성.html#cb480-7"></a><span class="kw">head</span>(KOSPI200_tilt)</span></code></pre></div>
<pre><code>##             종목명   PBR 시가총액비중  랭킹  zscore
## 1         삼성전자  1.97      0.26142 126.5 -0.4492
## 2       SK하이닉스  1.78      0.05076 120.0 -0.3369
## 3           LG화학  3.77      0.03431 159.0 -1.0108
## 4 삼성바이오로직스 12.26      0.03168 189.0 -1.5291
## 5         셀트리온 17.00      0.02832 193.0 -1.5982
## 6            NAVER  8.11      0.02783 185.0 -1.4600
##       cdf 투자비중      차이
## 1 0.32663  0.23829 -0.023132
## 2 0.36809  0.04275 -0.008012
## 3 0.15606  0.02723 -0.007072
## 4 0.06312  0.02480 -0.006887
## 5 0.05500  0.02167 -0.006649
## 6 0.07214  0.02121 -0.006614</code></pre>
<ol style="list-style-type: decimal">
<li><code>mutate_at()</code> 함수를 이용해 시가총액비중과 투자비중의 차이가 50bp 미만일 경우 투자비중을 [시가총액 - 50bp]로 변경해주며, 50bp 초과일 경우 [시가총액 + 50bp]로 변경해줍니다.</li>
<li>재표준화 작업을 거쳐준 후 차이를 다시 계산합니다.</li>
</ol>
<p>위 방법을 통해 차이가 50bp가 되도록 강제로 설정하였으나, 재표준화를 거치는 과정에서 차이가 50bp를 넘는 종목이 다시 발생하게 됩니다. 모든 종목의 차이가 50bp 이내가 되도록 해당 작업을 반복해줍니다.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="포트폴리오-구성.html#cb482-1"></a><span class="cf">while</span> (<span class="kw">max</span>(<span class="kw">abs</span>(KOSPI200_tilt<span class="op">$</span>차이)) <span class="op">&gt;</span><span class="st"> </span>(<span class="fl">0.005</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.00001</span>)) {</span>
<span id="cb482-2"><a href="포트폴리오-구성.html#cb482-2"></a>  KOSPI200_tilt =<span class="st"> </span>KOSPI200_tilt <span class="op">%&gt;%</span></span>
<span id="cb482-3"><a href="포트폴리오-구성.html#cb482-3"></a><span class="st">    </span><span class="kw">mutate_at</span>(<span class="kw">vars</span>(투자비중), <span class="kw">list</span>(<span class="op">~</span><span class="kw">ifelse</span>(차이 <span class="op">&lt;</span><span class="st"> </span><span class="fl">-0.005</span>, 시가총액비중 <span class="op">-</span><span class="st"> </span><span class="fl">0.005</span>, 투자비중))) <span class="op">%&gt;%</span></span>
<span id="cb482-4"><a href="포트폴리오-구성.html#cb482-4"></a><span class="st">    </span><span class="kw">mutate_at</span>(<span class="kw">vars</span>(투자비중), <span class="kw">list</span>(<span class="op">~</span><span class="kw">ifelse</span>(차이 <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.005</span>, 시가총액비중 <span class="op">+</span><span class="st"> </span><span class="fl">0.005</span>, 투자비중))) <span class="op">%&gt;%</span></span>
<span id="cb482-5"><a href="포트폴리오-구성.html#cb482-5"></a><span class="st">    </span><span class="kw">mutate</span>(투자비중 =<span class="st"> </span>투자비중 <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(투자비중), </span>
<span id="cb482-6"><a href="포트폴리오-구성.html#cb482-6"></a>               차이 =<span class="st"> </span>투자비중 <span class="op">-</span><span class="st"> </span>시가총액비중)</span>
<span id="cb482-7"><a href="포트폴리오-구성.html#cb482-7"></a>}</span>
<span id="cb482-8"><a href="포트폴리오-구성.html#cb482-8"></a></span>
<span id="cb482-9"><a href="포트폴리오-구성.html#cb482-9"></a><span class="kw">head</span>(KOSPI200_tilt)</span></code></pre></div>
<pre><code>##             종목명   PBR 시가총액비중  랭킹  zscore
## 1         삼성전자  1.97      0.26142 126.5 -0.4492
## 2       SK하이닉스  1.78      0.05076 120.0 -0.3369
## 3           LG화학  3.77      0.03431 159.0 -1.0108
## 4 삼성바이오로직스 12.26      0.03168 189.0 -1.5291
## 5         셀트리온 17.00      0.02832 193.0 -1.5982
## 6            NAVER  8.11      0.02783 185.0 -1.4600
##       cdf 투자비중      차이
## 1 0.32663  0.25641 -0.005007
## 2 0.36809  0.04576 -0.005001
## 3 0.15606  0.02931 -0.005001
## 4 0.06312  0.02668 -0.005001
## 5 0.05500  0.02332 -0.005001
## 6 0.07214  0.02283 -0.005001</code></pre>
<p>위와 동일한 코드에 <code>while()</code> 구문을 활용하여 둘 간의 차이가 50bp 보다 클 경우 해당 작업을 계속해서 반복하며, 결과적으로 차이가 거의 50bp에 수렴합니다.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="포트폴리오-구성.html#cb484-1"></a>KOSPI200_tilt <span class="op">%&gt;%</span></span>
<span id="cb484-2"><a href="포트폴리오-구성.html#cb484-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 차이)) <span class="op">+</span></span>
<span id="cb484-3"><a href="포트폴리오-구성.html#cb484-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb484-4"><a href="포트폴리오-구성.html#cb484-4"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">0.005</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb484-5"><a href="포트폴리오-구성.html#cb484-5"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> <span class="fl">-0.005</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb484-6"><a href="포트폴리오-구성.html#cb484-6"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb484-7"><a href="포트폴리오-구성.html#cb484-7"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;비중 차이(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb484-8"><a href="포트폴리오-구성.html#cb484-8"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">5</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb484-9"><a href="포트폴리오-구성.html#cb484-9"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent) <span class="op">+</span></span>
<span id="cb484-10"><a href="포트폴리오-구성.html#cb484-10"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-60-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>모든 종목이 제약조건 내에 들어오게 되었습니다.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="포트폴리오-구성.html#cb485-1"></a>KOSPI200 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb485-2"><a href="포트폴리오-구성.html#cb485-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 시가총액비중)) <span class="op">+</span></span>
<span id="cb485-3"><a href="포트폴리오-구성.html#cb485-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb485-4"><a href="포트폴리오-구성.html#cb485-4"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> KOSPI200_tilt, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, <span class="op">-</span>시가총액비중), <span class="dt">y =</span> 투자비중),</span>
<span id="cb485-5"><a href="포트폴리오-구성.html#cb485-5"></a>             <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">shape =</span> <span class="dv">4</span>) <span class="op">+</span></span>
<span id="cb485-6"><a href="포트폴리오-구성.html#cb485-6"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb485-7"><a href="포트폴리오-구성.html#cb485-7"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;비중(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb485-8"><a href="포트폴리오-구성.html#cb485-8"></a><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.03</span>)) <span class="op">+</span></span>
<span id="cb485-9"><a href="포트폴리오-구성.html#cb485-9"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">5</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb485-10"><a href="포트폴리오-구성.html#cb485-10"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent) <span class="op">+</span></span>
<span id="cb485-11"><a href="포트폴리오-구성.html#cb485-11"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-61-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>제약조건으로 인해 기초지수와의 차이가 줄어들었지만, 기존 단순가감법 보다는 적극적으로 베팅이 되었습니다.</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="포트폴리오-구성.html#cb486-1"></a>KOSPI200_tilt_mod =<span class="st"> </span>KOSPI200_tilt <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(PBR)</span>
<span id="cb486-2"><a href="포트폴리오-구성.html#cb486-2"></a></span>
<span id="cb486-3"><a href="포트폴리오-구성.html#cb486-3"></a>KOSPI200_tilt_mod <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb486-4"><a href="포트폴리오-구성.html#cb486-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, PBR), <span class="dt">y =</span> 차이)) <span class="op">+</span></span>
<span id="cb486-5"><a href="포트폴리오-구성.html#cb486-5"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb486-6"><a href="포트폴리오-구성.html#cb486-6"></a><span class="st">  </span><span class="kw">geom_col</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(종목명, PBR), <span class="dt">y =</span> PBR <span class="op">/</span><span class="dv">2000</span>), <span class="dt">fill =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">alpha =</span> <span class="fl">0.2</span>) <span class="op">+</span></span>
<span id="cb486-7"><a href="포트폴리오-구성.html#cb486-7"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;종목명&#39;</span>) <span class="op">+</span></span>
<span id="cb486-8"><a href="포트폴리오-구성.html#cb486-8"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;차이(%)&#39;</span>) <span class="op">+</span></span>
<span id="cb486-9"><a href="포트폴리오-구성.html#cb486-9"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>percent, </span>
<span id="cb486-10"><a href="포트폴리오-구성.html#cb486-10"></a>                     <span class="dt">sec.axis =</span> <span class="kw">sec_axis</span>(<span class="op">~</span>. <span class="op">*</span><span class="st"> </span><span class="dv">2000</span>, <span class="dt">name =</span> <span class="st">&quot;PBR&quot;</span>)) <span class="op">+</span></span>
<span id="cb486-11"><a href="포트폴리오-구성.html#cb486-11"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">breaks =</span> KOSPI200_mod[<span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">by =</span> <span class="dv">10</span>), <span class="st">&#39;종목명&#39;</span>]) <span class="op">+</span></span>
<span id="cb486-12"><a href="포트폴리오-구성.html#cb486-12"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">60</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="11-portfolio_files/figure-html/unnamed-chunk-62-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>PBR에 따른 비중의 차이 역시 단순 가감법보다 훨씬 증가했습니다. 실무에서는 단순히 PBR처럼 하나의 지표만 살펴보기 보다는 앞서 살펴본 멀티팩터를 이용해 비중을 틸트하기도 하며, 좀 더 다양한 제약조건을 추가하기도 합니다.</p>

</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-choueifaty2008toward">
<p>Choueifaty, Yves, and Yves Coignard. 2008. “Toward Maximum Diversification.” <em>The Journal of Portfolio Management</em> 35 (1): 40–51.</p>
</div>
<div id="ref-choueifaty2013properties">
<p>Choueifaty, Yves, Tristan Froidure, and Julien Reynier. 2013. “Properties of the Most Diversified Portfolio.” <em>Journal of Investment Strategies</em> 2 (2): 49–70.</p>
</div>
<div id="ref-qian2011risk">
<p>Qian, Edward. 2011. “Risk Parity and Diversification.” <em>The Journal of Investing</em> 20 (1): 119–27.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="18">
<li id="fn18"><p>엄밀하게는 mrc가 아닌 rc가 맞는 용어입니다.<a href="포트폴리오-구성.html#fnref18" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<div id="disqus_thread"></div>
<script>

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://quant-cookbook.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            </section>

          </div>
        </div>
      </div>
<a href="퀀트-전략을-이용한-종목선정-심화.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="포트폴리오-백테스트.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"split_bib": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
